// Master Dataset for Blended Colours with Authentic Specifications and Test Data
// Images imported directly from src/assets/img/efc/

import eggYellowImg from '../assets/img/efc/egg-yellow.jpg'
import orangeRedImg from '../assets/img/efc/orange-red.jpg'
import strawberryRedImg from '../assets/img/efc/strawberry-red.jpg'
import rosePinkImg from '../assets/img/efc/Pink-Rose.jpg'
import raspberryRedImg from '../assets/img/efc/raspberry-red.jpg'
import darkOrangeImg from '../assets/img/efc/dark-orange.jpg'
import purpleImg from '../assets/img/efc/purple.jpg'
import violetImg from '../assets/img/efc/violet.jpg'
import coffeeBrownImg from '../assets/img/efc/coffee-brown.jpg'
import chocolateBrownImg from '../assets/img/efc/chocolate-brown.jpg'
import limeGreenImg from '../assets/img/efc/lime-green.jpg'
import blackImg from '../assets/img/efc/black.png'
import grapeImg from '../assets/img/efc/grape.jpeg'
import falsaImg from '../assets/img/efc/falsa.jpg'
import darkChocolateImg from '../assets/img/efc/Dark-Chocolate.jpg'
import appleGreenImg from '../assets/img/efc/apple-green.jpg'
import peaGreenImg from '../assets/img/efc/Pea-Green-Food-Colour.jpg'
import blackCurrentImg from '../assets/img/efc/current black.jpg'
import khalaKhattaImg from '../assets/img/efc/kala khatta.jpg'

export const BLENDED_ANALYSIS_SPECS = [
  { characteristic: 'Assay / Total Pure Dye Content, Min.', requirement: '85.00%' },
  { characteristic: 'Water – Insoluble matter by mass, Max.', requirement: '00.20%' },
  { characteristic: 'Unsulfonated Primary Aromatic Amines (as aniline), Max.', requirement: '00.01%' },
  { characteristic: 'Lead (Pb), mg/kg, Max.', requirement: '02 ppm' },
  { characteristic: 'Arsenic (As), mg/kg, Max.', requirement: '03 ppm' },
  { characteristic: 'Cadmium (Cd), mg/kg, Max.', requirement: '01 ppm' },
  { characteristic: 'Mercury (Hg), mg/kg, Max.', requirement: '01 ppm' },
  { characteristic: 'Heavy metals (as Pb), mg/kg, Max.', requirement: '40 ppm' },
]

export const BLENDED_COLORS = [
  {
    id: 'egg-yellow',
    name: 'Egg Yellow',
    colorFamily: 'yellow-orange',
    colorHex: '#eab308',
    moq: '250 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Egg yellow blended colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Egg Yellow',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Yellow Powder',
    applicationSummary: 'Bakery, Biscuits, Confectionery, Dairy & Beverages',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: eggYellowImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'orange-red',
    name: 'Orange Red',
    colorFamily: 'yellow-orange',
    colorHex: '#ea580c',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Orange Red Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Orange Red',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Orange Red Powder',
    applicationSummary: 'Confectionery, Sauces, Snacks, Syrups & Carbonated Drinks',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: orangeRedImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'strawberry-red',
    name: 'Strawberry Red',
    colorFamily: 'red-pink',
    colorHex: '#e11d48',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Strawberry Red Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Strawberry Red',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Vibrant Red Powder',
    applicationSummary: 'Jams, Jellies, Ice Creams, Candies & Fruit Preparations',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: strawberryRedImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'rose-pink',
    name: 'Rose Pink',
    colorFamily: 'red-pink',
    colorHex: '#f43f5e',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Rose Pink Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Rose Pink',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Pink Powder',
    applicationSummary: 'Rose Milk, Falooda, Fondant, Marshmallows & Syrups',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: rosePinkImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'raspberry-red',
    name: 'Raspberry Red',
    colorFamily: 'red-pink',
    colorHex: '#be123c',
    moq: '250 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Raspberry Red Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Raspberry Red',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Deep Red Powder',
    applicationSummary: 'Beverages, Jellies, Dessert Toppings & Confectionery',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: raspberryRedImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'dark-orange',
    name: 'Dark Orange',
    colorFamily: 'yellow-orange',
    colorHex: '#c2410c',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Dark Orange Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Dark Orange',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Intense Orange Powder',
    applicationSummary: 'Squashes, Ready-to-Drink Juices, Pastries & Seasonings',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: darkOrangeImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'purple',
    name: 'Purple',
    colorFamily: 'violet-purple',
    colorHex: '#7e22ce',
    moq: '250 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Purple Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Purple',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Purple Powder',
    applicationSummary: 'Flavored Drinks, Popsicles, Hard Boiled Candies & Bakery Icings',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: purpleImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'violet',
    name: 'Violet',
    colorFamily: 'violet-purple',
    colorHex: '#6b21a8',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Violet Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Violet',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Violet Powder',
    applicationSummary: 'Blackcurrant Drinks, Confectionery, Syrups & Pharma Syrups',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: violetImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'coffee-brown',
    name: 'Coffee Brown',
    colorFamily: 'brown-black',
    colorHex: '#78350f',
    moq: '250 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Coffee Brown Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Coffee Brown',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Rich Coffee Brown Powder',
    applicationSummary: 'Coffee Premixes, Bakery, Toffees, Chocolate Fillings & Custards',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: coffeeBrownImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'chocolate-brown',
    name: 'Chocolate Brown',
    colorFamily: 'brown-black',
    colorHex: '#451a03',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Chocolate Brown Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Chocolate Brown',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Deep Chocolate Powder',
    applicationSummary: 'Cakes, Cookies, Chocolate Syrups, Pudding Powders & Ice Cream',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: chocolateBrownImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'lime-green',
    name: 'Lime Green',
    colorFamily: 'green',
    colorHex: '#65a30d',
    moq: '250 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Lime Green Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lime Green',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Fresh Lime Green Powder',
    applicationSummary: 'Lime Cordials, Soft Drink Concentrates, Candies & Gums',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: limeGreenImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'black',
    name: 'Black',
    colorFamily: 'brown-black',
    colorHex: '#18181b',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Black Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Black',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Jet Black Powder',
    applicationSummary: 'Liquorice, Dark Confectionery, Savory Sauces & Baked Goods',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: blackImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'grape',
    name: 'Grape',
    colorFamily: 'violet-purple',
    colorHex: '#581c87',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Grape Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Grape',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Deep Grape Powder',
    applicationSummary: 'Grape Juices, Jellies, Soda Pops, Chews & Syrups',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: grapeImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'falsa',
    name: 'Falsa',
    colorFamily: 'violet-purple',
    colorHex: '#4c1d95',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Falsa Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Falsa',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Dark Berry / Falsa Powder',
    applicationSummary: 'Ethnic Sherbets, Fruit Squash, Slushies & Candies',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: falsaImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'dark-chocolate',
    name: 'Dark Chocolate',
    colorFamily: 'brown-black',
    colorHex: '#3b1a0a',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Dark Chocolate Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Dark Chocolate',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Intense Dark Cocoa Powder Tone',
    applicationSummary: 'Dark Compound, Truffles, Brownies, Chocolate Sauces & Milkshakes',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: darkChocolateImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'apple-green',
    name: 'Apple Green',
    colorFamily: 'green',
    colorHex: '#22c55e',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Apple Green Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Apple Green',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Bright Apple Green Powder',
    applicationSummary: 'Popsicles, Carbonated Drinks, Jellies, Mints & Pastries',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: appleGreenImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'pea-green',
    name: 'Pea Green',
    colorFamily: 'green',
    colorHex: '#15803d',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Pea Green Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pea Green',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Natural Pea Green Powder',
    applicationSummary: 'Canned Vegetables, Savory Snacks, Soups & Seasoning Mixes',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: peaGreenImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'black-current',
    name: 'Black Current',
    colorFamily: 'brown-black',
    colorHex: '#312e81',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Black Current Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Black Current',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Dark Purple-Black Powder',
    applicationSummary: 'Ice Creams, Mocktail Syrups, Fruit Crushes & Chewable Tablets',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: blackCurrentImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
  {
    id: 'khala-khatta',
    name: 'Khala Khatta',
    colorFamily: 'brown-black',
    colorHex: '#1e1b4b',
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'N/A (Blend)',
    otherNames: 'Khala Khatta Blended Colour',
    mf: 'Custom Formulation',
    einecsNo: 'Blend',
    femaNo: 'N/A',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents',
    brandName: 'Exim India Corporation',
    modelNumber: 'Khala Khatta',
    grade: 'Cosmetic, Food Grade, Pharmaceutical Grade',
    colorDesc: 'Deep Dark Purple-Black Powder',
    applicationSummary: 'Kala Khatta Chuskis, Crushes, Ice Golas, Beverage Syrups & Candies',
    purity: '85.00% Min (Assay)',
    shelfLife: '2 - 3 Years',
    packagingDetails: '10/25/50 Kgs HDPE Drums/Bags or as per requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: khalaKhattaImg,
    analysis: BLENDED_ANALYSIS_SPECS,
  },
]
