// Master Dataset for Cosmetic Colours with Authentic Specifications and Quality Analysis Data
// Images imported directly from src/assets/img/cosmetic-color/

import blueImg from '../assets/img/cosmetic-color/blue.jpg'
import orange1Img from '../assets/img/cosmetic-color/orange1.jpg'
import orange2Img from '../assets/img/cosmetic-color/orange2.jpg'
import orange3Img from '../assets/img/cosmetic-color/orange3.jpg'
import pink1Img from '../assets/img/cosmetic-color/pink1.jpg'
import pink2Img from '../assets/img/cosmetic-color/pink2.jpg'
import pink3Img from '../assets/img/cosmetic-color/pink3.jpg'
import pink4Img from '../assets/img/cosmetic-color/pink4.jpg'
import pink5Img from '../assets/img/cosmetic-color/pink5.jpg'
import purple1Img from '../assets/img/cosmetic-color/purple1.jpg'
import purple2Img from '../assets/img/cosmetic-color/purple2.jpg'
import purple3Img from '../assets/img/cosmetic-color/purple3.jpg'
import redImg from '../assets/img/cosmetic-color/red.jpg'
import yellow1Img from '../assets/img/cosmetic-color/yellow1.jpg'
import yellow2Img from '../assets/img/cosmetic-color/yellow2.jpg'

export const COSMETIC_ANALYSIS_SPECS = [
  { characteristic: 'Total Pure Dye Content (High/Low Dye options)', requirement: '15.00% – 40.00% (Lakes) / 85.00% (Salts)' },
  { characteristic: 'Volatile Matter (Moisture) at 135°C, Max.', requirement: '12.00%' },
  { characteristic: 'Water-Soluble Chlorides & Sulphates, Max.', requirement: '02.00%' },
  { characteristic: 'Unreacted Intermediates & Subsidiary Dyes, Max.', requirement: '01.00%' },
  { characteristic: 'Lead (Pb), mg/kg, Max.', requirement: '10.00 ppm' },
  { characteristic: 'Arsenic (As), mg/kg, Max.', requirement: '02.00 ppm' },
  { characteristic: 'Mercury (Hg), mg/kg, Max.', requirement: '01.00 ppm' },
  { characteristic: 'Cadmium (Cd), mg/kg, Max.', requirement: '01.00 ppm' },
  { characteristic: 'Barium (Ba) soluble in dilute HCl, Max.', requirement: '500.00 ppm' },
  { characteristic: 'Total Heavy Metals (as Pb), Max.', requirement: '20.00 ppm' },
]

export const COSMETIC_COLORS = [
  {
    id: 'dc-red-7-ca-lake',
    name: 'D & C Red 7 Ca Lake',
    categoryType: 'lake',
    colorFamily: 'reds-pinks',
    colorHex: '#e11d48',
    ciNo: '15850:1',
    casNo: '5281-04-9',
    einecsNo: '226-109-5',
    femaNo: 'N/A',
    otherNames: 'Lithol Rubine BK Calcium Lake, Pigment Red 57:1',
    mf: 'C18H12CaN2O6S',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Calcium Lakes, Make-up Colorants',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 7 Lake',
    grade: 'Cosmetic Grade (US-FDA, EU 1223/2009 & BIS Approved)',
    colorDesc: 'Fine Crimson Red Powder',
    applicationSummary: 'Lipsticks, Lip Glosses, Nail Lacquers, Rouge & Blushers',
    purity: '24% – 28% Pure Dye Content (Customizable)',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: pink1Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-red-21-al-lake',
    name: 'D & C Red 21 Al Lake',
    categoryType: 'lake',
    colorFamily: 'reds-pinks',
    colorHex: '#f43f5e',
    ciNo: '45380:3',
    casNo: '15086-94-9',
    einecsNo: '239-138-3',
    femaNo: 'N/A',
    otherNames: 'Tetrabromofluorescein Aluminum Lake, Solvent Red 43 Lake',
    mf: 'C20H8Br4O5·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Aluminum Lakes, Color-Changing Dyes',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 21 Lake',
    grade: 'Cosmetic Grade (US-FDA & EU 1223/2009 Compliant)',
    colorDesc: 'Bright Pinkish-Orange to Pink Powder',
    applicationSummary: 'Mood Lipsticks, Lip Stains, Lip Balms & Blush Powders',
    purity: '15% – 25% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: pink2Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-red-27-al-lake',
    name: 'D & C Red 27 Al Lake',
    categoryType: 'lake',
    colorFamily: 'reds-pinks',
    colorHex: '#ec4899',
    ciNo: '45410:2',
    casNo: '13473-26-2',
    einecsNo: '236-747-6',
    femaNo: 'N/A',
    otherNames: 'Tetrachlorotetrabromofluorescein Aluminum Lake',
    mf: 'C20H4Br4Cl4O5·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Aluminum Lakes, pH Indicator Dyes',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 27 Lake',
    grade: 'Cosmetic Grade (US-FDA, EU 1223/2009 Compliant)',
    colorDesc: 'Vibrant Magenta-Pink Powder',
    applicationSummary: 'pH Lipsticks, Lip Tints, Bath Bombs, Lip Glosses & Nail Enamels',
    purity: '20% – 30% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: pink3Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-red-30-lake',
    name: 'D & C Red 30 Lake',
    categoryType: 'lake',
    colorFamily: 'reds-pinks',
    colorHex: '#e11d48',
    ciNo: '73360',
    casNo: '2379-74-0',
    einecsNo: '219-163-6',
    femaNo: 'N/A',
    otherNames: 'Thioindigo Red Lake, Vat Red 1 Lake',
    mf: 'C16H8Cl2O2S2',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Insoluble Pigments, Thioindigo Colorants',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 30 Lake',
    grade: 'Cosmetic Grade (US-FDA & EU Compliant)',
    colorDesc: 'Warm Coral-Pink Powder',
    applicationSummary: 'Pressed Powders, Cream Blushers, Lipsticks & Eye Makeup',
    purity: '30% – 40% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: pink4Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-red-33-lake',
    name: 'D & C Red 33 Lake',
    categoryType: 'lake',
    colorFamily: 'reds-pinks',
    colorHex: '#9333ea',
    ciNo: '17200:1',
    casNo: '3567-66-6 (Lake Form)',
    einecsNo: '222-656-9',
    femaNo: 'N/A',
    otherNames: 'Acid Red 33 Aluminum Lake, Fast Acid Magenta Lake',
    mf: 'C16H11N3Na2O7S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Azo Lakes, Deep Berry Colorants',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 33 Lake',
    grade: 'Cosmetic Grade (US-FDA, EU Compliant)',
    colorDesc: 'Plum / Deep Fuchsia Powder',
    applicationSummary: 'Lip Liners, Nail Polishes, Bath & Body Products, Hair Shampoos',
    purity: '20% – 25% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: purple1Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-red-34-lake',
    name: 'D & C Red 34 Lake',
    categoryType: 'lake',
    colorFamily: 'reds-pinks',
    colorHex: '#701a75',
    ciNo: '15880:1',
    casNo: '6417-83-6',
    einecsNo: '229-142-3',
    femaNo: 'N/A',
    otherNames: 'Deep Maroon Lake, Pigment Red 63:1 Calcium Lake',
    mf: 'C21H12CaN2O6S',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Deep Maroon Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 34 Lake',
    grade: 'Cosmetic Grade (US-FDA, EU Compliant)',
    colorDesc: 'Deep Rich Bordeaux / Maroon Powder',
    applicationSummary: 'Nail Enamels, Dark Lipsticks, Bronzers & Contouring Palettes',
    purity: '25% – 35% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: purple2Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'fdc-red-40-lake',
    name: 'FD & C Red 40 Lake',
    categoryType: 'lake',
    colorFamily: 'reds-pinks',
    colorHex: '#dc2626',
    ciNo: '16035:1',
    casNo: '68583-95-9',
    einecsNo: '271-524-7',
    femaNo: 'Allura Red AC Lake',
    otherNames: 'Allura Red AC Aluminum Lake, CI Food Red 17:1',
    mf: 'C18H14N2Na2O8S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic & Food Pigments, Aluminum Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'FD&C Red 40 Lake',
    grade: 'Cosmetic & Food Grade (US-FDA 21 CFR, EU 1223/2009)',
    colorDesc: 'Bright Scarlet Red Powder',
    applicationSummary: 'Eye Shadows, Lipsticks, Toothpaste, Blushers & Personal Wash',
    purity: '15% – 40% Pure Dye Content (Low & High Dye Options)',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: orange1Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'fdc-yellow-5-lake',
    name: 'FD & C Yellow 5 Lake',
    categoryType: 'lake',
    colorFamily: 'yellows-oranges',
    colorHex: '#eab308',
    ciNo: '19140:1',
    casNo: '12225-21-7',
    einecsNo: '235-428-9',
    femaNo: 'Tartrazine Lake',
    otherNames: 'Tartrazine Aluminum Lake, Acid Yellow 23 Lake',
    mf: 'C16H9N4Na3O9S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Yellow Aluminum Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'FD&C Yellow 5 Lake',
    grade: 'Cosmetic & Food Grade (US-FDA, EU Compliant)',
    colorDesc: 'Vivid Lemon Yellow Powder',
    applicationSummary: 'Eye Makeup, Foundations, Lip Balms, Soap Bars & Hair Colors',
    purity: '15% – 38% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: yellow1Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'fdc-yellow-6-lake',
    name: 'FD & C Yellow 6 Lake',
    categoryType: 'lake',
    colorFamily: 'yellows-oranges',
    colorHex: '#ea580c',
    ciNo: '15985:1',
    casNo: '15790-07-5',
    einecsNo: '239-888-1',
    femaNo: 'Sunset Yellow Lake',
    otherNames: 'Sunset Yellow FCF Aluminum Lake, Food Yellow 3:1',
    mf: 'C16H10N2Na2O7S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Orange Aluminum Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'FD&C Yellow 6 Lake',
    grade: 'Cosmetic & Food Grade (US-FDA, EU Compliant)',
    colorDesc: 'Brilliant Sunset Orange Powder',
    applicationSummary: 'Bath Bombs, Foundations, Cream Blushers, Shampoos & Lotions',
    purity: '15% – 40% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: orange2Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-yellow-10-lake',
    name: 'D & C Yellow 10 Lake',
    categoryType: 'lake',
    colorFamily: 'yellows-oranges',
    colorHex: '#facc15',
    ciNo: '47005:1',
    casNo: '68814-04-0',
    einecsNo: '272-364-1',
    femaNo: 'Quinoline Yellow Lake',
    otherNames: 'Quinoline Yellow Aluminum Lake, Acid Yellow 3 Lake',
    mf: 'C18H9NNa2O8S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, High Solubility Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Yellow 10 Lake',
    grade: 'Cosmetic Grade (US-FDA & EU 1223/2009 Compliant)',
    colorDesc: 'Bright Greenish Yellow Powder',
    applicationSummary: 'Soaps, Hair Care, Nail Enamels, Lotions & Bath Salts',
    purity: '15% – 30% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: yellow2Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'fdc-blue-1-lake',
    name: 'FD & C Blue 1 Lake',
    categoryType: 'lake',
    colorFamily: 'blues',
    colorHex: '#0284c7',
    ciNo: '42090:2',
    casNo: '68921-42-6',
    einecsNo: '272-939-6',
    femaNo: 'Brilliant Blue Lake',
    otherNames: 'Brilliant Blue FCF Aluminum Lake, Acid Blue 9 Lake',
    mf: 'C37H34N2Na2O9S3·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Blue Aluminum Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'FD&C Blue 1 Lake',
    grade: 'Cosmetic & Food Grade (US-FDA, EU Compliant)',
    colorDesc: 'Vibrant Royal Blue Powder',
    applicationSummary: 'Eye Liners, Mascaras, Toothpastes, Bath Bombs & Nail Colors',
    purity: '12% – 35% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: blueImg,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-red-6-na-salt',
    name: 'D & C Red 6 Na Salt',
    categoryType: 'salts-toners',
    colorFamily: 'reds-pinks',
    colorHex: '#b91c1c',
    ciNo: '15850',
    casNo: '5858-81-1',
    einecsNo: '227-497-9',
    femaNo: 'Lithol Rubine B Na Salt',
    otherNames: 'Lithol Rubine B Sodium Salt, Pigment Red 57',
    mf: 'C18H12N2Na2O6S',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pure Dyes, Water-Soluble Azo Toners',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 6 Na Salt',
    grade: 'Cosmetic Grade (US-FDA 21 CFR, EU Compliant)',
    colorDesc: 'Fine Deep Red Crystalline Powder',
    applicationSummary: 'Lipsticks, Liquid Foundations, Rouge, Nail Polishes & Cleansers',
    purity: '85.00% Min Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: redImg,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'fdc-red-7-ca-salt',
    name: 'FD & C Red 7 Ca Salt',
    categoryType: 'salts-toners',
    colorFamily: 'reds-pinks',
    colorHex: '#e11d48',
    ciNo: '15850:1',
    casNo: '5281-04-9',
    einecsNo: '226-109-5',
    femaNo: 'Lithol Rubine BK Ca Salt',
    otherNames: 'Lithol Rubine BK Calcium Toner / Salt',
    mf: 'C18H12CaN2O6S',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Toners, Insoluble Organic Salts',
    brandName: 'Exim India Corporation',
    modelNumber: 'FD&C Red 7 Ca Salt',
    grade: 'Cosmetic Grade (US-FDA 21 CFR, EU Compliant)',
    colorDesc: 'Rich Ruby Red Powder',
    applicationSummary: 'Premium Matte Lipsticks, Eye Shadows, Blushers & Face Makeup',
    purity: '85.00% Min Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: pink5Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-red-34-ca-salt',
    name: 'D & C Red 34 Ca Salt',
    categoryType: 'salts-toners',
    colorFamily: 'reds-pinks',
    colorHex: '#831843',
    ciNo: '15880:1',
    casNo: '6417-83-6',
    einecsNo: '229-142-3',
    femaNo: 'Deep Maroon Toner',
    otherNames: 'Pigment Red 63:1 Calcium Toner, Deep Maroon Salt',
    mf: 'C21H12CaN2O6S',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Toners, Organic Calcium Salts',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 34 Ca Salt',
    grade: 'Cosmetic Grade (US-FDA, EU Compliant)',
    colorDesc: 'Intense Maroon-Burgundy Powder',
    applicationSummary: 'Nail Polishes, Lipsticks, Highlighters & Personal Care',
    purity: '85.00% Min Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: purple3Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
  {
    id: 'dc-red-36',
    name: 'D & C Red 36',
    categoryType: 'salts-toners',
    colorFamily: 'yellows-oranges',
    colorHex: '#ea580c',
    ciNo: '12085',
    casNo: '2814-77-9',
    einecsNo: '220-562-2',
    femaNo: 'Flaming Red',
    otherNames: 'Flaming Red, Pigment Red 4, Chlorinated Para Red',
    mf: 'C16H10ClN3O3',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cosmetic Pigments, Monoazo Organic Pigments',
    brandName: 'Exim India Corporation',
    modelNumber: 'D&C Red 36',
    grade: 'Cosmetic Grade (US-FDA 21 CFR, EU Compliant)',
    colorDesc: 'Brilliant Scarlet Orange-Red Powder',
    applicationSummary: 'Lipsticks, Lip Balms, Rouge, Nail Lacquers & Face Powders',
    purity: '85.00% Min Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '10/25 Kgs Fibre Drums / HDPE Drums with double poly liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly closed containers in a cool, dry place protected from sunlight and moisture.',
    image: orange3Img,
    analysis: COSMETIC_ANALYSIS_SPECS,
  },
]
