// Master Dataset for Disco Dust Powder with Authentic Specifications, Shade Matrix and Analytical Data
// Images imported directly from src/assets/img/dust-color/

import goldDustImg from '../assets/img/dust-color/Gold-Disco-Dust.jpg'
import silverDustImg from '../assets/img/dust-color/Silver-Disco-Dust.jpg'
import redDustImg from '../assets/img/dust-color/Red-Disco-Dust.jpg'
import blueDustImg from '../assets/img/dust-color/Blue-Disco-Dust.jpg'
import pinkDustImg from '../assets/img/dust-color/Pink-Disco-Dust.jpg'
import greenDustImg from '../assets/img/dust-color/Green-Disco-Dust.jpg'
import yellowDustImg from '../assets/img/dust-color/Yellow-Disco-Dust.jpg'
import ivoryDustImg from '../assets/img/dust-color/Ivory-Disco-Dust.jpg'
import orangeDustImg from '../assets/img/dust-color/Orange-Disco-Dust.jpg'
import violetDustImg from '../assets/img/dust-color/Violet-Disco-Dust.jpg'

export const DISCO_DUST_ANALYSIS_SPECS = [
  { characteristic: 'Physical Appearance', requirement: 'Ultra-Fine Sparkle Powder / Micro-Prismatic Glitter' },
  { characteristic: 'Particle Size Distribution (D50)', requirement: '15 – 60 Microns (Uniform Sparkle Reflection)' },
  { characteristic: 'Loss on Drying (at 105°C)', requirement: '< 0.50% Max' },
  { characteristic: 'pH Value (10% Aqueous Slurry)', requirement: '6.50 – 8.00' },
  { characteristic: 'Heavy Metals (as Pb), Max.', requirement: '10.00 ppm' },
  { characteristic: 'Lead (Pb), Max.', requirement: '02.00 ppm' },
  { characteristic: 'Arsenic (As), Max.', requirement: '01.00 ppm' },
  { characteristic: 'Mercury (Hg), Max.', requirement: '0.50 ppm' },
  { characteristic: 'Total Aerobic Microbial Count', requirement: '< 100 CFU/g' },
  { characteristic: 'Yeast & Mould Count', requirement: '< 10 CFU/g (Pathogens Absent)' },
]

export const DISCO_DUST_VARIETY_SHADES = [
  // Coppers & Rusts
  { code: '5M', name: 'Dark Copper', group: 'Copper & Bronze', colorHex: '#b45309' },
  { code: '6M', name: 'T.Copper', group: 'Copper & Bronze', colorHex: '#9a3412' },
  { code: '41M', name: 'Copper (Amber)', group: 'Copper & Bronze', colorHex: '#d97706' },
  { code: '3CMT', name: 'Copper Matt', group: 'Copper & Bronze', colorHex: '#c2410c' },
  { code: '43M', name: 'Rust Copper', group: 'Copper & Bronze', colorHex: '#7c2d12' },
  { code: '22M', name: 'Rust Gold', group: 'Golds & Warm Tones', colorHex: '#b45309' },
  { code: '21M', name: 'Sand Storm', group: 'Golds & Warm Tones', colorHex: '#d97706' },
  { code: '51M', name: 'King Gold', group: 'Golds & Warm Tones', colorHex: '#eab308' },
  { code: '52M', name: 'Sand', group: 'Golds & Warm Tones', colorHex: '#ca8a04' },
  { code: '915', name: 'Copper Metallic', group: 'Copper & Bronze', colorHex: '#b45309' },
  { code: '916', name: 'Brown Metallic', group: 'Earthy Tones', colorHex: '#78350f' },
  { code: '925', name: 'L Brown', group: 'Earthy Tones', colorHex: '#92400e' },

  // Oranges
  { code: '23M', name: 'Orange Vivid', group: 'Oranges & Corals', colorHex: '#ea580c' },
  { code: '42M', name: 'Light Orange', group: 'Oranges & Corals', colorHex: '#f97316' },
  { code: '919', name: 'L Orange', group: 'Oranges & Corals', colorHex: '#fb923c' },

  // Blues
  { code: '47M', name: 'Turkish Blue', group: 'Blues & Cyans', colorHex: '#0284c7' },
  { code: '38M', name: 'Turkish Blue Deep', group: 'Blues & Cyans', colorHex: '#0369a1' },
  { code: '15M', name: 'Light Turkish Blue', group: 'Blues & Cyans', colorHex: '#38bdf8' },
  { code: '36M', name: 'Roman Blue', group: 'Blues & Cyans', colorHex: '#1d4ed8' },
  { code: '16M', name: 'Royal Blue', group: 'Blues & Cyans', colorHex: '#1e40af' },
  { code: '35M', name: 'Royal Blue (P7)', group: 'Blues & Cyans', colorHex: '#2563eb' },
  { code: '17M', name: 'Blue (753)', group: 'Blues & Cyans', colorHex: '#0284c7' },
  { code: '33M', name: 'M Blue (714)', group: 'Blues & Cyans', colorHex: '#0ea5e9' },
  { code: '18M', name: 'Light Blue (B)', group: 'Blues & Cyans', colorHex: '#7dd3fc' },
  { code: '34M', name: 'Light Blue (S)', group: 'Blues & Cyans', colorHex: '#38bdf8' },
  { code: '908', name: 'Turkish Blue Special', group: 'Blues & Cyans', colorHex: '#0284c7' },
  { code: '909', name: 'L Turkish Blue', group: 'Blues & Cyans', colorHex: '#7dd3fc' },
  { code: '914', name: 'Dark Blue', group: 'Blues & Cyans', colorHex: '#172554' },

  // Greens
  { code: '45M', name: 'Forest Green', group: 'Greens & Emeralds', colorHex: '#14532d' },
  { code: '13M', name: 'Light Green', group: 'Greens & Emeralds', colorHex: '#22c55e' },
  { code: '12M', name: 'Sea Green', group: 'Greens & Emeralds', colorHex: '#0d9488' },
  { code: '49M', name: 'Sea Green Export', group: 'Greens & Emeralds', colorHex: '#0f766e' },
  { code: '11M', name: 'Parrot Green', group: 'Greens & Emeralds', colorHex: '#16a34a' },
  { code: '48M', name: 'Light Parrot Green', group: 'Greens & Emeralds', colorHex: '#4ade80' },
  { code: '50M', name: 'Apple Green (Dhani)', group: 'Greens & Emeralds', colorHex: '#84cc16' },
  { code: '911', name: 'L Parrot Green', group: 'Greens & Emeralds', colorHex: '#22c55e' },
  { code: '912', name: 'Sea Green Lustre', group: 'Greens & Emeralds', colorHex: '#14b8a6' },
  { code: '921', name: 'L T P.Green', group: 'Greens & Emeralds', colorHex: '#4ade80' },
  { code: '923', name: 'L Green', group: 'Greens & Emeralds', colorHex: '#86efac' },
  { code: '926', name: 'Green Sparkle', group: 'Greens & Emeralds', colorHex: '#15803d' },
  { code: '929', name: 'L Green Pastel', group: 'Greens & Emeralds', colorHex: '#bbf7d0' },

  // Silvers & Sugars
  { code: '1S', name: 'Silver Classic', group: 'Silvers & Gunmetals', colorHex: '#94a3b8' },
  { code: '2S', name: 'Super Silver', group: 'Silvers & Gunmetals', colorHex: '#cbd5e1' },
  { code: '1P', name: 'Poly Sugar Sparkle', group: 'Silvers & Gunmetals', colorHex: '#e2e8f0' },
  { code: '1PS', name: 'Pure Silver Reflector', group: 'Silvers & Gunmetals', colorHex: '#f1f5f9' },

  // Specialized Golds
  { code: '16G', name: 'J D Water Gold', group: 'Golds & Warm Tones', colorHex: '#fbbf24' },
  { code: '17G', name: 'Water (S)', group: 'Golds & Warm Tones', colorHex: '#fde047' },
  { code: '18G', name: 'Water Gold Brilliant', group: 'Golds & Warm Tones', colorHex: '#facc15' },
  { code: '6G', name: 'Pale Gold (703)', group: 'Golds & Warm Tones', colorHex: '#fef08a' },
  { code: '10G', name: 'Pale Gold (704)', group: 'Golds & Warm Tones', colorHex: '#fef9c3' },
  { code: '19G', name: 'D D Gold', group: 'Golds & Warm Tones', colorHex: '#eab308' },
  { code: '20G', name: 'D D Gold (c)', group: 'Golds & Warm Tones', colorHex: '#ca8a04' },
  { code: '7G', name: 'Lemon Gold', group: 'Golds & Warm Tones', colorHex: '#facc15' },
  { code: '9G', name: 'White Gold', group: 'Golds & Warm Tones', colorHex: '#fef3c7' },
  { code: '1G', name: 'Light Gold (705)', group: 'Golds & Warm Tones', colorHex: '#fde68a' },
  { code: '3G', name: 'Medium Gold 211', group: 'Golds & Warm Tones', colorHex: '#eab308' },
  { code: '4G', name: 'Medium Gold (BG2P)', group: 'Golds & Warm Tones', colorHex: '#ca8a04' },
  { code: '11G', name: 'Medium Gold 719', group: 'Golds & Warm Tones', colorHex: '#d97706' },
  { code: '12G', name: 'Medium Gold 719F', group: 'Golds & Warm Tones', colorHex: '#b45309' },
  { code: '13G', name: 'Medium Gold 719 F New', group: 'Golds & Warm Tones', colorHex: '#d97706' },
  { code: '14G', name: 'Medium Gold 102', group: 'Golds & Warm Tones', colorHex: '#eab308' },
  { code: '15G', name: 'Medium Gold L', group: 'Golds & Warm Tones', colorHex: '#facc15' },
  { code: '5G', name: 'Rich Gold (AS)', group: 'Golds & Warm Tones', colorHex: '#d97706' },
  { code: '903', name: 'Gold Prime', group: 'Golds & Warm Tones', colorHex: '#eab308' },
  { code: '904', name: 'Gold Brilliant', group: 'Golds & Warm Tones', colorHex: '#f59e0b' },

  // Reds, Pinks & Purples
  { code: '904R', name: 'Red Sparkle', group: 'Reds & Pinks', colorHex: '#ef4444' },
  { code: '906', name: 'Pink Radiant', group: 'Reds & Pinks', colorHex: '#ec4899' },
  { code: '907', name: 'Red Brilliant', group: 'Reds & Pinks', colorHex: '#dc2626' },
  { code: '918', name: 'L Pink Delicate', group: 'Reds & Pinks', colorHex: '#f472b6' },
  { code: '930', name: 'Onion Pink', group: 'Reds & Pinks', colorHex: '#db2777' },
  { code: '933', name: 'Violet Regal', group: 'Violets & Magentas', colorHex: '#7c3aed' },
  { code: '937', name: 'L Violet Pastel', group: 'Violets & Magentas', colorHex: '#a78bfa' },

  // Gunmetals
  { code: '920', name: 'Gunmetal Sheen', group: 'Silvers & Gunmetals', colorHex: '#475569' },
  { code: '928', name: 'L Gunmetal Soft', group: 'Silvers & Gunmetals', colorHex: '#64748b' },
]

export const DISCO_DUST_POWDERS = [
  {
    id: 'golden-disco-dust',
    name: 'Golden Color Disco Dust',
    colorFamily: 'gold',
    colorHex: '#eab308',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Gold Sparkle Dust, Gold Confectionery Glitter, Luster Dust Gold',
    mf: 'PET / Synthetic Mica / TiO2 / Iron Oxide Blend',
    einecsNo: 'Cosmetic & Confectionery Grade',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Ultra-Fine Reflective Glitter Powder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust GD-01',
    grade: 'Decorative Cake Craft & Cosmetic Grade',
    colorDesc: 'High Brilliance Golden Micro-Flakes',
    applicationSummary: 'Celebration Cakes, Fondant Borders, Sugar Flowers, Edible Accents, Crafts & Cosmetics',
    purity: 'Non-Toxic High Sheen Formulation',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers / Poly Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: goldDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'silver-disco-dust',
    name: 'Silver Color Disco Dust',
    colorFamily: 'silver',
    colorHex: '#94a3b8',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Super Silver Dust, Diamond Sparkle Glitter, White Silver Disco Powder',
    mf: 'Reflective Polymer / Titanium Dioxide Coated Flakes',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Prismatic Mirror Silver Sparkle Powder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust SD-02',
    grade: 'Decorative Cake Craft & Confectionery Accents',
    colorDesc: 'Lustrous Mirror-Like Silver Flakes',
    applicationSummary: 'Wedding Cakes, Royal Icing, Fondant Drapery, Holiday Confections & Nail Art',
    purity: 'High Specular Reflectance > 99%',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: silverDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'red-disco-dust',
    name: 'Red Color Disco Dust',
    colorFamily: 'red',
    colorHex: '#ef4444',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Ruby Red Disco Dust, Crimson Sparkle Powder, Valentine Red Cake Glitter',
    mf: 'Polyester Micro-Pigment Matrix',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Deep Crimson Sparkling Powder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust RD-03',
    grade: 'Confectionery Decorative & Craft Grade',
    colorDesc: 'Intense Ruby Red Glitter Dust',
    applicationSummary: 'Christmas Confections, Valentine Heart Cakes, Fondant Roses, Cupcake Toppings',
    purity: 'Non-Bleeding Vivid Sparkle Blend',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: redDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'blue-disco-dust',
    name: 'Blue Color Disco Dust',
    colorFamily: 'blue',
    colorHex: '#2563eb',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Sapphire Blue Disco Dust, Royal Blue Sparkle, Ocean Blue Glitter Powder',
    mf: 'Polyester Flakes with Blue Pigment Coating',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Sapphire Brilliant Sparkle Powder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust BD-04',
    grade: 'Cake Craft, Sugarcraft & Decorative Grade',
    colorDesc: 'Vibrant Sapphire Royal Blue Flakes',
    applicationSummary: 'Winter Wonderland Cakes, Mermaid Themes, Macaron Shells, Sugar Accents',
    purity: 'Fade-Resistant High Sheen',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: blueDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'pink-disco-dust',
    name: 'Pink Color Disco Dust',
    colorFamily: 'pink',
    colorHex: '#ec4899',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Princess Pink Disco Dust, Rose Quartz Glitter, Pastel Pink Cake Dust',
    mf: 'Micro-Fine Iridescent Polymer Flakes',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Delicate Radiant Pink Sparkle Powder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust PD-05',
    grade: 'Confectionery Decorative & Cosmetic Grade',
    colorDesc: 'Dazzling Magenta-Pink Shimmer Powder',
    applicationSummary: 'Baby Shower Pastries, Birthday Cupcakes, Strawberry Glazes, Sugar Bows',
    purity: 'Non-Toxic Iridescent Matrix',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: pinkDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'green-disco-dust',
    name: 'Green Color Disco Dust',
    colorFamily: 'green',
    colorHex: '#16a34a',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Emerald Green Disco Dust, Forest Sparkle Powder, Lime Glitter Dust',
    mf: 'Reflective Green Polymer Flakes',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Emerald Prismatic Shimmer Powder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust GD-06',
    grade: 'Sugarcraft, Fondant & Craft Grade',
    colorDesc: 'Vivid Emerald Green Reflective Flakes',
    applicationSummary: 'Holiday Wreath Cakes, Fondant Leaves, Mint Chocolates, Sugar Botanicals',
    purity: 'Even Particle Size Distribution',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: greenDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'yellow-disco-dust',
    name: 'Yellow Color Disco Dust',
    colorFamily: 'yellow',
    colorHex: '#eab308',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Canary Yellow Disco Dust, Sunshine Sparkle, Lemon Glitter Powder',
    mf: 'Polymer Matrix with Yellow Colorant',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Bright Sunshine Shimmering Flakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust YD-07',
    grade: 'Cake Decoration & Decorative Sugar Art',
    colorDesc: 'Luminous Lemon Yellow Glitter',
    applicationSummary: 'Sunflower Fondant, Spring Theme Desserts, Lemon Macaron Accents, Cake Toppers',
    purity: 'High Luster Light-Catching Powder',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: yellowDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'ivory-disco-dust',
    name: 'Ivory Color Disco Dust',
    colorFamily: 'ivory',
    colorHex: '#fef3c7',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Pearl Ivory Disco Dust, Champagne Sparkle, Cream Luster Glitter',
    mf: 'Mica & Titanium Dioxide Pearlescent Flakes',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Subtle Warm Pearl Sparkle Powder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust ID-08',
    grade: 'Gourmet Pastry & Wedding Cake Sugarcraft',
    colorDesc: 'Elegant Champagne Ivory Shimmer',
    applicationSummary: 'Traditional Wedding Cakes, Vintage Lace Fondant, Champagne Truffles, Pearls',
    purity: 'Ultra-Fine Smooth Pearlescence',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: ivoryDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'orange-disco-dust',
    name: 'Orange Color Disco Dust',
    colorFamily: 'orange',
    colorHex: '#f97316',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Sunset Orange Disco Dust, Tangerine Sparkle, Autumn Gold Glitter',
    mf: 'Reflective Orange Color Coated Flakes',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Fiery Tangerine Prismatic Sparkle',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust OD-09',
    grade: 'Confectionery Decorative & Craft Grade',
    colorDesc: 'Vibrant Sunset Orange Glitter Flakes',
    applicationSummary: 'Halloween Confections, Autumn Harvest Cakes, Citrus Fondant Embellishments',
    purity: 'Rich Pigment Density & Flash',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: orangeDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
  {
    id: 'violet-disco-dust',
    name: 'Violet Color Disco Dust',
    colorFamily: 'violet',
    colorHex: '#8b5cf6',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Pigment Blend',
    otherNames: 'Purple Disco Dust, Amethyst Sparkle, Lavender Glitter Dust',
    mf: 'Deep Violet Iridescent Polymer Flakes',
    einecsNo: 'Decorative Grade Formulation',
    femaNo: 'Decorative Grade Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Deep Amethyst Regal Violet Powder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Disco Dust VD-10',
    grade: 'Sugarcraft, Fondant Accents & Crafts',
    colorDesc: 'Royal Violet Sparkling Flakes',
    applicationSummary: 'Galaxy Theme Cakes, Sugar Orchids, Royalty Cupcakes, Festive Fondant Details',
    purity: 'Exceptional Sparkle & Color Purity',
    shelfLife: '3 Years',
    packagingDetails: '1 Kg, 5 Kg, 10 Kg, 25 Kg HDPE Containers',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY PLACE AWAY FROM DIRECT SUNLIGHT',
    image: violetDustImg,
    analysis: DISCO_DUST_ANALYSIS_SPECS,
  },
]
