// Master Dataset for Edible Lustre Dust with Authentic Export Specifications and Analytical Data
// Images imported directly from src/assets/img/edible-lustre-dust/

import goldLustreImg from '../assets/img/edible-lustre-dust/gold-lustre-dust.jpg'
import silverLustreImg from '../assets/img/edible-lustre-dust/silver-lustre-dust.jpg'
import redLustreImg from '../assets/img/edible-lustre-dust/red-lustre-dust.jpg'
import blueLustreImg from '../assets/img/edible-lustre-dust/blue-lustre-dust.jpg'
import pinkLustreImg from '../assets/img/edible-lustre-dust/pink-lustre-dust.jpg'
import greenLustreImg from '../assets/img/edible-lustre-dust/green-lustre-dust.jpg'
import yellowLustreImg from '../assets/img/edible-lustre-dust/yellow-lustre-dust.png'
import ivoryLustreImg from '../assets/img/edible-lustre-dust/ivory-lustre-dust.jpg'
import orangeLustreImg from '../assets/img/edible-lustre-dust/orange-lustre-dust.jpg'
import violetLustreImg from '../assets/img/edible-lustre-dust/voilet-lustre-dust.jpg'

export const EDIBLE_LUSTRE_ANALYSIS_SPECS = [
  { characteristic: 'Physical Appearance', requirement: 'Ultra-Fine Pearlescent Shimmering Powder' },
  { characteristic: 'Food Grade Standard', requirement: '100% Edible / Confectionery & Food Grade Compliant' },
  { characteristic: 'Composition / Base', requirement: 'Potassium Aluminum Silicate (E555 / Mica), TiO2 & Approved Food Colourants' },
  { characteristic: 'Particle Size Distribution (D50)', requirement: '10 – 60 Microns (Silky, Streak-Free Metallic Sheen)' },
  { characteristic: 'Loss on Drying (at 105°C)', requirement: '< 0.50% Max' },
  { characteristic: 'pH Value (10% Aqueous Slurry)', requirement: '6.00 – 8.00' },
  { characteristic: 'Heavy Metals (as Pb), Max.', requirement: '10.00 ppm' },
  { characteristic: 'Lead (Pb), Max.', requirement: '02.00 ppm' },
  { characteristic: 'Arsenic (As), Max.', requirement: '01.00 ppm' },
  { characteristic: 'Mercury (Hg), Max.', requirement: '0.50 ppm' },
  { characteristic: 'Total Aerobic Microbial Count', requirement: '< 100 CFU/g' },
  { characteristic: 'Yeast & Mould Count', requirement: '< 10 CFU/g (Pathogens Absent)' },
]

export const LUSTRE_APPLICATION_TECHNIQUES = [
  {
    technique: 'Dry Dusting',
    method: 'Apply directly with a soft dry confectionery brush onto dry surfaces.',
    bestFor: 'Fondant accents, gum paste flower petals, royal icing, macarons, dry chocolate shells.',
    tip: 'Gives a soft, pearlescent, translucent shimmer that highlights textured details.',
  },
  {
    technique: 'Wet Painting / Metallic Paint',
    method: 'Mix equal parts lustre dust with clear high-proof alcohol, lemon extract, or confectioners glaze.',
    bestFor: 'Hand-lettering, calligraphy, metallic drip cakes, borders, gold leaf effects.',
    tip: 'Alcohol evaporates rapidly leaving a concentrated, streak-free opaque metallic foil finish.',
  },
  {
    technique: 'Airbrushing',
    method: 'Dilute with high-proof food grade grain spirit or airbrush thinner (ratio 1:3).',
    bestFor: 'Full cake coverage, large chocolate showpieces, continuous uniform ombre gradients.',
    tip: 'Use a 0.3mm to 0.5mm nozzle to prevent mica flake clogging.',
  },
  {
    technique: 'Beverage & Cocktail Shimmer',
    method: 'Stir a pinch directly into transparent or sparkling alcoholic and non-alcoholic drinks.',
    bestFor: 'Cocktails, mocktails, sparkling ciders, celebration champagnes, festive syrups.',
    tip: 'Suspends in carbonated or viscous liquids to create dynamic swirling metallic vortex effects.',
  },
]

export const EDIBLE_LUSTRE_PRODUCTS = [
  {
    id: 'golden-lustre',
    name: 'Golden Colour Edible Lustre Dust',
    image: goldLustreImg,
    category: 'metallic',
    groupName: 'Metallic & Warm',
    shadeColor: '#d97706',
    ciName: 'CI 77019 + CI 77891 + CI 77491',
    eNumber: 'E555, E171, E172',
    otherNames: 'Edible Gold Dust, Confectionery Gold Lustre, Shimmering Cake Gold',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7 / 1309-37-1',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Luxurious brilliant warm gold metallic lustre designed for premium wedding cake decoration, artisan chocolates, dry dusting on fondant flowers, and edible gold paint calligraphy.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'silver-lustre',
    name: 'Silver Colour Edible Lustre Dust',
    image: silverLustreImg,
    category: 'metallic',
    groupName: 'Metallic & Warm',
    shadeColor: '#94a3b8',
    ciName: 'CI 77019 + CI 77891',
    eNumber: 'E555, E171',
    otherNames: 'Edible Silver Dust, Silver Pearl Powder, Confectionery Silver Sheen',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Pristine mirror-bright silver metallic powder producing crisp platinum and chrome highlights on wedding cakes, sugar figurines, holiday macarons, and sparkling celebration cocktails.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'red-lustre',
    name: 'Red Colour Edible Lustre Dust',
    image: redLustreImg,
    category: 'vibrant',
    groupName: 'Vibrant Shades',
    shadeColor: '#dc2626',
    ciName: 'CI 77019 + CI 77891 + CI 16035',
    eNumber: 'E555, E171, E129',
    otherNames: 'Edible Ruby Red Dust, Crimson Lustre Powder, Metallic Red Dust',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7 / 25956-17-6',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Vivid, deep ruby metallic red finish engineered for Valentine desserts, red velvet cake borders, sugar rose petals, Christmas confectionery, and glazes.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'blue-lustre',
    name: 'Blue Colour Edible Lustre Dust',
    image: blueLustreImg,
    category: 'cool',
    groupName: 'Cool Tones',
    shadeColor: '#2563eb',
    ciName: 'CI 77019 + CI 77891 + CI 42090',
    eNumber: 'E555, E171, E133',
    otherNames: 'Edible Sapphire Blue Dust, Ocean Shimmer Powder, Royal Blue Lustre',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7 / 3844-45-9',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Dazzling royal sapphire blue pearlescent powder ideal for nautical theme cakes, celestial dessert styling, frozen-themed confectioneries, and signature blue cocktails.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'pink-lustre',
    name: 'Pink Colour Edible Lustre Dust',
    image: pinkLustreImg,
    category: 'vibrant',
    groupName: 'Vibrant Shades',
    shadeColor: '#db2777',
    ciName: 'CI 77019 + CI 77891 + CI 45430 / CI 16035',
    eNumber: 'E555, E171, E127 / E129',
    otherNames: 'Edible Rose Gold / Pink Dust, Confectionery Pink Shimmer, Rose Quartz Lustre',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Delicate, luminous rose pink pearlescent shimmer for baby shower confections, floral sugar craft, pink champagne flutes, macarons, and artisanal cake pops.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'green-lustre',
    name: 'Green Colour Edible Lustre Dust',
    image: greenLustreImg,
    category: 'cool',
    groupName: 'Cool Tones',
    shadeColor: '#16a34a',
    ciName: 'CI 77019 + CI 77891 + CI 19140 + CI 42090',
    eNumber: 'E555, E171, E102 + E133',
    otherNames: 'Edible Emerald Green Dust, Botanical Shimmer Powder, Lime Lustre Dust',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Rich emerald botanical green pearl shimmer for lifelike foliage dusting, sugar leaves, holiday wreath pastries, mint macarons, and exotic cocktail garnishes.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'yellow-lustre',
    name: 'Yellow Colour Edible Lustre Dust',
    image: yellowLustreImg,
    category: 'vibrant',
    groupName: 'Vibrant Shades',
    shadeColor: '#eab308',
    ciName: 'CI 77019 + CI 77891 + CI 19140',
    eNumber: 'E555, E171, E102',
    otherNames: 'Edible Canary Yellow Dust, Lemon Shimmer Powder, Golden Yellow Lustre',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7 / 1934-21-0',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Radiant sun-kissed canary yellow pearlescent powder delivering bright luminous accents on citrus desserts, summer confectionery, and sunny cake florals.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'ivory-lustre',
    name: 'Ivory Colour Edible Lustre Dust',
    image: ivoryLustreImg,
    category: 'metallic',
    groupName: 'Metallic & Warm',
    shadeColor: '#d6d3d1',
    ciName: 'CI 77019 + CI 77891 + CI 77492',
    eNumber: 'E555, E171, E172',
    otherNames: 'Edible Champagne Ivory Dust, Cream Pearl Dust, Soft Pearl Shimmer',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7 / 51274-00-1',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Subtle champagne ivory pearl powder providing refined, elegant undertones for vintage bridal cakes, cream pearls, white chocolate bonbons, and delicate lace work.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'orange-lustre',
    name: 'Orange Colour Edible Lustre Dust',
    image: orangeLustreImg,
    category: 'vibrant',
    groupName: 'Vibrant Shades',
    shadeColor: '#ea580c',
    ciName: 'CI 77019 + CI 77891 + CI 15985',
    eNumber: 'E555, E171, E110',
    otherNames: 'Edible Sunset Orange Dust, Copper Orange Lustre, Amber Shimmer Dust',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7 / 2783-94-0',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Fiery sunset orange pearlescent dust offering intense metallic warmth on autumn cakes, Halloween confectionery, tropical fruit pralines, and cocktail rimming.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
  {
    id: 'violet-lustre',
    name: 'Violet Colour Edible Lustre Dust',
    image: violetLustreImg,
    category: 'cool',
    groupName: 'Cool Tones',
    shadeColor: '#7c3aed',
    ciName: 'CI 77019 + CI 77891 + CI 42090 + CI 45430',
    eNumber: 'E555, E171, E133 + E127',
    otherNames: 'Edible Amethyst Violet Dust, Purple Shimmer Powder, Royal Violet Lustre',
    types: '100% Food Grade Edible Powder',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    packaging: '100g, 500g, 1 Kg tamper-evident food-grade jars; 25 Kg fibre drums',
    shelfLife: '36 Months from Manufacturing Date',
    casNo: '12001-26-2 / 13463-67-7',
    storage: 'Store in airtight containers in a cool, dry place away from direct moisture, sunlight, and volatile aromas.',
    applicationSummary:
      'Mystical imperial amethyst violet shimmer dust creating spellbinding luster on galaxy cakes, gourmet chocolate truffles, fantasy pastries, and specialty beverages.',
    analysis: EDIBLE_LUSTRE_ANALYSIS_SPECS,
  },
]
