// Master Dataset for Emulsion Flavours with Authentic Specifications and Analytical Data
// Images imported directly from src/assets/img/ef/

import mangoEmulsionImg from '../assets/img/ef/Mango-Emulsion.jpg'
import concentratedOrangeImg from '../assets/img/ef/Concentrated-orange-flavor.PNG'
import strawberryConcentratedImg from '../assets/img/ef/Strawberry-Concentrated-Liquid-Flavor.jpg'
import strawberryEmulsionImg from '../assets/img/ef/strawberry-emulsion-flavor.jpg'
import blackCurrantDrinkImg from '../assets/img/ef/Black-Currant-Drink-Flavor-Juice-Flavor-Black.jpg'
import redGrapesEmulsionImg from '../assets/img/ef/Red-Grapes-Flavour-best-quality-grape-emulsion.jpg'
import pineappleEmulsionImg from '../assets/img/ef/Pineapple-emulsion-flavour.jpg'
import concentratedMangoImg from '../assets/img/ef/Concentrated-Mango-Flavor-For-Liquid.jpg'
import wholesaleGrapeImg from '../assets/img/ef/Wholesale-grape-emulsion-flavor-for-whisky.jpg'
import blackCurrantEmulsionImg from '../assets/img/ef/good-quality-black-currant-emulsion-flavor.jpg'
import grapeJuiceEmulsionImg from '../assets/img/ef/India-supplier-grape-emulsion-flavor-Juice-emulsion.jpg'
import colaEmulsionImg from '../assets/img/ef/Cola-emulsion-flavor-cola-essence-flavor-cola.jpg'
import superPineappleImg from '../assets/img/ef/Super-concentrate-pineapple-emulsion-flavor-for-food.jpg'
import lemonLimeImg from '../assets/img/ef/Lemon-lime-flavouring-food-flavor-liquid.jpg'
import concentratedAppleImg from '../assets/img/ef/Concentrated-liquid-apple-flavor.jpg'
import mintEmulsionImg from '../assets/img/ef/Mint-Flavor-for-food-beverage.jpg'
import raspberryConcentratedImg from '../assets/img/ef/Raspberry-Concentrated-Liquid-Flavor.jpg'
import honeyEmulsionImg from '../assets/img/ef/Honey-flavor-for-dairy-products.jpg'
import almondEmulsionImg from '../assets/img/ef/Almond-liquid-food-flavoring.jpg'

export const EMULSION_ANALYSIS_SPECS = [
  { characteristic: 'Physical Form & Appearance', requirement: 'Homogeneous, Slightly Viscous Micro-Emulsion' },
  { characteristic: 'Specific Gravity (at 20°C / 30°C)', requirement: '1.020 – 1.120 g/cm³' },
  { characteristic: 'pH Value (Direct at 20°C)', requirement: '3.00 – 4.50' },
  { characteristic: 'Clouding & Emulsion Stability (180 Days)', requirement: 'Stable, No Ringing / Separation in Beverage' },
  { characteristic: 'Flash Point (Closed Cup)', requirement: '> 90°C' },
  { characteristic: 'Total Heavy Metals (as Pb), Max.', requirement: '10.00 ppm' },
  { characteristic: 'Lead (Pb), Max.', requirement: '02.00 ppm' },
  { characteristic: 'Arsenic (As), Max.', requirement: '01.00 ppm' },
  { characteristic: 'Total Aerobic Microbial Count', requirement: '< 500 CFU/g' },
  { characteristic: 'Yeast & Mould Count', requirement: '< 50 CFU/g (Pathogens Absent)' },
]

export const SPECIALTY_EMULSION_PROFILES = [
  'Blue Berry Emulsion', 'Butterscotch Emulsion', 'Cola Clouding Base', 'Garden Mist (N)',
  'Gold Mist (N)', 'Kala Khatta Special', 'Khus Clouding Flavour', 'Lemon Lime Emulsion',
  'Lemon Cloudy', 'Mango Green Special', 'Alphonso Mango Emulsion', 'Orange Fanta Cloud',
  'Pineapple Super', 'Sweet Orange Emulsion', 'Pista Kulfi Emulsion', 'Raspberry Cordial',
  'Red Rose Emulsion', 'Silver Mist Neutral Cloud', 'Strawberry Cream Emulsion'
]

export const EMULSION_FLAVOURS = [
  {
    id: 'mango-emulsion',
    name: 'Mango Emulsion',
    colorFamily: 'fruity',
    colorHex: '#ea580c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Alphonso Mango Beverage Emulsion',
    mf: 'Essential Oils, Clouding Agents & Color Blend',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Clouding Beverage Emulsion, Flavoring & Coloring Agent',
    brandName: 'Exim India Corporation',
    modelNumber: 'Mango Emulsion ME-01',
    grade: 'Food Grade, Beverage Grade (ISO9001:2015 & FSSAI)',
    colorDesc: 'Vibrant Orange Viscous Liquid',
    applicationSummary: 'Mango RTD Drinks, Fruit Squashes, Crushes, Ice Golas & Nectars',
    purity: 'High Density Clouding Formulation',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: mangoEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'concentrated-orange',
    name: 'Concentrated Orange Flavour',
    colorFamily: 'citrus',
    colorHex: '#f97316',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Orange Clouding Beverage Emulsion',
    mf: 'Cold-Pressed Orange Terpenes & Emulsifiers',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Orange Juice Clouding Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Orange Emulsion OE-02',
    grade: 'Food Grade, Beverage Grade',
    colorDesc: 'Bright Orange Milky Emulsion',
    applicationSummary: 'Carbonated Orange Sodas, Still Beverages, Syrups & Bakery Fillings',
    purity: 'High Clouding Stability, No Ringing',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: concentratedOrangeImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'strawberry-concentrated',
    name: 'Strawberry Concentrated Liquid Flavour',
    colorFamily: 'berries',
    colorHex: '#e11d48',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Ripe Strawberry Concentrated Aroma',
    mf: 'Natural & Nature-Identical Esters',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Concentrated Liquid Flavour Compound',
    brandName: 'Exim India Corporation',
    modelNumber: 'Strawberry SCLF-03',
    grade: 'Food Grade, Dairy & Beverage Grade',
    colorDesc: 'Clear Pinkish-Red Liquid',
    applicationSummary: 'Milk Drinks, Ice Creams, Toffees, Syrups & Fruit Crushes',
    purity: 'High Impact Aroma Concentration',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: strawberryConcentratedImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'strawberry-emulsion',
    name: 'Strawberry Emulsion Flavour',
    colorFamily: 'berries',
    colorHex: '#be123c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Creamy Strawberry Clouding Emulsion',
    mf: 'Flavoring Emulsion with Natural Colorants',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Clouding Beverage & Dairy Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Strawberry SEF-04',
    grade: 'Food Grade, Dairy & RTD Beverage Grade',
    colorDesc: 'Opaque Reddish-Pink Liquid Emulsion',
    applicationSummary: 'Flavored Milk, Milkshakes, Yogurt Smoothies & RTD Beverage Bottles',
    purity: 'Micro-Droplet Emulsion Formulation',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: strawberryEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'black-currant-drink',
    name: 'Black Currant Drink Flavour',
    colorFamily: 'berries',
    colorHex: '#4c1d95',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Juice Flavour Blackcurrant Beverage Concentrate',
    mf: 'Natural Blackcurrant Aroma Fractions',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Beverage Flavouring Compound',
    brandName: 'Exim India Corporation',
    modelNumber: 'Blackcurrant BCDF-05',
    grade: 'Food Grade, Soft Drink Grade',
    colorDesc: 'Deep Violet-Red Clear Liquid',
    applicationSummary: 'Carbonated Fruit Sodas, Cordials, Fruit Slushes & Candies',
    purity: 'High Concentration Essence',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: blackCurrantDrinkImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'red-grapes-emulsion',
    name: 'Red Grapes Flavour Best Quality Grape Emulsion',
    colorFamily: 'fruity',
    colorHex: '#701a75',
    moq: '100 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Red Concord Grape Juice Emulsion',
    mf: 'Natural Grape Concentrates & Clouding Agents',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Clouding Grape Beverage Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Red Grape RGE-06',
    grade: 'Food Grade, Beverage & Wine Mocktail Grade',
    colorDesc: 'Rich Purple-Red Opaque Liquid',
    applicationSummary: 'Grape Juices, Mocktails, Popsicles, Fruit Jellies & Syrups',
    purity: 'Authentic Concord Grape Profile',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: redGrapesEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'pineapple-emulsion',
    name: 'Pineapple Emulsion Flavour',
    colorFamily: 'fruity',
    colorHex: '#ca8a04',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Tropical Pineapple Clouding Emulsion',
    mf: 'Allyl Caproate, Fruit Esters & Emulsifiers',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Clouding Tropical Juice Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pineapple PE-07',
    grade: 'Food Grade, Beverage Grade',
    colorDesc: 'Pale Yellow Clouding Liquid',
    applicationSummary: 'Pineapple Crushes, RTD Juices, Bakery Creams & Cocktails',
    purity: 'Stable Clouding Technology',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: pineappleEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'concentrated-mango',
    name: 'Concentrated Mango Flavour For Liquid',
    colorFamily: 'fruity',
    colorHex: '#ea580c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'High Strength Alphonso Mango Liquid Essence',
    mf: 'Concentrated Fruit Aromas & Stabilizers',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Concentrated Beverage & Dairy Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Mango CMFL-08',
    grade: 'Food Grade, High Brix Ready',
    colorDesc: 'Golden Orange Concentrated Liquid',
    applicationSummary: 'Squashes, Fruit Syrups, Shakes, Ice Cream Premixes & Bakery',
    purity: 'Super Concentrated Formulation',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: concentratedMangoImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'grape-emulsion-beverage',
    name: 'Wholesale Grape Emulsion Flavour for Whisky',
    colorFamily: 'beverage-specialty',
    colorHex: '#581c87',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Oak & Grape Beverage Enhancer Emulsion',
    mf: 'Complex Aromatic Compounds & Essences',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Alcoholic & Non-Alcoholic Beverage Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Grape Emulsion GEW-09',
    grade: 'Food Grade, Distillery & Beverage Grade',
    colorDesc: 'Dark Purple-Amber Liquid',
    applicationSummary: 'Flavored Spirits, Mocktails, Craft Tonics & Specialty Beverages',
    purity: 'High Alcohol Solubility & Stability',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: wholesaleGrapeImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'black-currant-emulsion',
    name: 'Good Quality Black Currant Emulsion Flavour',
    colorFamily: 'berries',
    colorHex: '#3b0764',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Premium Blackcurrant Clouding Emulsion',
    mf: 'Fruit Extracts, Clouding Agents & Color',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Clouding Beverage Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Blackcurrant BCE-10',
    grade: 'Food Grade, Soft Drink & Cordial Grade',
    colorDesc: 'Dark Purple Viscous Emulsion',
    applicationSummary: 'Ready-to-Drink Juices, Mocktails, Syrups, Slushies & Popsicles',
    purity: 'Zero Separation Clouding Base',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: blackCurrantEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'grape-juice-emulsion',
    name: 'India Supplier Grape Emulsion Flavour Juice Emulsion',
    colorFamily: 'fruity',
    colorHex: '#6b21a8',
    moq: '100 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Export-Grade Grape Juice Emulsion',
    mf: 'Natural Grape Fractions & Stabilizers',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'High Output Beverage Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Grape Juice GJE-11',
    grade: 'Food Grade, Export Quality',
    colorDesc: 'Purple-Red Cloudy Liquid',
    applicationSummary: 'Industrial Bottling Plants, Juices, Sodas & Flavor Concentrates',
    purity: 'High Dilution Ratio (1:1000)',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: grapeJuiceEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'cola-emulsion',
    name: 'Cola Emulsion Flavour Cola Essence Flavour Cola',
    colorFamily: 'beverage-specialty',
    colorHex: '#382214',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Classic Cola Beverage Emulsion & Compound',
    mf: 'Citrus Oils, Spices, Caramel & Emulsifiers',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cola Soft Drink Concentrated Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Cola Emulsion CE-12',
    grade: 'Food Grade, Carbonated Beverage Grade',
    colorDesc: 'Dark Caramel-Brown Viscous Emulsion',
    applicationSummary: 'Carbonated Cola Drinks, Fountain Sodas, Gummy Candies & Lozenges',
    purity: 'Authentic 7-Oil Botanical Cola Profile',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: colaEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'super-pineapple',
    name: 'Super Concentrate Pineapple Emulsion Flavour for Food',
    colorFamily: 'fruity',
    colorHex: '#eab308',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Super-Strength Ripe Pineapple Emulsion',
    mf: 'Concentrated Esters & Food Hydrocolloids',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'High Density Emulsion Concentrate',
    brandName: 'Exim India Corporation',
    modelNumber: 'Super Pineapple SPE-13',
    grade: 'Food Grade, Bakery & Confectionery Grade',
    colorDesc: 'Opaque Golden Yellow Liquid',
    applicationSummary: 'Bakery Pastries, Cakes, Biscuits, Syrups, Milk Shakes & Candies',
    purity: 'Heat-Resistant Super Concentrate',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: superPineappleImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'lemon-lime-emulsion',
    name: 'Lemon Lime Flavouring Food Flavour Liquid',
    colorFamily: 'citrus',
    colorHex: '#84cc16',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Citrus Cloudy Lemon-Lime Beverage Compound',
    mf: 'Distilled Lime & Lemon Essential Oils',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Citrus Clouding Liquid Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lemon Lime LLE-14',
    grade: 'Food Grade, Beverage Grade',
    colorDesc: 'Cloudy Pale Greenish-Yellow Liquid',
    applicationSummary: 'Clear & Cloudy Lemonades, Sprite-Type Sodas, Cocktails & Mints',
    purity: 'Cold-Pressed Distilled Citrus Extracts',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: lemonLimeImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'concentrated-apple',
    name: 'Concentrated Liquid Apple Flavour',
    colorFamily: 'fruity',
    colorHex: '#65a30d',
    moq: '100 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Crisp Green Apple Concentrated Aroma',
    mf: 'Natural Apple Extracts & Aromatic Esters',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Concentrated Liquid Flavour Compound',
    brandName: 'Exim India Corporation',
    modelNumber: 'Apple CLA-15',
    grade: 'Food Grade, Juice & Confectionery Grade',
    colorDesc: 'Clear to Slightly Opalescent Liquid',
    applicationSummary: 'Fruit Ciders, Sparkling Waters, Chewing Gums, Hard Candies & Nectars',
    purity: 'Crisp Granny Smith Profile',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: concentratedAppleImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'mint-emulsion',
    name: 'Mint Flavour for Food Beverage',
    colorFamily: 'herbal-cooling',
    colorHex: '#059669',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Cooling Mint Clouding & Beverage Flavour',
    mf: 'Mentha Piperita Essential Oil & Stabilizers',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cooling Beverage & Confectionery Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Mint MFB-16',
    grade: 'Food Grade, Beverage & Pharma Grade',
    colorDesc: 'Translucent Pale Emerald Liquid',
    applicationSummary: 'Mojito Bases, Chuskis, Ayurvedic Tonics, Mouth Fresheners & Gums',
    purity: 'High Menthol Concentration',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: mintEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'raspberry-concentrated',
    name: 'Raspberry Concentrated Liquid Flavour',
    colorFamily: 'berries',
    colorHex: '#be123c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Wild Red Raspberry Liquid Concentrate',
    mf: 'Natural Raspberry Aroma & Food Acids',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Concentrated Liquid Flavour Compound',
    brandName: 'Exim India Corporation',
    modelNumber: 'Raspberry RCLF-17',
    grade: 'Food Grade, Confectionery Grade',
    colorDesc: 'Deep Ruby Red Transparent Liquid',
    applicationSummary: 'Jellies, Confectionery, Cake Icings, Ice Creams & Syrups',
    purity: 'Rich European Wild Raspberry Notes',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: raspberryConcentratedImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'honey-emulsion',
    name: 'Honey Flavour for Dairy Products',
    colorFamily: 'sweet-dairy',
    colorHex: '#d97706',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Floral Honey Emulsion for Dairy & Milk',
    mf: 'Honey Extracts, Floral Notes & Emulsifiers',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Dairy-Compatible Flavour Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Honey HFD-18',
    grade: 'Food Grade, Dairy & Breakfast Cereal Grade',
    colorDesc: 'Golden Amber Milky Emulsion',
    applicationSummary: 'Honey Yogurts, Flavored Milk, Ice Creams, Toffees & Cereals',
    purity: 'Readily Dispersible in Dairy Bases',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: honeyEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
  {
    id: 'almond-emulsion',
    name: 'Almond Liquid Food flavouring',
    colorFamily: 'sweet-dairy',
    colorHex: '#b45309',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Formulation',
    otherNames: 'Sweet Badam / Almond Culinary Emulsion',
    mf: 'Benzaldehyde, Nut Essential Oils & Emulsifiers',
    einecsNo: 'Flavour Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Culinary Nut Food Emulsion',
    brandName: 'Exim India Corporation',
    modelNumber: 'Almond ALFF-19',
    grade: 'Food Grade, Traditional Sweets & Dairy Grade',
    colorDesc: 'Milky White to Pale Cream Emulsion',
    applicationSummary: 'Badam Milk, Kulfi, Traditional Sweets, Pastries & Marzipan',
    purity: 'Authentic Indian Badam Aroma',
    shelfLife: '2 Years',
    packagingDetails: '10/25/50 Kgs Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE FROM HUMIDITY, EXCESSIVE HEAT & DIRECT SUNLIGHT',
    image: almondEmulsionImg,
    analysis: EMULSION_ANALYSIS_SPECS,
  },
]
