// Master Dataset for Food Additives & Ingredients with Authentic Specifications and Analytical Data
// Images imported directly from src/assets/img/fa/

import citricAcidImg from '../assets/img/fa/Citric-Acid.jpg'
import soyaLecithinPowderImg from '../assets/img/fa/soya-lecithin-powder.jpeg'
import soyaLecithinLiquidImg from '../assets/img/fa/soya_lecithin.jpg'
import gelatinImg from '../assets/img/fa/gelatin.jpg'
import sucroseImg from '../assets/img/fa/sucrose.jpg'
import cornstarchImg from '../assets/img/fa/cornstrach.jpg'
import saffronImg from '../assets/img/fa/saffron.jpg'

export const GENERAL_ADDITIVES_QUALITY_SPECS = [
  { characteristic: 'Heavy Metals (as Pb), Max.', requirement: '10.00 ppm' },
  { characteristic: 'Arsenic (As), Max.', requirement: '01.00 ppm' },
  { characteristic: 'Lead (Pb), Max.', requirement: '01.00 ppm' },
  { characteristic: 'Mercury (Hg), Max.', requirement: '0.10 ppm' },
  { characteristic: 'Total Aerobic Microbial Count', requirement: '< 1000 CFU/g' },
  { characteristic: 'Yeast & Mould Count', requirement: '< 100 CFU/g' },
  { characteristic: 'E. Coli & Salmonella', requirement: 'Absent in 25g' },
  { characteristic: 'Food Grade Standard', requirement: 'Complies with FSSAI, US-FDA 21 CFR & FCC Monograph' },
]

export const EXTENDED_FOOD_ADDITIVES = [
  { name: 'Ascorbic Acid (Vitamin C)', category: 'Antioxidant & Preservative', standard: 'FCC / USP / E300', form: 'White Crystalline Powder' },
  { name: 'Sodium Benzoate', category: 'Antimicrobial Preservative', standard: 'FCC / E211', form: 'Dense White Granules / Flakes' },
  { name: 'Potassium Sorbate', category: 'Fungistatic Preservative', standard: 'FCC / E202', form: 'White Granular Spheres' },
  { name: 'Calcium Propionate', category: 'Bakery Anti-Mould Agent', standard: 'FCC / E282', form: 'Fine White Powder' },
  { name: 'Xanthan Gum (80 / 200 Mesh)', category: 'Hydrocolloid & Stabilizer', standard: 'Food & Pharma Grade / E415', form: 'Creamy White Powder' },
  { name: 'Guar Gum (Food Grade)', category: 'Natural Thickening Agent', standard: 'FSSAI / E412', form: 'Pale White-Yellow Powder' },
  { name: 'Sodium Acid Pyrophosphate (SAPP)', category: 'Leavening & Buffering Agent', standard: 'Food Grade / E450(i)', form: 'White Crystalline Powder' },
  { name: 'Mono & Diglycerides (GMS)', category: 'Food Emulsifier', standard: 'FCC / E471', form: 'Ivory Flakes / Powder' },
]

export const FOOD_ADDITIVES = [
  {
    id: 'citric-acid',
    name: 'Citric Acid',
    colorFamily: 'acidulant',
    colorHex: '#0284c7',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '77-92-9 (Anhydrous) / 5949-29-1 (Monohydrate)',
    otherNames: '2-Hydroxypropane-1,2,3-tricarboxylic acid, E330, Acidum Citricum',
    mf: 'C6H8O7 / C6H8O7·H2O',
    einecsNo: '201-069-1',
    femaNo: '2306',
    placeOfOrigin: 'Gujarat / Maharashtra, India',
    types: 'Acidulant, Natural Preservative, Flavor Enhancer & Chelating Agent',
    brandName: 'Exim India Corporation',
    modelNumber: 'Food Additive CA-01',
    grade: 'Food Grade (FCC / USP / BP / IP / E330)',
    colorDesc: 'White Translucent Crystals or Granular Powder',
    applicationSummary: 'Carbonated Beverages, Jams, Jellies, Confectionery, Canned Foods, Dairy, Effervescent Products',
    purity: '99.5% – 100.5% (High Assay)',
    shelfLife: '3 Years',
    packagingDetails: '25 Kg Multi-wall Kraft Paper Bags with inner poly liner / 500 Kg Jumbo Bags',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A COOL, DRY, WELL-VENTILATED WAREHOUSE AWAY FROM EXCESSIVE HUMIDITY',
    image: citricAcidImg,
    analysis: [
      { characteristic: 'Assay (Dry Basis)', requirement: '99.50% – 100.50%' },
      { characteristic: 'Moisture (Anhydrous / Monohydrate)', requirement: '≤ 0.50% / 7.50% – 8.80%' },
      { characteristic: 'Residue on Ignition', requirement: '≤ 0.05%' },
      { characteristic: 'Sulphate (SO4)', requirement: '≤ 150 ppm' },
      { characteristic: 'Oxalate (C2O4)', requirement: '≤ 100 ppm' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '≤ 5.00 ppm' },
      { characteristic: 'Lead (Pb)', requirement: '≤ 0.50 ppm' },
      { characteristic: 'Arsenic (As)', requirement: '≤ 1.00 ppm' },
    ],
  },
  {
    id: 'soya-lecithin-powder',
    name: 'Soya Lecithin Powder',
    colorFamily: 'emulsifier',
    colorHex: '#eab308',
    moq: '50 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '8002-43-5',
    otherNames: 'De-oiled Soya Lecithin, E322, Phosphatidylcholine Complex',
    mf: 'Complex Mixture of Phospholipids & Glycolipids',
    einecsNo: '232-307-2',
    femaNo: 'GRAS Approved (E322)',
    placeOfOrigin: 'Madhya Pradesh / Maharashtra, India',
    types: 'Natural Emulsifier, Stabilizer, Wetting Agent, Dispersion Aid',
    brandName: 'Exim India Corporation',
    modelNumber: 'Food Additive SLP-02',
    grade: 'Non-GMO Food Grade & Bakery Grade',
    colorDesc: 'Light Cream to Light Tan Free-Flowing Powder',
    applicationSummary: 'Bakery Premixes, Chocolate Refining, Instant Drink Powders, Nutritional Premixes, Margarine',
    purity: 'Acetone Insoluble Matter ≥ 97.0%',
    shelfLife: '2 Years',
    packagingDetails: '20/25 Kg Corrugated Cartons with food-grade inner poly liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A DRY, COOL PLACE BELOW 25°C AWAY FROM DIRECT HEAT & SUNLIGHT',
    image: soyaLecithinPowderImg,
    analysis: [
      { characteristic: 'Acetone Insoluble Matter (Phospholipids)', requirement: '≥ 97.00%' },
      { characteristic: 'Moisture (Karl Fischer)', requirement: '≤ 1.50%' },
      { characteristic: 'Hexane Insoluble Matter', requirement: '≤ 0.30%' },
      { characteristic: 'Acid Value', requirement: '≤ 35.00 mg KOH/g' },
      { characteristic: 'Peroxide Value', requirement: '≤ 3.00 meq/kg' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '≤ 10.00 ppm' },
      { characteristic: 'Arsenic (As)', requirement: '≤ 1.00 ppm' },
      { characteristic: 'Total Plate Count', requirement: '< 1000 CFU/g' },
    ],
  },
  {
    id: 'soya-lecithin-liquid',
    name: 'Soya Lecithin Liquid',
    colorFamily: 'emulsifier',
    colorHex: '#b45309',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '8002-43-5',
    otherNames: 'Standardized Fluid Lecithin, Native Soya Lecithin, E322',
    mf: 'Phospholipids, Triglycerides & Glycolipids',
    einecsNo: '232-307-2',
    femaNo: 'GRAS Approved (E322)',
    placeOfOrigin: 'Madhya Pradesh / Maharashtra, India',
    types: 'Natural Food Emulsifier, Viscosity Reducer & Anti-Staling Agent',
    brandName: 'Exim India Corporation',
    modelNumber: 'Food Additive SLL-03',
    grade: 'Non-GMO Food Grade & Feed Grade',
    colorDesc: 'Clear Amber to Dark Brown Viscous Fluid',
    applicationSummary: 'Chocolates & Confectionery, Margarines & Spreads, Cones & Wafers, Instant Powders, Release Agent',
    purity: 'Acetone Insoluble Matter ≥ 62.0%',
    shelfLife: '2 Years',
    packagingDetails: '200 Kg Epoxy-Coated Steel / HDPE Drums, 1000 Kg IBC Totes',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE AT 15°C TO 30°C IN SEALED DRUMS; PROTECT FROM FREEZING & MOISTURE',
    image: soyaLecithinLiquidImg,
    analysis: [
      { characteristic: 'Acetone Insoluble Matter', requirement: '≥ 62.00%' },
      { characteristic: 'Moisture', requirement: '≤ 1.00%' },
      { characteristic: 'Hexane Insoluble Matter', requirement: '≤ 0.05%' },
      { characteristic: 'Acid Value', requirement: '≤ 30.00 mg KOH/g' },
      { characteristic: 'Viscosity (at 25°C)', requirement: '80 – 120 Poise' },
      { characteristic: 'Color (Gardner)', requirement: '≤ 14' },
      { characteristic: 'Peroxide Value', requirement: '≤ 5.00 meq/kg' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '≤ 10.00 ppm' },
    ],
  },
  {
    id: 'gelatin',
    name: 'Gelatin',
    colorFamily: 'texturizer',
    colorHex: '#15803d',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '9000-70-8',
    otherNames: 'Edible Bovine Gelatin, Gelatine Powder, E441, Collagen Protein',
    mf: 'High Molecular Weight Protein Polymer',
    einecsNo: '232-554-6',
    femaNo: 'GRAS Approved',
    placeOfOrigin: 'Maharashtra / Gujarat, India',
    types: 'Gelling Agent, Stabilizer, Thickener, Texturizer, Whipping Agent',
    brandName: 'Exim India Corporation',
    modelNumber: 'Food Additive GEL-04',
    grade: 'Food & Pharmaceutical Grade (Halal & Kosher Certified)',
    colorDesc: 'Light Yellow to Pale Amber Granular Powder',
    applicationSummary: 'Gummy Candies, Marshmallows, Dessert Jellies, Dairy Yogurts, Wine Fining, Hard/Soft Gelatin Capsules',
    purity: 'Bloom Strength 160 – 260 Bloom g',
    shelfLife: '3 Years',
    packagingDetails: '25 Kg Kraft Paper Bags with inner food-grade poly liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE IN AN AIRTIGHT CONTAINER IN A DRY, AMBIENT ENVIRONMENT',
    image: gelatinImg,
    analysis: [
      { characteristic: 'Bloom Strength (6.67% at 10°C)', requirement: '160 – 260 Bloom g' },
      { characteristic: 'Viscosity (6.67% at 60°C)', requirement: '3.50 – 5.50 mPa·s' },
      { characteristic: 'Moisture', requirement: '≤ 14.00%' },
      { characteristic: 'Total Ash', requirement: '≤ 2.00%' },
      { characteristic: 'pH Value (1% Solution at 55°C)', requirement: '4.50 – 6.50' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '≤ 10.00 ppm' },
      { characteristic: 'Arsenic (As)', requirement: '≤ 1.00 ppm' },
      { characteristic: 'E. Coli & Salmonella', requirement: 'Absent in 25g' },
    ],
  },
  {
    id: 'sucrose',
    name: 'Sucrose',
    colorFamily: 'sweetener',
    colorHex: '#0d9488',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '57-50-1',
    otherNames: 'Pure Refined Cane Sugar, D-Sucrose, Saccharose, Pharmaceutical Sugar',
    mf: 'C12H22O11',
    einecsNo: '200-334-9',
    femaNo: 'GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Natural Sweetener, Bulking Agent, Viscosity Agent, Tablet Binder',
    brandName: 'Exim India Corporation',
    modelNumber: 'Food Additive SUC-05',
    grade: 'Pharma / Food Grade (IP / BP / USP / FCC / ICUMSA 45)',
    colorDesc: 'White Odorless Crystalline Powder / Granules',
    applicationSummary: 'Pharmaceutical Syrups, Confectionery, Carbonated Beverages, Bakery Fillings, Condensed Milk',
    purity: 'Polarization ≥ 99.80°Z (Ultra Refined)',
    shelfLife: '3 Years',
    packagingDetails: '25 Kg / 50 Kg Poly-lined HDPE Bags',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A TIGHTLY CLOSED CONTAINER IN A DRY PLACE AT ROOM TEMPERATURE',
    image: sucroseImg,
    analysis: [
      { characteristic: 'Polarization', requirement: '≥ 99.80°Z' },
      { characteristic: 'Moisture / Loss on Drying', requirement: '≤ 0.04%' },
      { characteristic: 'Conductivity Ash', requirement: '≤ 0.04%' },
      { characteristic: 'Color (ICUMSA)', requirement: '< 45 IU' },
      { characteristic: 'Reducing Sugars', requirement: '≤ 0.04%' },
      { characteristic: 'Sulphur Dioxide (SO2)', requirement: '≤ 10.00 ppm' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '≤ 5.00 ppm' },
      { characteristic: 'Total Aerobic Microbial Count', requirement: '< 200 CFU/g' },
    ],
  },
  {
    id: 'cornstarch',
    name: 'Cornstarch',
    colorFamily: 'texturizer',
    colorHex: '#ca8a04',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '9005-25-8',
    otherNames: 'Maize Starch Powder, Corn Flour, Amylum Maydis, Refined Starch',
    mf: '(C6H10O5)n',
    einecsNo: '232-679-6',
    femaNo: 'GRAS Approved',
    placeOfOrigin: 'Gujarat / Maharashtra, India',
    types: 'Thickening Agent, Texture Stabilizer, Anti-caking Agent, Tablet Disintegrant',
    brandName: 'Exim India Corporation',
    modelNumber: 'Food Additive CS-06',
    grade: 'Food & Pharmaceutical Grade (IP / BP / USP / FCC)',
    colorDesc: 'Pure White Fine Free-Flowing Powder',
    applicationSummary: 'Soups & Gravies, Puddings & Custards, Bakery Batters, Confectionery Molding, Pharmaceutical Tablets',
    purity: 'Starch Content ≥ 98.5% (Dry Basis)',
    shelfLife: '2 Years',
    packagingDetails: '25 Kg / 50 Kg Multi-layer Kraft Paper Bags / PP Woven Bags',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A DRY, CLEAN, VENTILATED WAREHOUSE AWAY FROM ODOROUS SUBSTANCES',
    image: cornstarchImg,
    analysis: [
      { characteristic: 'Starch Content (Dry Basis)', requirement: '≥ 98.50%' },
      { characteristic: 'Moisture', requirement: '≤ 13.00%' },
      { characteristic: 'Total Ash', requirement: '≤ 0.20%' },
      { characteristic: 'Protein (Dry Basis)', requirement: '≤ 0.40%' },
      { characteristic: 'pH Value (10% Aqueous Slurry)', requirement: '4.50 – 7.00' },
      { characteristic: 'Fineness (Passing 100 Mesh)', requirement: '≥ 99.50%' },
      { characteristic: 'Sulphur Dioxide (SO2)', requirement: '≤ 30.00 ppm' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '≤ 10.00 ppm' },
    ],
  },
  {
    id: 'saffron',
    name: 'Saffron',
    colorFamily: 'specialty',
    colorHex: '#ea580c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '84604-17-1 / Crocin: 42553-65-1',
    otherNames: 'Crocus Sativus, Kesar, Zafran, Red Gold Saffron Filaments',
    mf: 'Natural Crocin, Picrocrocin & Safranal Bioactive Complex',
    einecsNo: '283-295-0',
    femaNo: '2999',
    placeOfOrigin: 'Kashmir / India',
    types: 'Premium Natural Colorant, Flavoring Agent & Botanical Extract',
    brandName: 'Exim India Corporation',
    modelNumber: 'Food Additive SAF-07',
    grade: 'ISO 3632 Category I (Super Negin / All-Red Filaments)',
    colorDesc: 'Deep Crimson Red Stigmas with Golden Tips',
    applicationSummary: 'Traditional Sweets, Biryani & Rice Dishes, Dairy & Ice Creams, Premium Liqueurs, Herbal Formulations',
    purity: 'Crocin Coloring Strength ≥ 220 (ISO 3632 Cat I)',
    shelfLife: '3 Years',
    packagingDetails: '1g, 5g, 10g, 25g, 100g, 500g, 1 Kg Airtight Aluminum Tins / Vacuum Sealed Pouches',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN AN AIRTIGHT LIGHT-PROOF CONTAINER IN A COOL, DARK, DRY PLACE',
    image: saffronImg,
    analysis: [
      { characteristic: 'Coloring Strength (Crocin E1% 440nm)', requirement: '≥ 220 (Category I)' },
      { characteristic: 'Flavor Strength (Picrocrocin E1% 257nm)', requirement: '≥ 70.00' },
      { characteristic: 'Aroma Strength (Safranal E1% 330nm)', requirement: '20.00 – 50.00' },
      { characteristic: 'Moisture & Volatile Matter', requirement: '≤ 10.00%' },
      { characteristic: 'Total Ash', requirement: '≤ 5.00%' },
      { characteristic: 'Acid Insoluble Ash', requirement: '≤ 1.00%' },
      { characteristic: 'Floral Waste & Foreign Matter', requirement: '< 0.50%' },
      { characteristic: 'Artificial Colorants', requirement: 'Completely Absent' },
    ],
  },
]
