// Master Dataset for Fruit Fragrances with Authentic IFRA Specifications & Olfactory Profiles
// Images imported directly from src/assets/img/fruit-fragrance/

import raspberryImg from '../assets/img/fruit-fragrance/raspberry-perfume.jpg'
import raspberry2651Img from '../assets/img/fruit-fragrance/raspberry-perfume1.jpg'
import strawberryImg from '../assets/img/fruit-fragrance/strawberry-perfume.jpg'
import vanillaImg from '../assets/img/fruit-fragrance/vanilla-perfume.jpg'
import almondImg from '../assets/img/fruit-fragrance/almond-perfume.Jpg'
import apricotImg from '../assets/img/fruit-fragrance/apricot-perfume.jpg'
import appleImg from '../assets/img/fruit-fragrance/apple-perfume.jpg'
import chocolate2796Img from '../assets/img/fruit-fragrance/chocolate-perfume.jpg'
import chocolate2810Img from '../assets/img/fruit-fragrance/chocolate-perfume2.jpg'
import lemonImg from '../assets/img/fruit-fragrance/lemon-perfume.jpg'
import milkHoneyImg from '../assets/img/fruit-fragrance/milk-&-honey.jpg'
import peachImg from '../assets/img/fruit-fragrance/peach-perfume.jpg'
import watermelonImg from '../assets/img/fruit-fragrance/watermelon-perfume.jpg'

export const FRAGRANCE_ANALYSIS_SPECS = [
  { characteristic: 'Physical Appearance', requirement: 'Clear to Light Yellow Liquid Aromatic Compound' },
  { characteristic: 'Specific Gravity (at 20°C)', requirement: '0.980 – 1.050' },
  { characteristic: 'Refractive Index (at 20°C)', requirement: '1.435 – 1.495' },
  { characteristic: 'Flash Point (Closed Cup)', requirement: '> 65°C – 95°C' },
  { characteristic: 'Regulatory Compliance', requirement: '100% IFRA Standard & GRAS Compliant' },
  { characteristic: 'Solubility Profile', requirement: 'Soluble in alcohols, mineral oils, diethyl phthalate (DEP) & dipropylene glycol (DPG)' },
  { characteristic: 'Odor Tenacity on Blotter', requirement: '> 48 Hours Substantivity' },
  { characteristic: 'Heavy Metals (as Pb), Max.', requirement: '< 5.00 ppm' },
]

export const FRAGRANCE_APPLICATIONS = [
  {
    category: 'Personal Care & Cosmetics',
    applications: 'Body lotions, shower gels, hand washes, shampoos, facial scrubs, and body mists.',
    feature: 'Dermatologically safe, hypoallergenic, and non-irritating formulations complying with IFRA guidelines.',
  },
  {
    category: 'Fine Soaps & Detergents',
    applications: 'Transparent bath soaps, luxury bar soaps, liquid laundry detergents, and fabric softeners.',
    feature: 'High alkaline stability, zero discoloration in saponified fatty acids, and persistent laundry blooming.',
  },
  {
    category: 'Air Care & Home Fragrance',
    applications: 'Reed diffusers, scented candles, aerosol room sprays, electric plug-ins, and car fresheners.',
    feature: 'Excellent vapor pressure diffusion, clean wax burning compatibility, and long-lasting room projection.',
  },
  {
    category: 'Fine Fragrances & Perfumery',
    applications: 'Eau de Parfum (EDP), Eau de Toilette (EDT), cologne sprays, and roll-on perfume oils.',
    feature: 'Sophisticated top, middle, and dry-down olfactory transitions crafted with high-tenacity fixatives.',
  },
]

export const FRUIT_FRAGRANCE_PRODUCTS = [
  {
    id: 'raspberry-perfume',
    name: 'Raspberry Perfume',
    image: raspberryImg,
    category: 'berries',
    groupName: 'Berry Accords',
    olfactoryNote: 'Sweet, juicy wild raspberry with subtle floral and balsamic undertones',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Enchanting and tart wild raspberry fragrance oil engineered for luxury bath gels, lip care formulations, shampoo systems, and youthful summer body mists.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'raspberry-perfume-2651',
    name: 'Raspberry Perfume 2651',
    image: raspberry2651Img,
    category: 'berries',
    groupName: 'Berry Accords',
    olfactoryNote: 'Concentrated ripe red raspberry with candied sugar nuances and berry leaf accord',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'High-substantivity raspberry formulation code 2651 designed for premium laundry softeners, air diffusers, and luxury hand wash soaps requiring intense fragrance bloom.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'strawberry-af-300697',
    name: 'Strawberry AF-300697',
    image: strawberryImg,
    category: 'berries',
    groupName: 'Berry Accords',
    olfactoryNote: 'Lush field-fresh strawberry accord, cotton candy sweetness, and light green calyx notes',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Artisanal strawberry compound AF-300697 capturing sparkling summer berry sweetness. Extensively formulated in lip balms, baby soaps, massage oils, and ambient reed diffusers.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'vanilla-os-aff',
    name: 'Vanilla OS AFF',
    image: vanillaImg,
    category: 'gourmand',
    groupName: 'Gourmand & Warm',
    olfactoryNote: 'Warm Bourbon vanilla bean, creamy tonka bean, amber base, and delicate caramel notes',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Opulent warm Madagascar vanilla accord with superior base-note fixative persistence. Highly requested for luxury scented candles, body butters, and fine gourmand perfumes.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'almond-perfume',
    name: 'Almond Perfume',
    image: almondImg,
    category: 'gourmand',
    groupName: 'Gourmand & Warm',
    olfactoryNote: 'Toasted bitter almond, marzipan sweetness, nutty facets, and soft heliotrope florals',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Classic Italian marzipan almond aromatic blend. Exceptional performance in cold-process soaps, nourishing hair oils, conditioning creams, and vintage cologne bases.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'apricot-perfume',
    name: 'Apricot Perfume',
    image: apricotImg,
    category: 'orchard',
    groupName: 'Orchard & Citrus',
    olfactoryNote: 'Velvety ripe apricot skin, honeyed nectar, and subtle Osmanthus floral nuances',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Soft, golden apricot essence engineered for gentle skincare lines, facial cleansers, baby wipe lotions, and suncare tanning creams.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'apple-perfume',
    name: 'Apple Perfume',
    image: appleImg,
    category: 'orchard',
    groupName: 'Orchard & Citrus',
    olfactoryNote: 'Crisp Granny Smith green apple, tart malic freshness, and dewy morning orchard air',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Invigorating and sparkling crisp green apple perfume. A commercial favourite for dishwashing liquids, hair clarifying shampoos, room fresheners, and sporty shower gels.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'chocolate-perfume-2796',
    name: 'Chocolate Perfume 2796',
    image: chocolate2796Img,
    category: 'gourmand',
    groupName: 'Gourmand & Warm',
    olfactoryNote: 'Dark roasted cocoa beans, rich ganache, bittersweet cocoa butter, and roasted malt',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Deep, comforting cocoa ganache fragrance compound 2796. Formulated for luxury spa body wraps, cocoa butter lotions, scented wax melts, and novelty cosmetic lines.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'chocolate-perfume-af-2810',
    name: 'Chocolate Perfume AF-2810',
    image: chocolate2810Img,
    category: 'gourmand',
    groupName: 'Gourmand & Warm',
    olfactoryNote: 'Creamy milk chocolate praline, buttery vanilla fudge, and warm hazelnut nuances',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Indulgent milk chocolate aroma formulation AF-2810 with irresistible gourmand appeal. Outstanding stability in lip balms, body scrubs, massage candles, and holiday room sprays.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'lemon-perfume-2843',
    name: 'Lemon Perfume 2843',
    image: lemonImg,
    category: 'orchard',
    groupName: 'Orchard & Citrus',
    olfactoryNote: 'Freshly zested Italian lemon peel, sparkling citrus zest, and clean verbena accord',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'High-potency citrus lemon perfume 2843 rich in natural limonene radiance. The premier choice for antibacterial soaps, degreasing kitchen cleaners, car deodorizers, and citrus colognes.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'milk-honey-perfume',
    name: 'Milk & Honey Perfume',
    image: milkHoneyImg,
    category: 'gourmand',
    groupName: 'Gourmand & Warm',
    olfactoryNote: 'Warm golden wildflower honey, sweet steamed milk accord, and creamy almond blossoms',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Soothing and comforting milk & honey fragrance accord renowned for luxury spa products, oatmeal bath soaps, intensive hand creams, and nourishing body conditioners.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'peach-perfume-2846',
    name: 'Peach Perfume 2846',
    image: peachImg,
    category: 'orchard',
    groupName: 'Orchard & Citrus',
    olfactoryNote: 'Sun-drenched Georgia white peach, nectarine sweetness, and velvet floral undertones',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Irresistibly juicy and delicate peach fragrance compound 2846. Ideal for feminine body lotions, facial sheet masks, transparent glycerine soaps, and summery room sprays.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
  {
    id: 'watermelon-perfume',
    name: 'Water-melon Perfume',
    image: watermelonImg,
    category: 'orchard',
    groupName: 'Orchard & Citrus',
    olfactoryNote: 'Refreshing crisp red watermelon pulp, aquatic melon rind, and light crystalline sugar',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg / 200 Kg UN-approved HDPE drums with airtight bung seals',
    shelfLife: '36 Months from Manufacturing Date',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight, open flames, and heat sources.',
    applicationSummary: 'Hydro-fresh summer watermelon fragrance bringing crisp aquatic sweetness to hair gels, body cooling sprays, splash colognes, and refreshing hand sanitizers.',
    analysis: FRAGRANCE_ANALYSIS_SPECS,
  },
]
