// Master Dataset for Aluminum Lake Colours with Authentic Specifications and Quality Analysis Data
// Images imported from src/assets/img/lake/ and src/assets/img/efc/

import lakeTartrazineImg from '../assets/img/lake/lake-tartrazine.jpg'
import ponceau4rImg from '../assets/img/lake/Ponceau-4R.jpg'
import lakeAlluraRedImg from '../assets/img/lake/lake-allura-red.jpg'
import sunsetYellowLakeImg from '../assets/img/efc/Sunset-Yellow-FCF-aluminum-lake.jpg'
import carmoisineLakeImg from '../assets/img/efc/Food-Color-Carmoisine.jpg'
import erythrosineLakeImg from '../assets/img/efc/food-grade-erythrosine.jpg'
import brownHtLakeImg from '../assets/img/efc/Brown-HT.jpg'
import quinolineYellowLakeImg from '../assets/img/efc/Quinoline-yellow.jpg'
import amaranthLakeImg from '../assets/img/efc/amarnath.jpg'
import brilliantBlueLakeImg from '../assets/img/efc/Brilliant-Blue.jpg'
import indigoCarmineLakeImg from '../assets/img/efc/Indigo-Carmine.png'
import blackPnLakeImg from '../assets/img/efc/Black-PN.jpg'

export const LAKE_ANALYSIS_SPECS = [
  { characteristic: 'Total dye content, corrected for sample dried at 105°C for 2 hr, Min.', requirement: '12.00% to 45.00%' },
  { characteristic: 'Water-insoluble matter, percent by mass, Max.', requirement: '00.20%' },
  { characteristic: 'Combined ether extracts, percent by mass, Max.', requirement: '00.20%' },
  { characteristic: 'Subsidiary dyes, percent by mass, Max.', requirement: '03.00%' },
  { characteristic: 'Organic Compound other than coloring matter, Max.', requirement: '01.50%' },
  { characteristic: 'Unsulfonated primary aromatic amine (as aniline), Max.', requirement: '00.01%' },
  { characteristic: 'Lead (Pb), mg/kg, Max.', requirement: '02.00 ppm' },
  { characteristic: 'Arsenic (As), mg/kg, Max.', requirement: '03.00 ppm' },
  { characteristic: 'Cadmium (Cd), mg/kg, Max.', requirement: '01.00 ppm' },
  { characteristic: 'Mercury (Hg), mg/kg, Max.', requirement: '01.00 ppm' },
  { characteristic: 'Total Heavy metals (as Pb), mg/kg, Max.', requirement: '40.00 ppm' },
]

export const LAKE_COLORS = [
  {
    id: 'lake-tartrazine',
    name: 'Lake Tartrazine',
    colorFamily: 'yellow',
    colorHex: '#eab308',
    eNumber: 'E102',
    ciNo: '19140:1',
    fdcName: 'FD&C Yellow No. 5 Lake',
    casNo: '1934-21-0',
    einecsNo: '217-699-5',
    femaNo: 'Tartrazine Lake',
    otherNames: 'Tartrazine Aluminum Lake, Acid Yellow 23 Lake',
    mf: 'C16H9N4Na3O9S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Tablet Coating, Insoluble Pigments',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Tartrazine',
    grade: 'Food Grade / Pharma Grade (US-FDA & EU Approved)',
    colorDesc: 'Fine Yellow Powder',
    applicationSummary: 'Pharmaceutical Tablet Coating, Bakery, Confectionery, Dry Mixes & Cosmetics',
    purity: '12% – 45% Pure Dye Content (Low & High Dye Options)',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: lakeTartrazineImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-ponceau-4r',
    name: 'Lake Ponceau 4R',
    colorFamily: 'red',
    colorHex: '#dc2626',
    eNumber: 'E124',
    ciNo: '16255:1',
    fdcName: 'Food Red 7 Lake',
    casNo: '2611-82-7',
    einecsNo: '220-036-2',
    femaNo: 'Ponceau 4R Lake',
    otherNames: 'Cochineal Red A Lake, Acid Red 18 Lake',
    mf: 'C20H11N2Na3O10S3·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Aluminum Lake Pigments',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Ponceau 4R',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Deep Scarlet Red Powder',
    applicationSummary: 'Dessert Powders, Snack Foods, Encapsulated Flavours & Seasonings',
    purity: '15% – 40% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: ponceau4rImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-allura-red',
    name: 'Lake Allura Red',
    colorFamily: 'red',
    colorHex: '#e11d48',
    eNumber: 'E129',
    ciNo: '16035:1',
    fdcName: 'FD&C Red No. 40 Lake',
    casNo: '25956-17-6',
    einecsNo: '247-368-0',
    femaNo: 'Allura Red AC Lake',
    otherNames: 'Food Red 17 Lake, Allura Red Aluminum Lake',
    mf: 'C18H14N2Na2O8S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Flavoring Agents, Pharmaceutical Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: '16035:1',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Bright Red Powder',
    applicationSummary: 'Hard Candies, Chewing Gums, Pharmaceutical Coatings & Dairy Products',
    purity: '15% – 42% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: lakeAlluraRedImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-sunset-yellow',
    name: 'Lake Sunset Yellow FCF',
    colorFamily: 'yellow',
    colorHex: '#ea580c',
    eNumber: 'E110',
    ciNo: '15985:1',
    fdcName: 'FD&C Yellow No. 6 Lake',
    casNo: '15790-07-5',
    einecsNo: '239-888-1',
    femaNo: 'Sunset Yellow Lake',
    otherNames: 'Food Yellow 3:1, Orange Yellow S Lake',
    mf: 'C16H10N2Na2O7S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Insoluble Food & Cosmetic Pigments',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Sunset Yellow',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Vibrant Sunset Orange Powder',
    applicationSummary: 'Bakery Icings, Biscuits, Snack Seasonings, Syrups & Gelatin Desserts',
    purity: '15% – 40% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: sunsetYellowLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-carmoisine',
    name: 'Lake Carmoisine',
    colorFamily: 'red',
    colorHex: '#be123c',
    eNumber: 'E122',
    ciNo: '14720:1',
    fdcName: 'Food Red 3 Lake',
    casNo: '3567-69-9',
    einecsNo: '222-657-4',
    femaNo: 'Azorubine Lake',
    otherNames: 'Azorubine Lake, Carmoisine Aluminum Lake',
    mf: 'C20H12N2Na2O7S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Food Pigments',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Carmoisine',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Deep Crimson Red Powder',
    applicationSummary: 'Jams, Jellies, Marzipan, Confectionery & Cosmetics',
    purity: '15% – 38% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: carmoisineLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-erythrosine',
    name: 'Lake Erythrosine',
    colorFamily: 'red',
    colorHex: '#f43f5e',
    eNumber: 'E127',
    ciNo: '45430:1',
    fdcName: 'FD&C Red No. 3 Lake',
    casNo: '16423-68-0',
    einecsNo: '240-474-8',
    femaNo: 'Erythrosine Lake',
    otherNames: 'Food Red 14 Lake, Erythrosine Aluminum Lake',
    mf: 'C20H6I4Na2O5·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Pharma Lake Pigments',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Erythrosine',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Cherry Pinkish-Red Powder',
    applicationSummary: 'Pharmaceutical Tablet Coating, Maraschino Cherries & Cake Decorations',
    purity: '15% – 35% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: erythrosineLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-brown-ht',
    name: 'Lake Brown HT',
    colorFamily: 'brown',
    colorHex: '#78350f',
    eNumber: 'E155',
    ciNo: '20285:1',
    fdcName: 'Chocolate Brown HT Lake',
    casNo: '4553-89-3',
    einecsNo: '224-924-0',
    femaNo: 'Brown HT Lake',
    otherNames: 'Chocolate Brown Lake, Food Brown 1 Lake',
    mf: 'C27H18N4Na2O9S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Insoluble Brown Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Brown HT',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Rich Chocolate Brown Powder',
    applicationSummary: 'Chocolate Bakery Goods, Biscuits, Wafer Fillings & Dessert Powders',
    purity: '15% – 35% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: brownHtLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-quinoline-yellow',
    name: 'Lake Quinoline Yellow',
    colorFamily: 'yellow',
    colorHex: '#facc15',
    eNumber: 'E104',
    ciNo: '47005:1',
    fdcName: 'Food Yellow 13 Lake',
    casNo: '8004-92-0',
    einecsNo: '305-897-5',
    femaNo: 'Quinoline Yellow Lake',
    otherNames: 'Acid Yellow 3 Lake, Quinoline Yellow Aluminum Lake',
    mf: 'C18H9NNa2O8S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Bright Yellow Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Quinoline Yellow',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Greenish-Yellow Fine Powder',
    applicationSummary: 'Cosmetics, Soap Bars, Hard Candies, Confectionery & Medicines',
    purity: '15% – 30% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: quinolineYellowLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-amaranth',
    name: 'Lake Amaranth',
    colorFamily: 'red',
    colorHex: '#9f1239',
    eNumber: 'E123',
    ciNo: '16185:1',
    fdcName: 'FD&C Red No. 2 Lake',
    casNo: '915-67-3',
    einecsNo: '213-022-2',
    femaNo: 'Amaranth Lake',
    otherNames: 'Acid Red 27 Lake, Food Red 9 Lake',
    mf: 'C20H11N2Na3O10S3·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Aluminum Lake Pigments',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Amaranth',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Dark Reddish-Brown to Purple Powder',
    applicationSummary: 'Beverage Concentrates, Jellies, Aperitifs & Cosmetic Powders',
    purity: '15% – 38% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: amaranthLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-brilliant-blue',
    name: 'Lake Brilliant Blue FCF',
    colorFamily: 'blue',
    colorHex: '#0284c7',
    eNumber: 'E133',
    ciNo: '42090:1',
    fdcName: 'FD&C Blue No. 1 Lake',
    casNo: '3844-45-9',
    einecsNo: '223-339-8',
    femaNo: 'Brilliant Blue Lake',
    otherNames: 'Acid Blue 9 Lake, Food Blue 2 Lake',
    mf: 'C37H34N2Na2O9S3·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Blue Aluminum Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Brilliant Blue',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Intense Blue Powder',
    applicationSummary: 'Toothpastes, Confectionery, Eyeliners, Ice Creams & Pharmaceutical Coatings',
    purity: '12% – 35% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: brilliantBlueLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-indigo-carmine',
    name: 'Lake Indigo Carmine',
    colorFamily: 'blue',
    colorHex: '#3b82f6',
    eNumber: 'E132',
    ciNo: '73015:1',
    fdcName: 'FD&C Blue No. 2 Lake',
    casNo: '860-22-0',
    einecsNo: '212-728-8',
    femaNo: 'Indigotine Lake',
    otherNames: 'Indigotine Lake, Acid Blue 74 Lake',
    mf: 'C16H8N2Na2O8S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Indigo Lakes',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Indigo Carmine',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Deep Indigo Blue Powder',
    applicationSummary: 'Capsule Coating, Biscuits, Pet Food, Candies & Confectionery',
    purity: '12% – 32% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: indigoCarmineLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
  {
    id: 'lake-black-pn',
    name: 'Lake Black PN',
    colorFamily: 'black',
    colorHex: '#1e293b',
    eNumber: 'E151',
    ciNo: '28440:1',
    fdcName: 'Brilliant Black BN Lake',
    casNo: '2519-30-4',
    einecsNo: '219-746-5',
    femaNo: 'Black PN Lake',
    otherNames: 'Black PN Aluminum Lake, Food Black 1 Lake',
    mf: 'C28H17N5Na4O14S4·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Insoluble Black Pigments',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Black PN',
    grade: 'Food Grade / Pharma Grade',
    colorDesc: 'Fine Jet Black Powder',
    applicationSummary: 'Licorice, Dark Sauces, Confectionery, Savory Coatings & Cosmetics',
    purity: '15% – 35% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg HDPE DRUM or As per customers requirement',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PLEASE KEEP IN CLOSED CONTAINERS AT AMBIENT TEMP & HUMIDITY',
    image: blackPnLakeImg,
    analysis: LAKE_ANALYSIS_SPECS,
  },
]
