// Master Dataset for Liquid Flavours with Authentic Specifications and Analytical Parameters
// Images imported directly from src/assets/img/lf/

import almondImg from '../assets/img/lf/almond-flavour.jpg'
import appleSweetImg from '../assets/img/lf/Apple Sweet.jpg'
import apricotImg from '../assets/img/lf/apricot-natural-flavor-500x500.jpeg'
import biscuitImg from '../assets/img/lf/Biscuit Flavour.jpg'
import blackcurrantImg from '../assets/img/lf/blackcurrant.jpg'
import blueberryImg from '../assets/img/lf/Blueberry Liquied Flavour.jpg'
import caramelImg from '../assets/img/lf/caramel Liquid Flavour.jpg'
import cheeseImg from '../assets/img/lf/Chees Liquid Flavour.jpg'
import cherryImg from '../assets/img/lf/Cherry-Flavour-E-liquid.jpg'
import chocolateImg from '../assets/img/lf/Chocklate Liquied Flavour.jpg'
import vanillaImg from '../assets/img/lf/eliquid-vanilla-flavour-500.jpg'
import honeyImg from '../assets/img/lf/Honey Liquied Flavour.jpg'
import lemonImg from '../assets/img/lf/lemon Liquid Flavour.jpg'
import licheeImg from '../assets/img/lf/Lichi Liquied Flavour.jpg'
import mangoImg from '../assets/img/lf/mango-Liquid Flavour.jpg'
import mintImg from '../assets/img/lf/Mint Liquid Flavour.jpg'
import mixedberriesImg from '../assets/img/lf/mixedberries.jpg'
import orangeImg from '../assets/img/lf/Orange-liquid-and-powder-food-grade-flavour.jpg'
import roseImg from '../assets/img/lf/rose.jpg'
import strawberryImg from '../assets/img/lf/Strawberry-Flavour-E-Liquid.jpg'

export const LIQUID_FLAVOUR_ANALYSIS_SPECS = [
  { characteristic: 'Specific Gravity (at 20°C / 25°C)', requirement: '0.980 – 1.050 g/cm³' },
  { characteristic: 'Refractive Index (at 20°C)', requirement: '1.380 – 1.450' },
  { characteristic: 'Organoleptic Profile (Odour & Taste)', requirement: 'Characteristic, true to nature, free from off-notes' },
  { characteristic: 'Solubility', requirement: 'Freely soluble in Water, Propylene Glycol & Alcohol' },
  { characteristic: 'Flash Point (Closed Cup)', requirement: '> 65°C' },
  { characteristic: 'Total Heavy Metals (as Pb), Max.', requirement: '10.00 ppm' },
  { characteristic: 'Lead (Pb), Max.', requirement: '02.00 ppm' },
  { characteristic: 'Arsenic (As), Max.', requirement: '01.00 ppm' },
  { characteristic: 'Total Microbial Plate Count, Max.', requirement: '< 1,000 CFU/g' },
  { characteristic: 'Yeast & Mould Count, Max.', requirement: '< 100 CFU/g' },
]

export const SPECIALTY_LIQUID_ENHANCERS = [
  'Capsicum Flavour', 'Cardamom Flavour', 'Carmel Flavour', 'Cashew Nut Flavour',
  'Cheese Flavour', 'Cherry Flavour', 'Chikoo', 'Chocolate',
  'Coconut', 'Coffee Mast', 'Cola Excellent', 'Creamy Milk Flavour',
  'Cumin Flavour', 'Custard Flavour', 'Dairy Milk Flavour', 'Falsa Special',
  'Guava Fresh', 'Garlic', 'Ginger Beer Cloudy', 'Glucose Biscuit Flavour',
  'Grape Flavour', 'Groundnut Flavour', 'Honey', 'Ice-Cream Soda',
  'Jeera Masala', 'Kewra', 'Kiwi', 'Lemon',
  'Lemon Limca', 'Lichy', 'Lime Lemon', 'Mango Green Special',
  'Mango', 'Water Melon', 'Milk Toffee', 'Mint Flavour',
  'Mixed Fruit', 'Mixed Berry', 'Nutmeg Flavour', 'Nutty Coffee',
  'Orange Fanta', 'Orange', 'Peanut Special', 'Peach',
  'Peppermint', 'Pineapple', 'Plum Flavour', 'Pistachio Special',
  'Pomegranate Excellent', 'Raspberry', 'Rose', 'Rum Flavour',
  'Saffron', 'Sandal', 'Strawberry', 'Spearmint',
  'Vanilla', 'Whisky Flavour'
]

export const LIQUID_FLAVOURS = [
  {
    id: 'almond',
    name: 'Almond',
    colorFamily: 'nutty-sweet',
    colorHex: '#d97706',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Sweet Almond Food Flavour Essence',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Almond LF-101',
    grade: 'Food Grade, Pharma Grade (FSSAI, US-FDA Compliant)',
    colorDesc: 'Clear Colorless to Pale Straw Liquid',
    applicationSummary: 'Bakery, Marzipan, Confectionery, Indian Sweets, Milk Drinks & Syrups',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: almondImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'apple-sweet',
    name: 'Apple Sweet',
    colorFamily: 'fruity',
    colorHex: '#84cc16',
    moq: '50 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Sweet Green Apple Liquid Aroma',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Apple LF-102',
    grade: 'Food Grade, Beverage Grade',
    colorDesc: 'Clear Transparent Liquid',
    applicationSummary: 'Beverages, Ready-to-Drink Juices, Candies, Jellies & Syrups',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: appleSweetImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'biscuit-flavour',
    name: 'Biscuit Flavour',
    colorFamily: 'bakery-dairy',
    colorHex: '#b45309',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Baked Glucose Biscuit Aroma Concentrate',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Heat-Stable Bakery Liquid Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Biscuit LF-103',
    grade: 'Food Grade (Heat Resistant)',
    colorDesc: 'Pale Golden Yellow Liquid',
    applicationSummary: 'Biscuits, Cookies, Wafers, Cracker Dough & Toffee Fillings',
    purity: 'Heat Stable up to 240°C',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: biscuitImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'black-current',
    name: 'Black Current',
    colorFamily: 'berries',
    colorHex: '#4c1d95',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Blackcurrant Juice Essence Concentrate',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Blackcurrant LF-104',
    grade: 'Food Grade, Beverage Grade',
    colorDesc: 'Slightly Reddish Clear Liquid',
    applicationSummary: 'Carbonated Soft Drinks, Squash, Mocktails, Ice Creams & Jellies',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: blackcurrantImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'blueberry',
    name: 'Blueberry Flavour',
    colorFamily: 'berries',
    colorHex: '#1e3a8a',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Wild Blueberry Liquid Flavour',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Blueberry LF-105',
    grade: 'Food Grade, Dairy & Confectionery Grade',
    colorDesc: 'Clear Pale Violet Liquid',
    applicationSummary: 'Yogurts, Smoothies, Muffins, Cake Fillings, E-liquids & Syrups',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: blueberryImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'chocolate',
    name: 'Chocolate',
    colorFamily: 'bakery-dairy',
    colorHex: '#451a03',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Rich Cocoa & Dark Chocolate Aroma',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Heat-Resistant Liquid Chocolate Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Chocolate LF-106',
    grade: 'Food Grade, Dairy & Bakery Grade',
    colorDesc: 'Dark Brown Liquid',
    applicationSummary: 'Cakes, Brownies, Chocolate Milk, Protein Shakes & Toffees',
    purity: 'Heat Stable Flavour Compound',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: chocolateImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'cheese',
    name: 'Cheese',
    colorFamily: 'herbal-savory',
    colorHex: '#eab308',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Cheddar Cheese Liquid Savory Flavour',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Savory Liquid Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Cheese LF-107',
    grade: 'Food Grade, Snack & Savory Grade',
    colorDesc: 'Pale Yellow Liquid',
    applicationSummary: 'Potato Chips, Popcorn, Extruded Snacks, Cheese Sauces & Dips',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: cheeseImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'apricot',
    name: 'Apricot',
    colorFamily: 'fruity',
    colorHex: '#f97316',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Natural Apricot Liquid Food Aroma',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Apricot LF-108',
    grade: 'Food Grade, Beverage & Jam Grade',
    colorDesc: 'Clear Pale Orange Liquid',
    applicationSummary: 'Fruit Jams, Canned Fruits, Nectars, Confectionery & Pastries',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: apricotImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'caramel',
    name: 'Caramel Flavour',
    colorFamily: 'bakery-dairy',
    colorHex: '#92400e',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Butterscotch & Caramelized Sugar Flavour',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Heat-Resistant Liquid Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Caramel LF-109',
    grade: 'Food Grade, Confectionery Grade',
    colorDesc: 'Golden Amber Liquid',
    applicationSummary: 'Toffees, Popcorn Glaze, Coffee Syrups, Puddings & Ice Creams',
    purity: 'High Heat Stable Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: caramelImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'lemon',
    name: 'Lemon',
    colorFamily: 'citrus',
    colorHex: '#eab308',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Juicy Citrus Lemon Liquid Flavour',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Water-Soluble & Beverage Liquid Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lemon LF-110',
    grade: 'Food Grade, Beverage & Hard Boiled Candy Grade',
    colorDesc: 'Clear Liquid with Fresh Zesty Aroma',
    applicationSummary: 'Lemonades, Clear Sodas, Lozenges, Hard Candies & Bakeries',
    purity: 'Natural Terpeneless Citrus Extract',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: lemonImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'mango',
    name: 'Mango',
    colorFamily: 'fruity',
    colorHex: '#ea580c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Alphonso & Totapuri Mango Food Essence',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Mango LF-111',
    grade: 'Food Grade, Beverage & Dairy Grade',
    colorDesc: 'Bright Yellow-Orange Transparent Liquid',
    applicationSummary: 'Mango Drinks, Ice Golas, Candies, Ice Creams, Lassi & Yogurts',
    purity: 'Authentic Indian Alphonso Profile',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: mangoImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'mint',
    name: 'Mint',
    colorFamily: 'herbal-savory',
    colorHex: '#10b981',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Spearmint & Peppermint Liquid Essence',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Cooling Liquid Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Mint LF-112',
    grade: 'Food Grade, Pharma & Oral Care Grade',
    colorDesc: 'Clear Liquid with Intense Cooling Sensation',
    applicationSummary: 'Chewing Gums, Toothpastes, Breath Fresheners, Syrups & Chuskis',
    purity: 'Pure Menthol & Spearmint Extracts',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: mintImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'mixed-berry',
    name: 'Mixed Berry',
    colorFamily: 'berries',
    colorHex: '#9333ea',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Forest Berry Cocktail Liquid Flavour',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'MixedBerry LF-113',
    grade: 'Food Grade, Beverage & Confectionery Grade',
    colorDesc: 'Slightly Reddish Purple Liquid',
    applicationSummary: 'Energy Drinks, RTD Mocktails, Gelatin Candies, Flavored Waters & Teas',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: mixedberriesImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'orange',
    name: 'Orange',
    colorFamily: 'citrus',
    colorHex: '#ea580c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Sweet Orange Oil & Citrus Flavour',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Beverage Emulsion Base',
    brandName: 'Exim India Corporation',
    modelNumber: 'Orange LF-114',
    grade: 'Food Grade, Beverage Grade',
    colorDesc: 'Bright Orange Clear Liquid',
    applicationSummary: 'Carbonated Orange Sodas, Fruit Juices, Ice Pops, Pastries & Lozenges',
    purity: 'Cold-Pressed Valencia Orange Notes',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: orangeImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'rose',
    name: 'Rose',
    colorFamily: 'herbal-savory',
    colorHex: '#f43f5e',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Damask Rose Otto Food Essence',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Floral Culinary Flavour Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Rose LF-115',
    grade: 'Food Grade, Ethnic Sweets Grade',
    colorDesc: 'Clear Liquid with Fresh Floral Aroma',
    applicationSummary: 'Rose Milk, Falooda, Rooh-Afza type Syrups, Gulab Jamun & Desserts',
    purity: 'Distilled Indian Rose Profile',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: roseImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    colorFamily: 'berries',
    colorHex: '#e11d48',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Fresh Ripe Strawberry Aroma Essence',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Strawberry LF-116',
    grade: 'Food Grade, Dairy & Beverage Grade',
    colorDesc: 'Clear Pinkish Liquid',
    applicationSummary: 'Milkshakes, Ice Creams, Toffees, Syrups, Wafers & Jelly Cups',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: strawberryImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'lichee',
    name: 'Lichee',
    colorFamily: 'fruity',
    colorHex: '#f472b6',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Lychee Fruit Liquid Aroma Compound',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lichee LF-117',
    grade: 'Food Grade, Beverage Grade',
    colorDesc: 'Clear Colorless Liquid with Sweet Lychee Notes',
    applicationSummary: 'Lychee Nectars, Boba Drinks, Hard Boiled Candies & Ice Slushes',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: licheeImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'cherry',
    name: 'Cherry',
    colorFamily: 'fruity',
    colorHex: '#be123c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Wild Red Cherry Food Essence',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Cherry LF-118',
    grade: 'Food Grade, Pharma & Soda Grade',
    colorDesc: 'Clear Reddish Liquid with Fruity Tart Aroma',
    applicationSummary: 'Cherry Colas, Cough Syrups, Lozenges, Pastries & Chewing Gums',
    purity: 'High Concentration Essence',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: cherryImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'honey',
    name: 'Honey',
    colorFamily: 'nutty-sweet',
    colorHex: '#d97706',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'Wildflower Honey Liquid Aroma',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Liquid Food Flavour, Water-Soluble Essence',
    brandName: 'Exim India Corporation',
    modelNumber: 'Honey LF-119',
    grade: 'Food Grade, Breakfast Cereals & Bakery Grade',
    colorDesc: 'Golden Amber Viscous Liquid',
    applicationSummary: 'Honey Graham Crackers, Breakfast Cereals, Herbal Teas, Syrups & Cough Drops',
    purity: 'Rich Floral Honey Profile',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: honeyImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
  {
    id: 'vanilla',
    name: 'Vanilla',
    colorFamily: 'bakery-dairy',
    colorHex: '#ca8a04',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Proprietary Blend',
    otherNames: 'French Bourbon Vanilla Food Essence',
    mf: 'Natural & Nature-Identical Blend',
    einecsNo: 'Flavouring Preparation',
    femaNo: 'FEMA GRAS Approved',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Heat-Resistant Liquid Vanilla Flavour',
    brandName: 'Exim India Corporation',
    modelNumber: 'Vanilla LF-120',
    grade: 'Food Grade, Dairy & Bakery Grade',
    colorDesc: 'Clear Amber-Brown Liquid with Rich Creamy Vanillin Notes',
    applicationSummary: 'Ice Creams, Custards, Sponge Cakes, Cookies, Milk Powders & Chocolates',
    purity: 'High Vanillin Content, Heat Resistant up to 250°C',
    shelfLife: '2 - 3 Years',
    packagingDetails: '5 / 25 / 30 Kgs HDPE Cans, 200 Kgs Barrels',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'Store in tightly sealed containers in a cool, dry place away from direct sunlight.',
    image: vanillaImg,
    analysis: LIQUID_FLAVOUR_ANALYSIS_SPECS,
  },
]
