// Master Dataset for Pure Indian Mango Pulps & Purees with Authentic Specifications and Analytical Data
// Images imported directly from src/assets/img/mango-pulp/

import alphonsoPulpImg from '../assets/img/mango-pulp/alphonso-pulp.jpg'
import totapuriPulpImg from '../assets/img/mango-pulp/totapuri-pulp.jpg'
import kesarPulpImg from '../assets/img/mango-pulp/kesar-pulp.jpg'

export const MANGO_PULP_STANDARDS = [
  { characteristic: 'Microbiological Quality', requirement: 'Commercially Sterile (Free from Pathogens & Osmophilic Yeasts)' },
  { characteristic: 'Heavy Metals (as Pb), Max.', requirement: '1.00 ppm' },
  { characteristic: 'Arsenic (As), Max.', requirement: '0.10 ppm' },
  { characteristic: 'Pesticide Residues', requirement: 'Complies with US-FDA, EU MRL & FSSAI Limits' },
  { characteristic: 'Preservatives', requirement: '100% Free from Artificial Colors, Preservatives or Flavors' },
  { characteristic: 'Processing Method', requirement: 'Thermal Aseptic Sterilization & Deaeration (Flash Pasteurized)' },
]

export const MANGO_PULPS = [
  {
    id: 'alphonso-mango-pulp',
    name: 'Alphonso Mango Pulp',
    variety: 'alphonso',
    colorHex: '#ea580c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Natural Fruit Puree',
    otherNames: 'Alphonso Puree, Hapus Mango Pulp, Sweetened / Natural Alphonso Pulp',
    mf: '100% Pure Alphonso Mango (Mangifera Indica L.)',
    einecsNo: 'Natural Food Product',
    femaNo: 'Natural Fruit Preparation',
    placeOfOrigin: 'Ratnagiri / Konkan, Maharashtra, India',
    types: 'Aseptic Fruit Puree / Canned Mango Pulp',
    brandName: 'Exim India Corporation',
    modelNumber: 'Mango Pulp AMP-01',
    grade: 'Export Grade (FSSAI, ISO 22000, US-FDA Registered)',
    colorDesc: 'Intense Golden Yellow Homogeneous Puree',
    applicationSummary: 'Mango RTD Beverages, Ice Creams, Yogurts, Fruit Jams, Sorbets, Confectionery & Pastry Glazes',
    purity: '100% Pure, Free from Added Fillers',
    shelfLife: '2 Years (24 Months)',
    packagingDetails: '20/50/200 Kg Aseptic Bag-in-Drum / 3.1 Kg A10 OTS Cans (6 Cans/Carton)',
    deliveryDetail: 'Shipped in 15-20 days after order confirmation',
    storage: 'KEEP IN CLOSED CONTAINERS AT AMBIENT TEMPERATURE AND DRY HUMIDITY',
    image: alphonsoPulpImg,
    analysis: [
      { characteristic: 'Total Soluble Solids (TSS at 20°C)', requirement: '24.0° – 26.0° Brix (Sweetened) / Min 16.0° Brix (Natural)' },
      { characteristic: 'Acidity (as Citric Acid % w/w)', requirement: '0.50% – 0.75%' },
      { characteristic: 'pH Value (at 20°C)', requirement: '3.60 – 4.00' },
      { characteristic: 'Consistency (Bostwick at 20°C / 30 sec)', requirement: '8.0 – 12.0 cm' },
      { characteristic: 'Viscosity (Ford Cup No. 4)', requirement: '24 Seconds' },
      { characteristic: 'Vacuum in Cans', requirement: 'Min 10 Inches Hg' },
      { characteristic: 'Head Space', requirement: '< 6.0 mm' },
      { characteristic: 'Black / Brown Specks', requirement: 'NIL / Nil Per 10g' },
      { characteristic: 'Color & Flavor', requirement: 'Characteristics of Ripe Alphonso, Sweet & Fragrant' },
    ],
  },
  {
    id: 'totapuri-mango-pulp',
    name: 'Totapuri Mango Pulp',
    variety: 'totapuri',
    colorHex: '#eab308',
    moq: '215 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Natural Fruit Puree',
    otherNames: 'Totapuri Puree, Ginimoothi Mango Puree, Standard Industrial Mango Pulp',
    mf: '100% Totapuri Mango (Mangifera Indica L.)',
    einecsNo: 'Natural Food Product',
    femaNo: 'Natural Fruit Preparation',
    placeOfOrigin: 'Andhra Pradesh / Tamil Nadu / Karnataka, India',
    types: 'Aseptic Industrial Mango Pulp / Concentrate',
    brandName: 'Exim India Corporation',
    modelNumber: 'Mango Pulp TMP-02',
    grade: 'Industrial Food & Beverage Grade (ISO, HACCP, FSSAI)',
    colorDesc: 'Bright Uniform Golden Yellow',
    applicationSummary: 'Fruit Juices, Nectars, Beverage Blends, Bakery Fillings, Sauces, Chutneys, Dairy Smoothies',
    purity: '100% Natural Selected Fruit',
    shelfLife: '2 Years (24 Months)',
    packagingDetails: '215 Kg Aseptic Bag in Steel Drums / 3.1 Kg A10 Cans',
    deliveryDetail: 'Shipped in 15-20 days after order confirmation',
    storage: 'KEEP IN CLOSED CONTAINERS AT AMBIENT TEMPERATURE AND DRY HUMIDITY',
    image: totapuriPulpImg,
    analysis: [
      { characteristic: 'Total Soluble Solids (TSS at 20°C)', requirement: 'Min 14.0° Brix' },
      { characteristic: 'Acidity (as Citric Acid % w/w)', requirement: '0.45% – 0.70%' },
      { characteristic: 'pH Value (at 20°C)', requirement: '3.50 – 3.80' },
      { characteristic: 'Consistency (Bostwick at 20°C / 30 sec)', requirement: '7.0 – 11.0 cm' },
      { characteristic: 'Brown Specks', requirement: '< 5 nos per 10g of pulp' },
      { characteristic: 'Black Specks', requirement: 'NIL' },
      { characteristic: 'Net Weight (A10 Can)', requirement: '3.1 Kg / Can' },
      { characteristic: 'Flavor & Taste', requirement: 'Characteristic Ripe Totapuri Flavour, Tart-Sweet' },
    ],
  },
  {
    id: 'kesar-mango-pulp',
    name: 'Kesar Mango Pulp',
    variety: 'kesar',
    colorHex: '#f97316',
    moq: '215 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Natural Fruit Puree',
    otherNames: 'Gir Kesar Mango Pulp, Queen of Mangoes Puree, Aseptic Kesar Puree',
    mf: '100% Ripe Gir Kesar Mango (Mangifera Indica L.)',
    einecsNo: 'Natural Food Product',
    femaNo: 'Natural Fruit Preparation',
    placeOfOrigin: 'Saurashtra / Gujarat, India (GI Tagged Origin)',
    types: 'Premium Saffron-Aroma Mango Puree',
    brandName: 'Exim India Corporation',
    modelNumber: 'Mango Pulp KMP-03',
    grade: 'Gourmet Food & Export Grade (ISO 9001:2015, FSSAI)',
    colorDesc: 'Deep Ochre to Saffron Orange-Yellow',
    applicationSummary: 'Specialty Desserts, Kesar Mango Kulfi, Milkshakes, Gourmet Fruit Beverages, Bakery Fillings',
    purity: 'High Natural Saffron Aroma & Rich Texture',
    shelfLife: '2 Years (24 Months)',
    packagingDetails: '215 Kg Aseptic Bag in Steel Drums / 850g & 3.1 Kg Cans',
    deliveryDetail: 'Shipped in 15-20 days after order confirmation',
    storage: 'KEEP IN CLOSED CONTAINERS AT AMBIENT TEMPERATURE AND DRY HUMIDITY',
    image: kesarPulpImg,
    analysis: [
      { characteristic: 'Total Soluble Solids (TSS at 20°C)', requirement: 'Min 16.0° – 18.0° Brix' },
      { characteristic: 'Acidity (as Citric Acid % w/w)', requirement: '0.45% – 0.65%' },
      { characteristic: 'pH Value (at 20°C)', requirement: '3.60 – 3.90' },
      { characteristic: 'Consistency (Bostwick at 20°C / 30 sec)', requirement: '8.0 – 12.0 cm' },
      { characteristic: 'Brown Specks', requirement: '< 3 nos per 10g of pulp' },
      { characteristic: 'Black Specks', requirement: 'NIL' },
      { characteristic: 'Aroma & Taste', requirement: 'Intense Saffron-like Natural Kesar Fragrance' },
      { characteristic: 'Commercial Sterility', requirement: 'Free from viable microorganisms' },
    ],
  },
]
