// Master Dataset for Natural Fruit Powder (Spray Dried) with Authentic Export Specifications
// Images imported directly from src/assets/img/nfp/

import appleImg from '../assets/img/nfp/Apple-Juice-Powder-manufacturer.jpg'
import apricotImg from '../assets/img/nfp/apricot.jpg'
import acerolaImg from '../assets/img/nfp/Acerola.jpg'
import bananaImg from '../assets/img/nfp/banana-powder-250x250.jpg'
import custardAppleImg from '../assets/img/nfp/Custard Apple.jpg'
import dateImg from '../assets/img/nfp/Dates.jpg'
import figImg from '../assets/img/nfp/figpowder.png'
import strawberryImg from '../assets/img/nfp/Strawberry-Juice-Powder.jpg'
import grapeImg from '../assets/img/nfp/grapes-extract-powder.jpg'
import guavaImg from '../assets/img/nfp/guava-powder.jpg'
import lemonImg from '../assets/img/nfp/Lemon Powder.jpg'
import limeImg from '../assets/img/nfp/Lime Juice Powder.jpg'
import litchiImg from '../assets/img/nfp/Litchi-powder-factory.jpg'
import mangoImg from '../assets/img/nfp/mango-powder-250x250.jpg'
import orangeImg from '../assets/img/nfp/fruit-juice-powder_orange-250x250.jpg'
import papayaImg from '../assets/img/nfp/Papaya-Powder-Juice-Drink.jpg'
import pineappleImg from '../assets/img/nfp/Pineapple-powder-factory.jpg'
import pomegranateImg from '../assets/img/nfp/Pomegranate-Juice-Powder.jpg'
import amlaImg from '../assets/img/nfp/amla-powder.jpg'

export const FRUIT_POWDER_ANALYSIS_SPECS = [
  { characteristic: 'Physical Appearance', requirement: 'Fine Free-Flowing Spray-Dried Powder' },
  { characteristic: 'Solubility in Cold Water', requirement: '100% Instantly Soluble / Easily Dispersible' },
  { characteristic: 'Processing Method', requirement: 'Low-Temperature Spray Drying preserving natural aromas & vitamins' },
  { characteristic: 'Moisture Content', requirement: '< 4.00% Max' },
  { characteristic: 'Total Ash', requirement: '< 3.00% Max' },
  { characteristic: 'Bulk Density', requirement: '0.50 – 0.75 g/ml' },
  { characteristic: 'Particle Size Distribution', requirement: '100% passes through 80 Mesh' },
  { characteristic: 'Heavy Metals (as Pb), Max.', requirement: '< 5.00 ppm' },
  { characteristic: 'Total Plate Count (CFU/g)', requirement: '< 1000 CFU/g' },
  { characteristic: 'Yeast & Mould (CFU/g)', requirement: '< 50 CFU/g (E. Coli & Salmonella Absent)' },
]

export const FRUIT_POWDER_APPLICATIONS = [
  {
    category: 'Beverages & Instant Drink Mixes',
    use: 'RTD beverage powders, fruit juices, flavored smoothies, energy drink mixes, and functional teas.',
    advantage: 'Delivers authentic natural fruit taste, genuine aroma, and instant reconstitution in water.',
  },
  {
    category: 'Bakery & Confectionery',
    use: 'Cake batters, fruit fillings, fondant, macaron shells, chocolate centers, and cookie premixes.',
    advantage: 'Heat-stable fruit flavor profile without adding excess moisture to doughs and fillings.',
  },
  {
    category: 'Dairy & Ice Creams',
    use: 'Flavored yogurts, frozen desserts, fruit milkshakes, soft-serve premixes, and artisanal cheeses.',
    advantage: 'Imparts natural fruit color and smooth texture without curdling dairy proteins.',
  },
  {
    category: 'Nutraceuticals & Dietary Supplements',
    use: 'Superfood blends, meal replacement shakes, effervescent vitamin tablets, and immunity boosters.',
    advantage: 'Rich in naturally occurring vitamin C, antioxidants, polyphenols, and dietary dietary minerals.',
  },
]

export const NATURAL_FRUIT_POWDERS = [
  {
    id: 'apple-juice-powder',
    name: 'Apple Juice Powder',
    fruitFamily: 'Pome Fruit',
    image: appleImg,
    category: 'orchard',
    groupName: 'Orchard & Berries',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Crisp, refreshing spray-dried apple juice powder rich in natural malic acid and pectin. Highly sought after for instant infant formulas, cereal coatings, and cider drink powders.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'apricot-juice-powder',
    name: 'Apricot Juice Powder',
    fruitFamily: 'Stone Fruit',
    image: apricotImg,
    category: 'orchard',
    groupName: 'Orchard & Berries',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Golden aromatic apricot juice powder delivering delicate stone-fruit sweetness. Excellent for bakery glazes, dessert yogurts, and confectionery fondants.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'acerola-juice-powder',
    name: 'Acerola Juice Powder',
    fruitFamily: 'Super Berry',
    image: acerolaImg,
    category: 'superfood',
    groupName: 'Superfoods & Citrus',
    moq: '50 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Ultra-high Vitamin C (natural ascorbic acid 17-25%) superberry powder. Premium choice for dietary immunity tablets, clean-label dough conditioning, and functional smoothies.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'banana-pulp-powder',
    name: 'Banana Pulp Powder',
    fruitFamily: 'Tropical Fruit',
    image: bananaImg,
    category: 'tropical',
    groupName: 'Tropical Exotic',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Rich, creamy spray-dried ripe Cavendish banana pulp powder with full potassium retention. Ideal for baby weaning foods, milkshakes, bakery batters, and snack fillings.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'custard-apple-powder',
    name: 'Custard Apple Powder',
    fruitFamily: 'Tropical Fruit',
    image: custardAppleImg,
    category: 'tropical',
    groupName: 'Tropical Exotic',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Exotic Sitaphal (custard apple) spray-dried powder preserving velvety sweetness and floral notes. Perfect for artisan kulfi, gourmet milk desserts, and exotic cocktail syrups.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'date-powder',
    name: 'Date Powder',
    fruitFamily: 'Mediterranean / Desert Fruit',
    image: dateImg,
    category: 'superfood',
    groupName: 'Superfoods & Citrus',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Natural unrefined date sweetener powder high in dietary fiber and potassium. A healthy 1:1 white sugar replacement for granola bars, sports nutrition, and wellness biscuits.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'fig-powder',
    name: 'Fig Powder',
    fruitFamily: 'Mediterranean Fruit',
    image: figImg,
    category: 'orchard',
    groupName: 'Orchard & Berries',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Nutrient-rich dried fig powder offering deep caramel honey flavors. Used widely in digestion supplements, breakfast cereals, artisan breads, and savory chutney mixes.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'strawberry-juice-powder',
    name: 'Strawberry Juice Powder',
    fruitFamily: 'Berry',
    image: strawberryImg,
    category: 'orchard',
    groupName: 'Orchard & Berries',
    moq: '100 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Naturally sweet and tangy real strawberry juice powder with vivid natural pink tint. Highly demanded for ice-cream mixes, yogurt premixes, jelly candies, and protein drinks.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'grape-powder',
    name: 'Grape Powder',
    fruitFamily: 'Berry',
    image: grapeImg,
    category: 'orchard',
    groupName: 'Orchard & Berries',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Polyphenol-rich spray-dried grape extract powder offering rich wine-like fruitiness and tartness. Premium ingredient for beverage bases, gummy chews, and cardiovascular nutraceuticals.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'guava-powder',
    name: 'Guava Powder',
    fruitFamily: 'Tropical Fruit',
    image: guavaImg,
    category: 'tropical',
    groupName: 'Tropical Exotic',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Tropical pink and white guava spray-dried powder packed with natural lycopene and dietary fiber. Excellent for spiced fruit nectars, fruit roll-ups, and cocktail mixes.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'lemon-juice-powder',
    name: 'Lemon Juice Powder',
    fruitFamily: 'Citrus',
    image: lemonImg,
    category: 'superfood',
    groupName: 'Superfoods & Citrus',
    moq: '100 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Zesty, sharp spray-dried lemon juice powder high in natural citric acid. Perfect for instant lemonade premixes, tea flavorings, seasoning rubs, and marinades.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'lime-juice-powder',
    name: 'Lime Juice Powder',
    fruitFamily: 'Citrus',
    image: limeImg,
    category: 'superfood',
    groupName: 'Superfoods & Citrus',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Intense aromatic key lime powder delivering bright tropical acidity. Extensively formulated in confectionery centers, mojito syrups, and dry seasoning blends.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'litchi-pulp-powder',
    name: 'Litchi Pulp Powder',
    fruitFamily: 'Tropical Fruit',
    image: litchiImg,
    category: 'tropical',
    groupName: 'Tropical Exotic',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Exquisite fragrant litchi pulp powder with authentic floral sweetness. Highly favored in bubble tea powders, jellies, confectionery hard candies, and dessert creams.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'mango-juice-powder',
    name: 'Mango Juice Powder',
    fruitFamily: 'Tropical Fruit',
    image: mangoImg,
    category: 'tropical',
    groupName: 'Tropical Exotic',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'King of Fruits spray-dried Alphonso & Totapuri mango powder capturing peak aroma, carotenoids, and tropical richness for beverages, puddings, and ice creams.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'orange-juice-powder',
    name: 'Orange Juice Powder',
    fruitFamily: 'Citrus',
    image: orangeImg,
    category: 'superfood',
    groupName: 'Superfoods & Citrus',
    moq: '100 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Sun-drenched citrus sinensis spray-dried orange juice powder with pure citrus burst. A staple in breakfast drink powders, effervescent tablets, and gelatin desserts.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'papaya-juice-powder',
    name: 'Papaya Juice Powder',
    fruitFamily: 'Tropical Fruit',
    image: papayaImg,
    category: 'tropical',
    groupName: 'Tropical Exotic',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Pure spray-dried papaya juice powder retaining active papain enzyme and beta-carotene. Renowned for digestives, tropical health drinks, and natural tenderizers.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'pineapple-juice-powder',
    name: 'Pineapple Juice Powder',
    fruitFamily: 'Tropical Fruit',
    image: pineappleImg,
    category: 'tropical',
    groupName: 'Tropical Exotic',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Vibrant sweet-tart pineapple powder containing bromelain. Superior ingredient for tropical punch drinks, pina colada premixes, bakery icings, and health foods.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'pomegranate-juice-powder',
    name: 'Pomegranate Juice Powder',
    fruitFamily: 'Super Fruit',
    image: pomegranateImg,
    category: 'superfood',
    groupName: 'Superfoods & Citrus',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Deep crimson antioxidant powerhouse rich in punicalagins and ellagic acid. Ideal for anti-aging supplements, luxury chocolate truffles, and gourmet vinaigrette dry rubs.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
  {
    id: 'amla-powder',
    name: 'Amla (Gooseberry) Powder',
    fruitFamily: 'Ayurvedic Superfood',
    image: amlaImg,
    category: 'superfood',
    groupName: 'Superfoods & Citrus',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg food-grade fibre drum with dual polyethylene inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    storage: 'Store in a cool (< 25°C), dry place in airtight containers away from humidity and direct sunlight.',
    applicationSummary: 'Therapeutic Indian Gooseberry spray-dried extract renowned for natural vitamin C, tannins, and rejuvenative wellness. Core ingredient for herbal formulations, hair care, and immunity powders.',
    analysis: FRUIT_POWDER_ANALYSIS_SPECS,
  },
]
