// Master Dataset for Natural Food Colors & Botanical Extracts with Authentic Specifications and Analytical Data
// Images imported directly from src/assets/img/nfc/

import caramelImg from '../assets/img/nfc/Caramel.jpg'
import caramelLiquidImg from '../assets/img/nfc/Caramel-liquid-Single-strength.jpeg'
import caramelPowderImg from '../assets/img/nfc/Caramel-powder.jpeg'
import annattoNorBixinImg from '../assets/img/nfc/high-quality-annatto-nor-bixin-powder.jpg'
import annattoBixinImg from '../assets/img/nfc/annatto-powder.jpg'
import betaCaroteneImg from '../assets/img/nfc/High-quality-Beta-Carotene-5-Liquid.jpg'
import paprikaOleoresinImg from '../assets/img/nfc/High-Quality-PAPRIKA-OLEORESIN-40000-CU-Water.jpg'
import chlorophyllOilImg from '../assets/img/nfc/ch-green.jpg'
import chlorophyllWaterImg from '../assets/img/nfc/water-green.jpg'
import redBeetImg from '../assets/img/nfc/red-beet.jpg'
import curcuminImg from '../assets/img/nfc/curcumina.jpg'
import orangeFruitJuiceImg from '../assets/img/nfc/Orange-color-Fruit-Juice-Powder.jpg'
import acidYellowImg from '../assets/img/nfc/High-quality-Acid-Yellow-73.jpg'

export const NATURAL_COLOR_STABILITY_SPECS = [
  { colorant: 'Curcumin (E100)', source: 'Curcuma Longa (Turmeric)', solubility: 'Water / Alcohol Dispersible', phRange: 'pH 2.0 – 9.0 (Yellow to Orange)', heatStability: 'Excellent (Up to 140°C)', lightStability: 'Moderate (Protect from UV)' },
  { colorant: 'Chlorophyllin (E141)', source: 'Spinach & Alfalfa Leaves', solubility: 'Water / Oil Soluble Grades', phRange: 'pH 4.0 – 10.0 (Vivid Green)', heatStability: 'Very Good (Up to 100°C)', lightStability: 'Good (Copper Stabilized)' },
  { colorant: 'Annatto (E160b)', source: 'Bixa Orellana Seeds', solubility: 'Water (Nor-Bixin) / Oil (Bixin)', phRange: 'pH 3.5 – 8.5 (Warm Yellow-Orange)', heatStability: 'Good (Up to 125°C)', lightStability: 'Good' },
  { colorant: 'Beta-Carotene (E160a)', source: 'Fermentation / Carrot Extracts', solubility: 'Water Dispersible Emulsion', phRange: 'pH 3.0 – 7.0 (Bright Orange-Yellow)', heatStability: 'Good (With Antioxidants)', lightStability: 'Good' },
  { colorant: 'Paprika Oleoresin (E160c)', source: 'Capsicum Annuum', solubility: 'Water Dispersible / Oil Soluble', phRange: 'pH 3.0 – 8.0 (Vibrant Red-Orange)', heatStability: 'Very Good', lightStability: 'Good' },
  { colorant: 'Beetroot Red (E162)', source: 'Beta Vulgaris (Red Beet)', solubility: 'Freely Water Soluble', phRange: 'pH 3.5 – 6.5 (Rich Magenta-Red)', heatStability: 'Moderate (Cold / Low Heat Process)', lightStability: 'Fair to Good' },
  { colorant: 'Caramel (E150a-d)', source: 'Controlled Carbohydrate Heating', solubility: 'Completely Water Soluble', phRange: 'pH 2.5 – 9.0 (Amber to Dark Brown)', heatStability: 'Outstanding (Up to 180°C)', lightStability: 'Outstanding' },
]

export const NATURAL_FOOD_COLORS = [
  {
    id: 'caramel-natural-color',
    name: 'Caramel Natural Color',
    colorFamily: 'brown',
    colorHex: '#78350f',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '8028-89-5',
    ecNo: 'E-150',
    otherNames: 'Caramel Colorant, Burnt Sugar Coloring, Natural Brown Color',
    mf: 'Complex Carbohydrate Polymer',
    einecsNo: '232-435-9',
    femaNo: '2235',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Natural Food Colorant, Flavoring Agent & Viscosity Modifier',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC CAR-01',
    grade: 'Food Grade (Class I / III / IV FCC & FSSAI Compliant)',
    colorDesc: 'Dark Brown to Deep Black Viscous Liquid / Powder',
    applicationSummary: 'Bakery Goods, Confectionery, Soft Drinks, Beers, Spirits, Sauces & Gravies',
    purity: 'High Color Intensity & Acid Stability',
    shelfLife: '2 Years',
    packagingDetails: '25/50 Kg HDPE Food Grade Drums / 25 Kg Poly-lined Cartons',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A COOL, DRY PLACE AWAY FROM DIRECT HEAT AND SUNLIGHT',
    image: caramelImg,
    analysis: [
      { characteristic: 'Color Intensity (Absorbance at 610 nm)', requirement: '0.080 – 0.120 AU' },
      { characteristic: 'Specific Gravity (at 20°C)', requirement: '1.250 – 1.340 g/cm³' },
      { characteristic: 'pH Value (Direct)', requirement: '2.50 – 4.50' },
      { characteristic: 'Total Sulphur (as S)', requirement: '< 0.50%' },
      { characteristic: 'Total Nitrogen (as N)', requirement: '< 0.50%' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
      { characteristic: 'Arsenic (As)', requirement: '< 1.00 ppm' },
      { characteristic: 'Lead (Pb)', requirement: '< 2.00 ppm' },
    ],
  },
  {
    id: 'caramel-liquid-single-strength',
    name: 'Caramel Liquid Single Strength',
    colorFamily: 'brown',
    colorHex: '#92400e',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '8028-89-5',
    ecNo: 'E-150a (Class I Plain Caramel)',
    otherNames: 'Plain Caramel Color, Caustic Caramel, Single Strength Brown Color',
    mf: 'Pure Heated Sucrose / Glucose',
    einecsNo: '232-435-9',
    femaNo: '2235',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Natural Food & Spirit Coloring Agent',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC CLSS-02',
    grade: 'Food & Distillery Grade (FCC & EU Approved)',
    colorDesc: 'Rich Golden Amber to Dark Brown Liquid',
    applicationSummary: 'Whiskeys, Rums, High-Proof Spirits, Craft Beers, Vinegars, Bakery Fillings & Syrups',
    purity: 'Single Strength High Alcohol Stability (> 80% ABV)',
    shelfLife: '2 Years',
    packagingDetails: '30/50/250 Kg Food Grade HDPE Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A COOL, DRY PLACE AWAY FROM FREEZING CONDITIONS',
    image: caramelLiquidImg,
    analysis: [
      { characteristic: 'Specific Gravity (at 20°C)', requirement: '1.260 – 1.300 g/cm³' },
      { characteristic: 'Color Intensity (EBC Unit)', requirement: '20,000 – 26,000' },
      { characteristic: 'pH Value (Direct)', requirement: '3.00 – 4.20' },
      { characteristic: 'Alcohol Stability (at 80° Proof)', requirement: 'Completely Clear, No Precipitation' },
      { characteristic: 'Sulphur Dioxide (SO2)', requirement: '< 10.00 ppm' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
    ],
  },
  {
    id: 'caramel-powder',
    name: 'Caramel Powder',
    colorFamily: 'brown',
    colorHex: '#581c87',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '8028-89-5',
    ecNo: 'E-150d (Class IV Sulphite Ammonia Caramel)',
    otherNames: 'Spray-Dried Caramel Powder, Acid-Proof Caramel Powder',
    mf: 'Modified Carbohydrate Polymer',
    einecsNo: '232-435-9',
    femaNo: '2235',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Free-Flowing Spray-Dried Natural Colorant',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC CRP-03',
    grade: 'Food Grade (Acid-Resistant & Carbonated Beverage Grade)',
    colorDesc: 'Dark Brown Hygroscopic Fine Powder',
    applicationSummary: 'Instant Beverage Premixes, Soup Powders, Gravies, Spice Seasonings, Dry Cake Mixes, Coffee Blends',
    purity: 'High Solubility in Cold Water (> 99.5%)',
    shelfLife: '2 Years',
    packagingDetails: '20/25 Kg Multi-layer Kraft Bags with food-grade PE liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A MOISTURE-PROOF WAREHOUSE; HYGROSCOPIC',
    image: caramelPowderImg,
    analysis: [
      { characteristic: 'Color Intensity (0.1% Solution at 610 nm)', requirement: '0.220 – 0.280 AU' },
      { characteristic: 'Loss on Drying (Moisture)', requirement: '≤ 4.50%' },
      { characteristic: 'pH Value (10% Solution)', requirement: '2.80 – 3.80' },
      { characteristic: 'Total Ash', requirement: '≤ 8.00%' },
      { characteristic: '4-MEI (4-Methylimidazole)', requirement: '< 150.00 ppm (Complies with EU/US Limits)' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
    ],
  },
  {
    id: 'annatto-nor-bixin-powder',
    name: 'Annatto Nor Bixin Powder',
    colorFamily: 'orange',
    colorHex: '#ea580c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '542-40-5',
    ecNo: 'E-160b(ii) (Water Soluble Annatto)',
    otherNames: 'Nor-Bixin Powder, Water Soluble Annatto Extract, Natural Orange Yellow',
    mf: 'C24H28O4 (Dicarboxylic Carotenoid)',
    einecsNo: '208-810-8',
    femaNo: '2103',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Water-Soluble Carotenoid Food Colorant',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC ANBP-04',
    grade: 'Food Grade (FSSAI, FCC, JECFA Compliant)',
    colorDesc: 'Deep Red-Orange Free Flowing Powder',
    applicationSummary: 'Cheddar Cheese, Processed Cheese, Dairy Drinks, Macaroni, Snack Extrusions, Confectionery',
    purity: 'Nor-Bixin Content: 10% – 20% (High Purity)',
    shelfLife: '2 Years',
    packagingDetails: '20/25 Kg Corrugated Cartons with inner PE liners',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A COOL, DARK, DRY PLACE PROTECTED FROM MOISTURE & OXYGEN',
    image: annattoNorBixinImg,
    analysis: [
      { characteristic: 'Nor-Bixin Content (Spectrophotometric)', requirement: '≥ 15.00%' },
      { characteristic: 'Moisture Content', requirement: '≤ 6.00%' },
      { characteristic: 'pH (1% Aqueous Solution)', requirement: '9.00 – 11.50' },
      { characteristic: 'Water Solubility', requirement: 'Completely Dispersible / Soluble' },
      { characteristic: 'Arsenic (As)', requirement: '< 1.00 ppm' },
      { characteristic: 'Lead (Pb)', requirement: '< 2.00 ppm' },
    ],
  },
  {
    id: 'annatto-bixin-powder',
    name: 'Annatto Bixin Powder',
    colorFamily: 'orange',
    colorHex: '#c2410c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '6983-79-9',
    ecNo: 'E-160b(i) (Oil Soluble Annatto)',
    otherNames: 'Bixin Powder, Oil Soluble Annatto Extract, Natural Warm Gold',
    mf: 'C25H30O4',
    einecsNo: '230-248-7',
    femaNo: '2103',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Oil-Soluble Natural Carotenoid Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC ABP-05',
    grade: 'Food Grade (Dairy & Bakery Monograph)',
    colorDesc: 'Dark Orange-Red Microcrystalline Powder',
    applicationSummary: 'Butter, Margarines, Bakery Shortenings, Salad Dressings, Popcorn Oils, Processed Cheese Slices',
    purity: 'Bixin Content: 5% – 15%',
    shelfLife: '2 Years',
    packagingDetails: '20/25 Kg Fibre Drums / Multi-wall Paper Bags',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE IN TIGHTLY SEALED CONTAINERS PROTECTED FROM DIRECT LIGHT',
    image: annattoBixinImg,
    analysis: [
      { characteristic: 'Bixin Content (HPLC / UV)', requirement: '≥ 10.00%' },
      { characteristic: 'Loss on Drying', requirement: '≤ 5.00%' },
      { characteristic: 'Oil Solubility (in Vegetable Oil)', requirement: 'Completely Soluble upon Mild Heating' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
    ],
  },
  {
    id: 'beta-carotene-5-liquid',
    name: 'Beta Carotene 5 Liquid',
    colorFamily: 'orange',
    colorHex: '#f97316',
    moq: '25 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '7235-40-7',
    ecNo: 'E-160a',
    otherNames: 'Pro-Vitamin A Liquid, Beta-Carotene 5% Emulsion, Natural Orange Color',
    mf: 'C40H56',
    einecsNo: '230-636-6',
    femaNo: '2160',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Water-Dispersible Liquid Carotenoid Colorant',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC BCL-06',
    grade: 'Food & Nutrition Grade (USP / FCC / EU Approved)',
    colorDesc: 'Vibrant Orange Viscous Liquid Emulsion',
    applicationSummary: 'Citrus RTD Drinks, Fruit Squashes, Jellies, Dairy Yogurts, Margarines, Pastas & Ice Creams',
    purity: 'Beta-Carotene Content ≥ 5.0% (Enhanced Photostability)',
    shelfLife: '2 Years',
    packagingDetails: '5/25 Kg Food Grade HDPE Cans',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE AT 5°C – 20°C IN A COOL, DRY PLACE PROTECTED FROM LIGHT & AIR',
    image: betaCaroteneImg,
    analysis: [
      { characteristic: 'Assay (Beta-Carotene Content)', requirement: '≥ 5.00%' },
      { characteristic: 'Dispersibility in Water', requirement: 'Instantly Forms Clear to Translucent Orange Dispersion' },
      { characteristic: 'Specific Gravity (at 20°C)', requirement: '1.020 – 1.060 g/cm³' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 5.00 ppm' },
      { characteristic: 'Arsenic (As)', requirement: '< 1.00 ppm' },
    ],
  },
  {
    id: 'paprika-oleoresin-40000-cu',
    name: 'Paprika Oleoresin 40000 CU Water',
    colorFamily: 'orange',
    colorHex: '#dc2626',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '84625-29-6',
    ecNo: 'E-160c',
    otherNames: 'Capsicum Extract, Paprika Extract 40000 CU, Natural Red-Orange Color',
    mf: 'Natural Capsanthin & Capsorubin Complex',
    einecsNo: '283-406-2',
    femaNo: '2834',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Water-Dispersible Natural Red-Orange Extract',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC POCU-07',
    grade: 'Food Grade (De-pungentized / Low Pungency)',
    colorDesc: 'Deep Dark Red Viscous Liquid',
    applicationSummary: 'Processed Meats, Sausages, Seasonings, Snack Flavorings, Sauces, Dressings, Soups, Marinades',
    purity: 'Color Value: 40,000 Color Units (CU)',
    shelfLife: '2 Years',
    packagingDetails: '20/25 Kg Food Grade HDPE Drums / Jerry Cans',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A COOL, DRY WAREHOUSE AWAY FROM DIRECT SUNLIGHT',
    image: paprikaOleoresinImg,
    analysis: [
      { characteristic: 'Color Value (ASTA 20.1 / CU)', requirement: '≥ 40,000 Color Units' },
      { characteristic: 'Residual Solvent (Acetone / Hexane)', requirement: '< 10.00 ppm (Complies with FCC)' },
      { characteristic: 'Capsaicin (Pungency)', requirement: '< 0.01% (De-pungentized)' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
    ],
  },
  {
    id: 'chlorophyll-oil-soluble',
    name: 'Chlorophyll Green Color Oil Soluble',
    colorFamily: 'green',
    colorHex: '#15803d',
    moq: '50 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '1406-65-1',
    ecNo: 'E-141(i) (Copper Chlorophyll Oil Soluble)',
    otherNames: 'Oil Soluble Chlorophyll, Copper Complexes of Chlorophyll, Natural Olive Green',
    mf: 'Copper Phaeophytin Complex',
    einecsNo: '215-800-7',
    femaNo: 'Natural Green Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Oil-Soluble Natural Green Colorant',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC CGO-08',
    grade: 'Food & Cosmetic Grade',
    colorDesc: 'Deep Dark Olive Green Viscous Liquid',
    applicationSummary: 'Vegetable Oils, Cooking Fats, Margarines, Pastry Creams, Herbal Cosmetics, Soaps, Candles',
    purity: 'Copper Complexed for High Heat & Light Stability',
    shelfLife: '2 Years',
    packagingDetails: '5/25 Kg HDPE Food Grade Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A COOL, DARK PLACE PROTECTED FROM MOISTURE',
    image: chlorophyllOilImg,
    analysis: [
      { characteristic: 'Total Copper Chlorophyllin', requirement: '≥ 95.00% (of total colorants)' },
      { characteristic: 'Free Ionic Copper', requirement: '< 200.00 ppm' },
      { characteristic: 'Total Copper Content', requirement: '≤ 8.00%' },
      { characteristic: 'Solubility in Vegetable Oil', requirement: 'Completely Miscible' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
    ],
  },
  {
    id: 'chlorophyll-water-soluble',
    name: 'Chlorophyll Green Color Water Soluble',
    colorFamily: 'green',
    colorHex: '#16a34a',
    moq: '50 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '28302-36-5',
    ecNo: 'E-141(ii) (Sodium Copper Chlorophyllin)',
    otherNames: 'Sodium Copper Chlorophyllin, Water Soluble Green, Natural Emerald Color',
    mf: 'C34H31CuN4Na3O6',
    einecsNo: '248-950-7',
    femaNo: 'Natural Green Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Water-Soluble Natural Green Colorant Powder / Liquid',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC CGW-09',
    grade: 'Food, Confectionery & Pharma Grade',
    colorDesc: 'Blue-Green to Dark Green Free Flowing Powder',
    applicationSummary: 'Beverages, Frozen Desserts, Sugar Confectionery, Mint Jellies, Sauces, Toothpastes, Dietary Supplements',
    purity: 'Total Copper Chlorophyllins ≥ 95.0%',
    shelfLife: '2 Years',
    packagingDetails: '10/25 Kg Poly-lined Cartons / Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN TIGHTLY CLOSED CONTAINERS IN A DRY, AMBIENT WAREHOUSE',
    image: chlorophyllWaterImg,
    analysis: [
      { characteristic: 'Absorbance at 405 nm (1% Aqueous Solution)', requirement: '≥ 500' },
      { characteristic: 'pH Value (1% Solution)', requirement: '8.50 – 10.50' },
      { characteristic: 'Loss on Drying', requirement: '≤ 5.00%' },
      { characteristic: 'Free Ionic Copper', requirement: '< 200.00 ppm' },
      { characteristic: 'Arsenic (As)', requirement: '< 1.00 ppm' },
      { characteristic: 'Lead (Pb)', requirement: '< 2.00 ppm' },
    ],
  },
  {
    id: 'red-beet-powder',
    name: 'Red Beet Powder',
    colorFamily: 'red',
    colorHex: '#be185d',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '7659-95-2',
    ecNo: 'E-162 (Beetroot Red / Betanin)',
    otherNames: 'Beetroot Red Extract, Betanin Powder, Natural Crimson Powder',
    mf: 'C24H26N2O13',
    einecsNo: '231-628-5',
    femaNo: 'Natural Red Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Spray-Dried Pure Botanical Red Colorant',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC RBP-10',
    grade: 'Food Grade (Clean Label Certified)',
    colorDesc: 'Fine Dark Red to Purplish-Red Powder',
    applicationSummary: 'Fruit Beverages, Condiments, Gelatin Desserts, Candies, Dairy Yogurts, Ice Creams, Meat Substitutes',
    purity: 'Betanin Content ≥ 0.40% – 1.00% (Direct Extraction)',
    shelfLife: '2 Years',
    packagingDetails: '20/25 Kg Multi-layer Kraft Paper Bags with PE inner liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A COOL, DRY PLACE (BELOW 20°C); PROTECT FROM MOISTURE & AIR',
    image: redBeetImg,
    analysis: [
      { characteristic: 'Betanin Content (Spectrophotometric at 535 nm)', requirement: '≥ 0.45%' },
      { characteristic: 'Loss on Drying (Moisture)', requirement: '≤ 6.00%' },
      { characteristic: 'pH (1% Aqueous Solution)', requirement: '4.00 – 6.00' },
      { characteristic: 'Total Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
      { characteristic: 'Arsenic (As)', requirement: '< 1.00 ppm' },
    ],
  },
  {
    id: 'curcumin-yellow-color',
    name: 'Curcumin Yellow Color',
    colorFamily: 'yellow',
    colorHex: '#eab308',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '458-37-7',
    ecNo: 'E-100 (Curcumin Extract)',
    otherNames: 'Turmeric Extract 95%, Natural Turmeric Yellow, C.I. Natural Yellow 3',
    mf: 'C21H20O6',
    einecsNo: '207-280-5',
    femaNo: '2349',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Standardized Botanical Polyphenol Colorant',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC CYC-11',
    grade: 'Food, Pharma & Dietary Supplement Grade',
    colorDesc: 'Bright Golden Yellow Crystalline Powder',
    applicationSummary: 'Beverages, Dairy Milks & Cheeses, Confectionery, Pastries, Pickles, Mustard, Functional Dietary Supplements',
    purity: 'Total Curcuminoids ≥ 95.0% (HPLC)',
    shelfLife: '3 Years',
    packagingDetails: '25 Kg Poly-lined Fibre Drums',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN LIGHT-PROOF CONTAINERS IN A DRY, AMBIENT ENVIRONMENT',
    image: curcuminImg,
    analysis: [
      { characteristic: 'Total Curcuminoids Content (HPLC)', requirement: '≥ 95.00%' },
      { characteristic: 'Melting Point', requirement: '180°C – 183°C' },
      { characteristic: 'Loss on Drying', requirement: '≤ 1.00%' },
      { characteristic: 'Residue on Ignition (Ash)', requirement: '≤ 0.10%' },
      { characteristic: 'Residual Solvents', requirement: 'Complies with USP Limits (< 50 ppm)' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
    ],
  },
  {
    id: 'orange-fruit-juice-powder',
    name: 'Orange Color Fruit Juice Powder',
    colorFamily: 'orange',
    colorHex: '#fb923c',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: 'Natural Fruit Preparation',
    ecNo: 'Fruit Powder Colorant',
    otherNames: 'Spray-Dried Orange Powder, Natural Juice Color Base',
    mf: '100% Selected Orange Juice Concentrate on Maltodextrin Carrier',
    einecsNo: 'Food Product',
    femaNo: 'GRAS Listed',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Spray-Dried Fruit Colorant & Flavoring Base',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC OFJP-12',
    grade: 'Beverage & Confectionery Grade',
    colorDesc: 'Bright Natural Orange Free-Flowing Powder',
    applicationSummary: 'Instant Beverage Premixes, Fruit Drink Powders, Confectionery Fillings, Bakery Icing, Energy Formulations',
    purity: '100% Free from Synthetic Dyes',
    shelfLife: '2 Years',
    packagingDetails: '20/25 Kg Multi-wall Paper Bags with food-grade PE liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A COOL, DRY WAREHOUSE; HYGROSCOPIC',
    image: orangeFruitJuiceImg,
    analysis: [
      { characteristic: 'Moisture Content', requirement: '≤ 4.50%' },
      { characteristic: 'Total Soluble Solids (Reconstituted)', requirement: '≥ 10.0° Brix' },
      { characteristic: 'Solubility in Cold Water', requirement: 'Instant & Complete' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 5.00 ppm' },
    ],
  },
  {
    id: 'acid-yellow-73',
    name: 'Acid Yellow 73',
    colorFamily: 'yellow',
    colorHex: '#facc15',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '518-47-8',
    ecNo: 'C.I. 45350',
    otherNames: 'Fluorescein Sodium, D&C Yellow No. 8, Uranine, Fluorescent Tracer Dye',
    mf: 'C20H10Na2O5',
    einecsNo: '208-253-0',
    femaNo: 'Technical & Cosmetic Colorant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'High-Fluorescence Water Soluble Colorant & Diagnostic Tracer',
    brandName: 'Exim India Corporation',
    modelNumber: 'NFC AY-13',
    grade: 'Cosmetic & Industrial Diagnostic Grade',
    colorDesc: 'Intense Reddish-Orange Powder (Bright Green Fluorescence in Solution)',
    applicationSummary: 'Cosmetics, Bath Salts, Soaps, Leak Detection Tracers, Industrial Water Flow Testing, Antifreeze Marking',
    purity: 'Pure Dye Content ≥ 90.0%',
    shelfLife: '5 Years',
    packagingDetails: '25 Kg Fibre Drums with inner poly liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE IN TIGHTLY CLOSED CONTAINERS IN A DRY, WELL-VENTILATED AREA',
    image: acidYellowImg,
    analysis: [
      { characteristic: 'Pure Dye Content (Spectrophotometric)', requirement: '≥ 90.00%' },
      { characteristic: 'Loss on Drying (at 105°C)', requirement: '≤ 7.00%' },
      { characteristic: 'Water-Insoluble Matter', requirement: '≤ 0.50%' },
      { characteristic: 'Chlorides & Sulphates', requirement: '≤ 5.00%' },
      { characteristic: 'Heavy Metals (as Pb)', requirement: '< 10.00 ppm' },
    ],
  },
]
