// Master Dataset for Pearl Pigment Powder with Authentic Specifications, Optical Guides and Analytical Data
// Images imported directly from src/assets/img/pearl/

import micaImg from '../assets/img/pearl/1.png'
import brilliantGoldImg from '../assets/img/pearl/2.png'
import amberRedImg from '../assets/img/pearl/3.png'
import silverPearlImg from '../assets/img/pearl/4.png'
import copperFineImg from '../assets/img/pearl/5.png'
import ci77019Img from '../assets/img/pearl/6.png'

export const PEARL_PIGMENT_ANALYSIS_SPECS = [
  { characteristic: 'Physical Appearance', requirement: 'Lustrous, Free-Flowing Pearlescent Flakes / Powder' },
  { characteristic: 'Particle Size Distribution (80% within)', requirement: '10 – 60 Microns (Silky Luster) / 20 – 100 Microns (Sparkle)' },
  { characteristic: 'Loss on Drying (at 105°C for 2 hrs)', requirement: '≤ 0.50%' },
  { characteristic: 'pH Value (10% Aqueous Slurry)', requirement: '6.50 – 8.50' },
  { characteristic: 'Total Heavy Metals (as Pb), Max.', requirement: '10.00 ppm' },
  { characteristic: 'Lead (Pb), Max.', requirement: '02.00 ppm' },
  { characteristic: 'Arsenic (As), Max.', requirement: '01.00 ppm' },
  { characteristic: 'Mercury (Hg), Max.', requirement: '0.10 ppm' },
  { characteristic: 'Cadmium (Cd), Max.', requirement: '01.00 ppm' },
  { characteristic: 'Total Aerobic Microbial Count', requirement: '< 100 CFU/g (Pathogens Absent)' },
]

export const PEARL_EFFECTS_GUIDE = [
  { shade: 'Pure Mica Base (C.I. 77019)', substrate: 'Natural Muscovite Flakes', coating: 'Uncoated / Purified', effect: 'Silky Translucent Sheen, Non-Grit Texture', application: 'Foundation Powders, Mineral Makeup, Confectionery Dusting' },
  { shade: 'Brilliant Gold Pearl', substrate: 'Mica Flakes (52 – 62%)', coating: 'TiO2 (32 – 40%) + Fe2O3 (4 – 8%)', effect: 'Luminous Regal Gold Reflection', application: 'Chocolate Coatings, Wedding Cakes, Lipsticks, Eye Shadows' },
  { shade: 'Amber Red Pearl', substrate: 'Mica Flakes (50 – 58%)', coating: 'Iron Oxide Fe2O3 (42 – 50%)', effect: 'Deep Radiant Copper-Red Metallic Sparkle', application: 'Gourmet Sugarcraft, Blushers, Nail Lacquers, Lip Gloss' },
  { shade: 'Silver Sparkle Pearl', substrate: 'Mica Flakes (68 – 76%)', coating: 'Rutile TiO2 (24 – 32%)', effect: 'Brilliant Diamond-Like Pure White Luster', application: 'Frostings, Dragées, Champagne Truffles, Highlighters' },
  { shade: 'Copper Fine Pearl', substrate: 'Mica Flakes (55 – 64%)', coating: 'Iron Oxide Fe2O3 (36 – 45%)', effect: 'Warm Antique Metallic Bronze Finish', application: 'Fondant Accents, Bronzers, Body Lotions, Soaps' },
]

export const PEARL_PIGMENT_PRODUCTS = [
  {
    id: 'sparkling-mica',
    name: 'Sparkling Food and Cosmetic Grade Mica',
    category: 'mica',
    colorHex: '#e2e8f0',
    moq: '250 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '12001-26-2',
    ciName: 'C.I. 77019 (Mica / Muscovite)',
    otherNames: 'Purified Potassium Aluminum Silicate, Food Grade Mica, Cosmetic Mineral Flakes',
    mf: 'KAl2(AlSi3O10)(F,OH)2',
    einecsNo: '310-127-6',
    femaNo: 'US-FDA 21 CFR § 73.350',
    placeOfOrigin: 'Maharashtra / Rajasthan, India',
    types: 'Ultra-Pure Lamellar Pearlescent Substrate',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pearl Pigment MC-01',
    grade: 'Food & Cosmetic Grade (USP / EU Directive 231/2012)',
    colorDesc: 'Translucent White Silky Platelets',
    applicationSummary: 'Confectionery Glazes, Tablet Coatings, Mineral Face Powders, Body Shimmers, Toothpastes',
    purity: 'Purity ≥ 99.0% (Natural Silicate Matrix)',
    shelfLife: '5 Years',
    packagingDetails: '25 Kgs Fibre Drums with double food-grade PE liner / 25 Kg Cartons',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'KEEP TIGHTLY SEALED IN A CLEAN, DRY AMBIENT WAREHOUSE AWAY FROM DUST',
    image: micaImg,
    analysis: PEARL_PIGMENT_ANALYSIS_SPECS,
  },
  {
    id: 'brilliant-gold',
    name: 'Sparkling Food & Cosmetic Grade Pearl Pigment - Brilliant Gold',
    category: 'gold',
    colorHex: '#eab308',
    moq: '250 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '12001-26-2 / 13463-67-7 / 1309-37-1',
    ciName: 'C.I. 77019 + C.I. 77891 + C.I. 77491',
    otherNames: 'Gold Luster Pigment, Brilliant Gold Food Pearl, Edible Gold Sparkle',
    mf: 'Mica / TiO2 / Fe2O3 Composite',
    einecsNo: 'Multi-Component Inorganic Complex',
    femaNo: 'US-FDA 21 CFR § 73.350 Compliant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Inorganic Multilayer Pearlescent Luster Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pearl Pigment BG-02',
    grade: 'Food Grade & Cosmetic Grade (FSSAI, EU E171/E172 Compliant)',
    colorDesc: 'Rich Radiant Golden Sparkle Powder',
    applicationSummary: 'Celebration Cakes, Chocolate Praline Glazes, Sugarcraft Flowers, Eye Shadows, Lipsticks, Shimmer Lotions',
    purity: 'High Interference Golden Reflection',
    shelfLife: '5 Years',
    packagingDetails: '25 Kgs Fibre Drums with PE inner liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN DRY, COVERED CONDITIONS AT AMBIENT TEMPERATURE',
    image: brilliantGoldImg,
    analysis: PEARL_PIGMENT_ANALYSIS_SPECS,
  },
  {
    id: 'amber-red',
    name: 'Sparkling Food & Cosmetic Grade Pearl Pigment - Amber Red',
    category: 'red',
    colorHex: '#b91c1c',
    moq: '250 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '12001-26-2 / 1309-37-1',
    ciName: 'C.I. 77019 + C.I. 77491 (Iron Oxide Red)',
    otherNames: 'Amber Red Pearl Pigment, Copper Red Mica, Metallic Crimson Pearl',
    mf: 'Mica / Fe2O3 High Refractive Composite',
    einecsNo: 'Multi-Component Inorganic Complex',
    femaNo: 'US-FDA 21 CFR § 73.350 Compliant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Metallic Luster Pearlescent Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pearl Pigment AR-03',
    grade: 'Food Grade & Cosmetic Grade',
    colorDesc: 'Deep Amber-Reddish Bronze Sparkling Powder',
    applicationSummary: 'Festive Confections, Fondant Draping, Cocktail Rimmers, Blushers, Nail Lacquers, Lip Glosses',
    purity: 'High Heat Resistance up to 800°C',
    shelfLife: '5 Years',
    packagingDetails: '25 Kgs Fibre Drums with PE inner liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN DRY, COVERED CONDITIONS AT AMBIENT TEMPERATURE',
    image: amberRedImg,
    analysis: PEARL_PIGMENT_ANALYSIS_SPECS,
  },
  {
    id: 'silver-sparkle',
    name: 'Sparkling Food & Cosmetic Grade Pearl Pigment - Silver',
    category: 'silver',
    colorHex: '#94a3b8',
    moq: '250 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '12001-26-2 / 13463-67-7',
    ciName: 'C.I. 77019 + C.I. 77891 (Titanium Dioxide)',
    otherNames: 'Silver White Pearl, Diamond Luster Mica, Rutile Silver Pearl',
    mf: 'Mica Coated with Rutile TiO2',
    einecsNo: 'Multi-Component Inorganic Complex',
    femaNo: 'US-FDA 21 CFR § 73.350 Compliant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'High-Brightness Silver White Interference Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pearl Pigment SP-04',
    grade: 'Food Grade & Cosmetic Grade',
    colorDesc: 'Brilliant Diamond White Pearlescent Powder',
    applicationSummary: 'Wedding Cake Frosting, Champagne Dragées, Macaron Dusting, Highlighting Powders, Pearly Shampoos',
    purity: 'High Specular Reflectivity',
    shelfLife: '5 Years',
    packagingDetails: '25 Kgs Fibre Drums with PE inner liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN DRY, COVERED CONDITIONS AT AMBIENT TEMPERATURE',
    image: silverPearlImg,
    analysis: PEARL_PIGMENT_ANALYSIS_SPECS,
  },
  {
    id: 'copper-fine',
    name: 'Sparkling Pearl Pigment Food Grade & Cosmetic Grade - Copper Fine',
    category: 'gold',
    colorHex: '#c2410c',
    moq: '250 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '12001-26-2 / 1309-37-1',
    ciName: 'C.I. 77019 + C.I. 77491',
    otherNames: 'Copper Fine Luster, Antique Copper Mica, Fine Metallic Bronze Pearl',
    mf: 'Mica Coated with Iron Oxide',
    einecsNo: 'Multi-Component Inorganic Complex',
    femaNo: 'US-FDA 21 CFR § 73.350 Compliant',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Microfine Metallic Luster Pearlescent Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pearl Pigment CF-05',
    grade: 'Food Grade & Cosmetic Grade',
    colorDesc: 'Warm Satin Metallic Copper Fine Powder',
    applicationSummary: 'Gourmet Chocolates, Sugarcraft Ribbons, Bronzers, Tinted Lip Balms, Soap Colorants, Body Butters',
    purity: 'Smooth Non-Abrasive Micro-Flakes',
    shelfLife: '5 Years',
    packagingDetails: '25 Kgs Fibre Drums with PE inner liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN DRY, COVERED CONDITIONS AT AMBIENT TEMPERATURE',
    image: copperFineImg,
    analysis: PEARL_PIGMENT_ANALYSIS_SPECS,
  },
  {
    id: 'pearl-pigment-ci-77019',
    name: 'Pearl Pigment Food & Cosmetic Grade - CI No 77019',
    category: 'mica',
    colorHex: '#cbd5e1',
    moq: '250 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '12001-26-2',
    ciName: 'C.I. 77019 (Natural Mica)',
    otherNames: 'High Purity Muscovite C.I. 77019, Satin White Mineral Luster, Cosmetic Filler Mica',
    mf: 'Natural Potassium Aluminum Silicate Mineral',
    einecsNo: '310-127-6',
    femaNo: 'US-FDA 21 CFR § 73.350',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Standard Monograph Pearlescent White Mineral',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pearl Pigment CI-06',
    grade: 'Food Grade & Cosmetic Grade (E171/E172 Substrate)',
    colorDesc: 'Pure White to Soft Pearlescent Satin Powder',
    applicationSummary: 'Capsule Shells, Chewing Gums, Marshmallow Dusting, Pressed Eyeshadows, Mineral Foundations, Toothpastes',
    purity: 'High Chemical Inertness & UV Resistance',
    shelfLife: '5 Years',
    packagingDetails: '25 Kgs Fibre Drums with PE inner liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN DRY, COVERED CONDITIONS AT AMBIENT TEMPERATURE',
    image: ci77019Img,
    analysis: PEARL_PIGMENT_ANALYSIS_SPECS,
  },
]
