// Master Dataset for Pharmaceutical Colours with Authentic Pharmacopoeia (IP/BP/USP/EP) Specifications
// Images imported from src/assets/img/synthesis-food-color/ and src/assets/img/lake/

import tartrazineImg from '../assets/img/synthesis-food-color/high-quality-Tartrazine.jpg'
import sunsetYellowImg from '../assets/img/synthesis-food-color/Sunset-Yellow-FCF-aluminum-lake.jpg'
import ponceauImg from '../assets/img/synthesis-food-color/High-quality-food-color-Ponceau.jpg'
import alluraRedImg from '../assets/img/synthesis-food-color/Allura-Red-colour.jpg'
import carmoisineImg from '../assets/img/synthesis-food-color/Food-Color-Carmoisine.jpg'
import erythrosineImg from '../assets/img/synthesis-food-color/food-grade-erythrosine.jpg'
import brilliantBlueImg from '../assets/img/synthesis-food-color/Brilliant-Blue.jpg'
import indigoCarmineImg from '../assets/img/synthesis-food-color/Indigo-Carmine.png'
import quinolineYellowImg from '../assets/img/synthesis-food-color/Quinoline-yellow.jpg'
import brownHtImg from '../assets/img/synthesis-food-color/Brown-HT.jpg'

import lakeTartrazineImg from '../assets/img/lake/lake-tartrazine.jpg'
import ponceau4rLakeImg from '../assets/img/lake/Ponceau-4R.jpg'
import lakeAlluraRedImg from '../assets/img/lake/lake-allura-red.jpg'
import sunsetYellowLakeImg from '../assets/img/efc/Sunset-Yellow-FCF-aluminum-lake.jpg'
import carmoisineLakeImg from '../assets/img/efc/Food-Color-Carmoisine.jpg'
import erythrosineLakeImg from '../assets/img/efc/food-grade-erythrosine.jpg'

export const PHARMA_ANALYSIS_SPECS = [
  { characteristic: 'Total Pure Dye Content, Min.', requirement: '85.00% – 90.00% (Dyes) / 15.00% – 40.00% (Lakes)' },
  { characteristic: 'Volatile Matter at 135°C & Chlorides/Sulphates, Max.', requirement: '13.00%' },
  { characteristic: 'Water-Insoluble Matter, Max.', requirement: '00.20%' },
  { characteristic: 'Combined Ether Extracts, Max.', requirement: '00.20%' },
  { characteristic: 'Unsulfonated Primary Aromatic Amines (as aniline), Max.', requirement: '00.01%' },
  { characteristic: 'Subsidiary Dyes & Intermediates, Max.', requirement: '01.00%' },
  { characteristic: 'Lead (Pb), mg/kg, Max.', requirement: '02.00 ppm' },
  { characteristic: 'Arsenic (As), mg/kg, Max.', requirement: '01.00 ppm' },
  { characteristic: 'Cadmium (Cd), mg/kg, Max.', requirement: '00.50 ppm' },
  { characteristic: 'Mercury (Hg), mg/kg, Max.', requirement: '00.50 ppm' },
  { characteristic: 'Total Heavy Metals (as Pb), Max.', requirement: '10.00 ppm' },
  { characteristic: 'Total Aerobic Microbial Count (TAMC)', requirement: '< 100 CFU/g (Pathogens Absent)' },
]

export const PHARMACEUTICAL_COLORS = [
  {
    id: 'pharma-tartrazine',
    name: 'Pharma Tartrazine',
    formType: 'soluble-dyes',
    colorFamily: 'yellows-oranges',
    colorHex: '#eab308',
    pharmacopoeia: 'IP / BP / USP / EP',
    eNumber: 'E102',
    ciNo: '19140',
    fdcName: 'FD&C Yellow No. 5',
    casNo: '1934-21-0',
    einecsNo: '217-699-5',
    femaNo: 'Tartrazine Yellow',
    otherNames: 'Acid Yellow 23, Food Yellow 4',
    mf: 'C16H9N4Na3O9S2',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Pharma Tartrazine IP/USP',
    grade: 'Pharmaceutical Grade (GMP & WHO-GMP Certified)',
    colorDesc: 'High Purity Bright Yellow Powder',
    applicationSummary: 'Oral Liquids, Pediatric Syrups, Effervescent Tablets, Hard Gelatin Capsules',
    purity: '87.00% Min Pure Dye (Pharmacopoeia Compliant)',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: tartrazineImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-sunset-yellow',
    name: 'Pharma Sunset Yellow FCF',
    formType: 'soluble-dyes',
    colorFamily: 'yellows-oranges',
    colorHex: '#ea580c',
    pharmacopoeia: 'IP / BP / USP / EP',
    eNumber: 'E110',
    ciNo: '15985',
    fdcName: 'FD&C Yellow No. 6',
    casNo: '2783-94-0',
    einecsNo: '220-491-7',
    femaNo: 'Sunset Yellow FCF',
    otherNames: 'Orange Yellow S, Food Yellow 3',
    mf: 'C16H10N2Na2O7S2',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Sunset Yellow IP/USP',
    grade: 'Pharmaceutical Grade (GMP Certified)',
    colorDesc: 'Bright Reddish-Orange Powder',
    applicationSummary: 'Oral Suspensions, Antacids, Chewable Tablets, Vitamin Formulations',
    purity: '86.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: sunsetYellowImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-allura-red',
    name: 'Pharma Allura Red',
    formType: 'soluble-dyes',
    colorFamily: 'reds-pinks',
    colorHex: '#dc2626',
    pharmacopoeia: 'USP / NF / EP',
    eNumber: 'E129',
    ciNo: '16035',
    fdcName: 'FD&C Red No. 40',
    casNo: '25956-17-6',
    einecsNo: '247-368-0',
    femaNo: 'Allura Red AC',
    otherNames: 'Food Red 17, Curry Red',
    mf: 'C18H14N2Na2O8S2',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Allura Red USP/NF',
    grade: 'Pharmaceutical Grade (USP-NF & EP)',
    colorDesc: 'Dark Red Fine Powder',
    applicationSummary: 'Cough Syrups, Antibiotic Suspensions, Gelatin Capsule Shells',
    purity: '88.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: alluraRedImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-ponceau-4r',
    name: 'Pharma Ponceau 4R',
    formType: 'soluble-dyes',
    colorFamily: 'reds-pinks',
    colorHex: '#be123c',
    pharmacopoeia: 'IP / BP',
    eNumber: 'E124',
    ciNo: '16255',
    fdcName: 'Food Red 7',
    casNo: '2611-82-7',
    einecsNo: '220-036-2',
    femaNo: 'Ponceau 4R',
    otherNames: 'Cochineal Red A, Acid Red 18',
    mf: 'C20H11N2Na3O10S3',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Ponceau 4R IP',
    grade: 'Pharmaceutical Grade (IP / BP Certified)',
    colorDesc: 'Deep Crimson Red Powder',
    applicationSummary: 'Oral Tonics, Expectorants, Coated Granules, Medicated Lozenges',
    purity: '85.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: ponceauImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-carmoisine',
    name: 'Pharma Carmoisine',
    formType: 'soluble-dyes',
    colorFamily: 'reds-pinks',
    colorHex: '#9f1239',
    pharmacopoeia: 'IP / BP',
    eNumber: 'E122',
    ciNo: '14720',
    fdcName: 'Food Red 3',
    casNo: '3567-69-9',
    einecsNo: '222-657-4',
    femaNo: 'Azorubine',
    otherNames: 'Azorubine, Ext. D&C Red 10',
    mf: 'C20H12N2Na2O7S2',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Carmoisine IP',
    grade: 'Pharmaceutical Grade (IP / BP)',
    colorDesc: 'Fine Ruby Red Powder',
    applicationSummary: 'Liquid Analgesics, Antibacterial Syrups, Toothpastes & Gels',
    purity: '85.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: carmoisineImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-erythrosine',
    name: 'Pharma Erythrosine',
    formType: 'soluble-dyes',
    colorFamily: 'reds-pinks',
    colorHex: '#f43f5e',
    pharmacopoeia: 'IP / BP / USP',
    eNumber: 'E127',
    ciNo: '45430',
    fdcName: 'FD&C Red No. 3',
    casNo: '16423-68-0',
    einecsNo: '240-474-8',
    femaNo: 'Erythrosine B',
    otherNames: 'Food Red 14, Acid Red 51',
    mf: 'C20H6I4Na2O5',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Erythrosine IP/USP',
    grade: 'Pharmaceutical Grade (IP / USP Compliant)',
    colorDesc: 'Vivid Cherry-Pink Powder',
    applicationSummary: 'Capsule Shells, Dental Plaque Disclosing Agents, Tablet Coatings',
    purity: '87.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: erythrosineImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-brilliant-blue',
    name: 'Pharma Brilliant Blue FCF',
    formType: 'soluble-dyes',
    colorFamily: 'blues',
    colorHex: '#0284c7',
    pharmacopoeia: 'IP / BP / USP / EP',
    eNumber: 'E133',
    ciNo: '42090',
    fdcName: 'FD&C Blue No. 1',
    casNo: '3844-45-9',
    einecsNo: '223-339-8',
    femaNo: 'Brilliant Blue FCF',
    otherNames: 'Acid Blue 9, Food Blue 2',
    mf: 'C37H34N2Na2O9S3',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Brilliant Blue IP/USP',
    grade: 'Pharmaceutical Grade (IP / BP / USP / EP)',
    colorDesc: 'Reddish-Blue Granular Powder',
    applicationSummary: 'Oral Drops, Mouthwashes, Antiseptic Gels, Capsule Banding',
    purity: '88.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: brilliantBlueImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-indigo-carmine',
    name: 'Pharma Indigo Carmine',
    formType: 'soluble-dyes',
    colorFamily: 'blues',
    colorHex: '#2563eb',
    pharmacopoeia: 'IP / BP / USP / EP',
    eNumber: 'E132',
    ciNo: '73015',
    fdcName: 'FD&C Blue No. 2',
    casNo: '860-22-0',
    einecsNo: '212-728-8',
    femaNo: 'Indigotine',
    otherNames: 'Indigotine, Acid Blue 74',
    mf: 'C16H8N2Na2O8S2',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye & Diagnostic Agent',
    brandName: 'Exim India Corporation',
    modelNumber: 'Indigo Carmine IP/USP',
    grade: 'Pharmaceutical & Diagnostic Grade',
    colorDesc: 'Dark Blue-Purple Powder',
    applicationSummary: 'Urological Diagnostic Markers, Kidney Function Testing, Tablet Film Coating',
    purity: '85.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: indigoCarmineImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-quinoline-yellow',
    name: 'Pharma Quinoline Yellow',
    formType: 'soluble-dyes',
    colorFamily: 'yellows-oranges',
    colorHex: '#facc15',
    pharmacopoeia: 'IP / BP / EP',
    eNumber: 'E104',
    ciNo: '47005',
    fdcName: 'Food Yellow 13',
    casNo: '8004-92-0',
    einecsNo: '305-897-5',
    femaNo: 'Quinoline Yellow',
    otherNames: 'Acid Yellow 3, D&C Yellow 10 (Water-Soluble)',
    mf: 'C18H9NNa2O8S2',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Quinoline Yellow IP/BP',
    grade: 'Pharmaceutical Grade (IP / BP / EP)',
    colorDesc: 'Bright Greenish-Yellow Fine Powder',
    applicationSummary: 'Antibiotic Powders, Multivitamin Syrups, Disinfectant Solutions',
    purity: '85.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: quinolineYellowImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-brown-ht',
    name: 'Pharma Brown HT',
    formType: 'soluble-dyes',
    colorFamily: 'yellows-oranges',
    colorHex: '#78350f',
    pharmacopoeia: 'IP / BP',
    eNumber: 'E155',
    ciNo: '20285',
    fdcName: 'Food Brown 1',
    casNo: '4553-89-3',
    einecsNo: '224-924-0',
    femaNo: 'Chocolate Brown HT',
    otherNames: 'Chocolate Brown HT, Food Brown 1',
    mf: 'C27H18N4Na2O9S2',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Pharmaceutical Water-Soluble Certified Dye',
    brandName: 'Exim India Corporation',
    modelNumber: 'Brown HT IP',
    grade: 'Pharmaceutical Grade (IP / BP)',
    colorDesc: 'Deep Chocolate Brown Powder',
    applicationSummary: 'Iron Tonics, Chocolate Flavored Chewable Tablets, Syrups',
    purity: '85.00% Min Pure Dye',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: brownHtImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-lake-tartrazine',
    name: 'Pharma Lake Tartrazine',
    formType: 'coating-lakes',
    colorFamily: 'yellows-oranges',
    colorHex: '#eab308',
    pharmacopoeia: 'IP / USP / BP Coating Grade',
    eNumber: 'E102',
    ciNo: '19140:1',
    fdcName: 'FD&C Yellow No. 5 Lake',
    casNo: '1934-21-0',
    einecsNo: '217-699-5',
    femaNo: 'Tartrazine Lake',
    otherNames: 'Tartrazine Aluminum Lake (Pharma)',
    mf: 'C16H9N4Na3O9S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Insoluble Tablet Film Coating Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Tartrazine Pharma Grade',
    grade: 'Pharmaceutical Coating Grade (IP / USP)',
    colorDesc: 'Micro-Pulverized Yellow Lake Powder',
    applicationSummary: 'Film Coating of Tablets, Moisture Barrier Premixes, Dry Suspension Granules',
    purity: '24% – 28% Pure Dye Content (Low & High Dye options)',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: lakeTartrazineImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-lake-sunset-yellow',
    name: 'Pharma Lake Sunset Yellow',
    formType: 'coating-lakes',
    colorFamily: 'yellows-oranges',
    colorHex: '#ea580c',
    pharmacopoeia: 'IP / USP / BP Coating Grade',
    eNumber: 'E110',
    ciNo: '15985:1',
    fdcName: 'FD&C Yellow No. 6 Lake',
    casNo: '15790-07-5',
    einecsNo: '239-888-1',
    femaNo: 'Sunset Yellow Lake',
    otherNames: 'Sunset Yellow FCF Aluminum Lake (Pharma)',
    mf: 'C16H10N2Na2O7S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Insoluble Tablet Coating Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Sunset Yellow Pharma',
    grade: 'Pharmaceutical Coating Grade (IP / USP)',
    colorDesc: 'Vibrant Orange Microfine Lake Powder',
    applicationSummary: 'Oral Solid Dosage Forms, Film Coating Suspensions, ODT Tablets',
    purity: '22% – 26% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: sunsetYellowLakeImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-lake-allura-red',
    name: 'Pharma Lake Allura Red',
    formType: 'coating-lakes',
    colorFamily: 'reds-pinks',
    colorHex: '#dc2626',
    pharmacopoeia: 'USP / NF / EP Coating Grade',
    eNumber: 'E129',
    ciNo: '16035:1',
    fdcName: 'FD&C Red No. 40 Lake',
    casNo: '25956-17-6',
    einecsNo: '247-368-0',
    femaNo: 'Allura Red AC Lake',
    otherNames: 'Allura Red Aluminum Lake (Pharma)',
    mf: 'C18H14N2Na2O8S2·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Insoluble Tablet Film Coating Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Allura Red Pharma',
    grade: 'Pharmaceutical Coating Grade (USP-NF & EP)',
    colorDesc: 'Uniform Bright Red Lake Powder',
    applicationSummary: 'Enteric & Film Coating of Analgesic & Antibiotic Tablets',
    purity: '24% – 28% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: lakeAlluraRedImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-lake-brilliant-blue',
    name: 'Pharma Lake Brilliant Blue',
    formType: 'coating-lakes',
    colorFamily: 'blues',
    colorHex: '#0284c7',
    pharmacopoeia: 'IP / USP / BP Coating Grade',
    eNumber: 'E133',
    ciNo: '42090:1',
    fdcName: 'FD&C Blue No. 1 Lake',
    casNo: '3844-45-9',
    einecsNo: '223-339-8',
    femaNo: 'Brilliant Blue Lake',
    otherNames: 'Brilliant Blue FCF Aluminum Lake (Pharma)',
    mf: 'C37H34N2Na2O9S3·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Insoluble Tablet Coating Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Brilliant Blue Pharma',
    grade: 'Pharmaceutical Coating Grade (IP / USP / EP)',
    colorDesc: 'Fine Brilliant Blue Lake Powder',
    applicationSummary: 'Softgels, Film Coated Tablets, Capsule Shells & Antihistamine Pills',
    purity: '20% – 25% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: brilliantBlueImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-lake-ponceau-4r',
    name: 'Pharma Lake Ponceau 4R',
    formType: 'coating-lakes',
    colorFamily: 'reds-pinks',
    colorHex: '#be123c',
    pharmacopoeia: 'IP / BP Coating Grade',
    eNumber: 'E124',
    ciNo: '16255:1',
    fdcName: 'Food Red 7 Lake',
    casNo: '2611-82-7',
    einecsNo: '220-036-2',
    femaNo: 'Ponceau 4R Lake',
    otherNames: 'Ponceau 4R Aluminum Lake (Pharma)',
    mf: 'C20H11N2Na3O10S3·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Insoluble Tablet Film Coating Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Ponceau 4R Pharma',
    grade: 'Pharmaceutical Coating Grade (IP / BP)',
    colorDesc: 'Scarlet Red Lake Powder',
    applicationSummary: 'Sugar Coating & Film Coating of Cardiac & Vitamin Tablets',
    purity: '22% – 26% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: ponceau4rLakeImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
  {
    id: 'pharma-lake-erythrosine',
    name: 'Pharma Lake Erythrosine',
    formType: 'coating-lakes',
    colorFamily: 'reds-pinks',
    colorHex: '#f43f5e',
    pharmacopoeia: 'IP / USP Coating Grade',
    eNumber: 'E127',
    ciNo: '45430:1',
    fdcName: 'FD&C Red No. 3 Lake',
    casNo: '16423-68-0',
    einecsNo: '240-474-8',
    femaNo: 'Erythrosine Lake',
    otherNames: 'Erythrosine Aluminum Lake (Pharma)',
    mf: 'C20H6I4Na2O5·Al',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Insoluble Tablet Film Coating Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Lake Erythrosine Pharma',
    grade: 'Pharmaceutical Coating Grade (IP / USP)',
    colorDesc: 'Fine Cherry Pink Lake Powder',
    applicationSummary: 'Controlled-Release Pellet Coating, Capsule Shells & Chewables',
    purity: '20% – 25% Pure Dye Content',
    shelfLife: '3 - 5 Years',
    moq: '50 Kgs',
    supplyAbility: '15 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packagingDetails: '25 kg Pharma Fiber Drum with Double Anti-Static Liners',
    deliveryDetail: 'Shipped in 10-15 days after payment with Batch CoA',
    storage: 'Store in tightly closed containers in a dry, cool place protected from light and moisture.',
    image: erythrosineLakeImg,
    analysis: PHARMA_ANALYSIS_SPECS,
  },
]
