// Master Dataset for Powder Flavours with Authentic Specifications
// Images imported directly from src/assets/img/pf/

import bananaImg from '../assets/img/pf/banan-powder.jpg'
import butterscotchImg from '../assets/img/pf/butterscotch.jpg'
import chocolateImg from '../assets/img/pf/chocolate-powder.jpg'
import coconutImg from '../assets/img/pf/coconut-powder.jpg'
import fruitImg from '../assets/img/pf/fruit-powder.jpg'
import lemonImg from '../assets/img/pf/lemon-powder.jpeg'
import mangoImg from '../assets/img/pf/mango-powder.jpg'
import orangeImg from '../assets/img/pf/orange-powder.jpg'
import peppermintImg from '../assets/img/pf/peppermint.jpg'
import pineappleImg from '../assets/img/pf/pineapples.jpg'
import raspberryImg from '../assets/img/pf/raspberry.jpg'
import strawberryImg from '../assets/img/pf/strawberry_powder.jpg'
import vanillaImg from '../assets/img/pf/vanilla.jpg'

export const POWDER_FLAVOURS_ANALYSIS_SPECS = [
  { characteristic: 'Physical Appearance', requirement: 'Fine Free-Flowing Encapsulated Powder' },
  { characteristic: 'Solubility in Water', requirement: '100% Water Soluble / Dispersible' },
  { characteristic: 'Moisture Content', requirement: '< 5.00% Max' },
  { characteristic: 'Encapsulation Matrix', requirement: 'Food Grade Modified Starch / Maltodextrin / Gum Acacia' },
  { characteristic: 'Heat Stability', requirement: 'Baking Heat Stable up to 220°C without flavour loss' },
  { characteristic: 'Heavy Metals (as Pb), Max.', requirement: '< 5.00 ppm' },
  { characteristic: 'Total Plate Count', requirement: '< 1000 CFU/g' },
  { characteristic: 'Yeast & Mould', requirement: '< 100 CFU/g (Pathogens Absent)' },
]

export const POWDER_FLAVOUR_PRODUCTS = [
  {
    id: 'banana-powder-flavour',
    name: 'Banana Powder Flavour',
    image: bananaImg,
    category: 'sweet',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Rich sweet Cavendish banana encapsulated aroma for bakery mixes, biscuits, infant formulas, and milkshake powders.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'coconut-powder-flavour',
    name: 'Coconut Powder Flavour',
    image: coconutImg,
    category: 'sweet',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Tropical creamy desiccated coconut notes designed for confectionery fillings, wafer creams, and savory curry bases.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'butterscotch-powder-flavour',
    name: 'Butterscotch Powder Flavour',
    image: butterscotchImg,
    category: 'sweet',
    moq: '50 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Indulgent brown sugar and rich caramelized butter flavor for puddings, cookies, toffees, and instant coffee premixes.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'chocolate-powder-flavour',
    name: 'Chocolate Powder Flavour',
    image: chocolateImg,
    category: 'sweet',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Deep roasted cocoa profile with smooth chocolate nuances for cocoa beverage powders, cake premixes, and fillings.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'fruit-powder-flavour',
    name: 'Fruit Powder Flavour',
    image: fruitImg,
    category: 'fruit',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Exotic mixed fruit tutti-frutti encapsulated blend for bubble gums, fruit chews, candies, and beverage mixes.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'lemon-powder-flavour',
    name: 'Lemon Powder Flavour',
    image: lemonImg,
    category: 'citrus',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Zesty lemon peel aroma engineered for dry drink powders, pharmaceutical effervescents, and bakery glazes.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'mango-powder-flavour',
    name: 'Mango Powder Flavour',
    image: mangoImg,
    category: 'fruit',
    moq: '100 Kgs',
    supplyAbility: '10 Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Luscious ripe Alphonso mango notes for instant beverage powders, ice cream premixes, and fruit jelly beans.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'orange-powder-flavour',
    name: 'Orange Powder Flavour',
    image: orangeImg,
    category: 'citrus',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Bright citrus sinensis orange flavor with natural terpenes for carbonated dry beverage mixes and chewing gums.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'peppermint-powder-flavour',
    name: 'Peppermint Powder Flavour',
    image: peppermintImg,
    category: 'mint',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Intense cooling menthol crystal aroma for breath fresheners, medicinal tablets, oral care, and chocolate mints.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'pineapple-powder-flavour',
    name: 'Pineapple Powder Flavour',
    image: pineappleImg,
    category: 'fruit',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Sweet-tangy tropical pineapple flavor for candies, cake batters, dry jelly crystals, and tropical mocktails.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'raspberry-powder-flavour',
    name: 'Raspberry Powder Flavour',
    image: raspberryImg,
    category: 'fruit',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Tart wild red raspberry flavor for pharmaceutical pediatric syrups, gummies, and instant fruit tea mixes.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'strawberry-powder-flavour',
    name: 'Strawberry Powder Flavour',
    image: strawberryImg,
    category: 'fruit',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Classic ripe summer strawberry flavor for milk powder blends, chocolate shells, wafers, and snack coatings.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
  {
    id: 'vanilla-powder-flavour',
    name: 'Vanilla Powder Flavour',
    image: vanillaImg,
    category: 'sweet',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    packaging: '25 Kg corrugated carton with poly inner liner',
    shelfLife: '24 Months from Manufacturing Date',
    applicationSummary: 'Bourbon vanilla bean aroma high in ethyl vanillin tenacity for commercial bakery mixes, custards, and ice creams.',
    analysis: POWDER_FLAVOURS_ANALYSIS_SPECS,
  },
]
