// Master Dataset for Synthetic Food Colours with Complete Chemical Analysis Specifications
// Images imported directly from src/assets/img/synthesis-food-color/

import tartrazineImg from '../assets/img/synthesis-food-color/high-quality-Tartrazine.jpg'
import ponceauImg from '../assets/img/synthesis-food-color/High-quality-food-color-Ponceau.jpg'
import alluraRedImg from '../assets/img/synthesis-food-color/Allura-Red-colour.jpg'
import sunsetYellowImg from '../assets/img/synthesis-food-color/Sunset-Yellow-FCF-aluminum-lake.jpg'
import carmoisineImg from '../assets/img/synthesis-food-color/Food-Color-Carmoisine.jpg'
import erythrosineImg from '../assets/img/synthesis-food-color/food-grade-erythrosine.jpg'
import brownHtImg from '../assets/img/synthesis-food-color/Brown-HT.jpg'
import quinolineYellowImg from '../assets/img/synthesis-food-color/Quinoline-yellow.jpg'
import amarnathImg from '../assets/img/synthesis-food-color/amarnath.jpg'
import brilliantBlueImg from '../assets/img/synthesis-food-color/Brilliant-Blue.jpg'
import indigoCarmineImg from '../assets/img/synthesis-food-color/Indigo-Carmine.png'
import blackPnImg from '../assets/img/synthesis-food-color/Black-PN.jpg'
import red2gImg from '../assets/img/synthesis-food-color/Red 2g.jpg'
import patentBlueVImg from '../assets/img/synthesis-food-color/Patent Blue V.jpg'
import greenSImg from '../assets/img/synthesis-food-color/green s.jpg'

export const STANDARD_ANALYSIS_SPECS = [
  { characteristic: 'Total color/Assay, percent by Mass, min.', requirement: '85.00' },
  { characteristic: 'Volatile matter +Sodium chloride +Sodium Sulphate percent by mass, min.', requirement: '15.00' },
  { characteristic: 'Water-insoluble matter, percent by mass, Max.', requirement: '00.20' },
  { characteristic: 'Combined ether extracts, percent by mass, Max', requirement: '00.20' },
  { characteristic: 'Subsidiary dyes, percent by mass, Max.', requirement: '01.00' },
  { characteristic: 'Dye intermediates, percent by mass, max', requirement: '00.01' },
  { characteristic: 'Unsulfonated primary aromatic amine (calculated as aniline) percent by mass, max.', requirement: '00.01' },
  { characteristic: 'Lead, mg/kg, Max.', requirement: '10.00' },
  { characteristic: 'Arsenic, mg/kg, Max.', requirement: '03.00' },
  { characteristic: 'Heavy metals, (as pb) mg/kg, max', requirement: '40.00' },
  { characteristic: 'Mercury, Cadmium, mg/kg, Max.', requirement: '01.00' },
  { characteristic: 'Cadmium, mg/kg, Max', requirement: '01.00' },
  { characteristic: 'Shelf Life', requirement: '3 Years' },
]

export const SYNTHETIC_FOOD_COLORS = [
  {
    id: 'tartrazine',
    name: 'Tartrazine',
    colorFamily: 'yellow',
    colorHex: '#facc15',
    colorNo: 'Yellow 4',
    ciNo: '19140',
    eNumber: 'E102',
    fdcName: 'FD&C Yellow No 5',
    casNo: '1934-21-0',
    mf: 'C16H9N4Na3O9S2',
    femaNo: 'Tartrazine Yellow',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '19140',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Yellow Powder',
    applicationSummary: 'Bakery, Food additive , Confectionery',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: tartrazineImg,
    moq: '250 Kgs',
    supplyAbility: '20 Metric Tons / Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Bright lemon-yellow azo dye known for outstanding water solubility and thermal stability across confectionery, carbonated beverages, snacks, and oral medications.',
    applications: ['Carbonated Beverages', 'Confectionery & Hard Candies', 'Bakery & Dessert Mixes', 'Pickles & Sauces', 'Pharmaceutical Syrups'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'allura-red',
    name: 'Allura Red Colour',
    colorFamily: 'red',
    colorHex: '#e11d48',
    colorNo: 'Red 17',
    ciNo: '16035',
    eNumber: 'E129',
    fdcName: 'FD&C Red No 40',
    casNo: '25956-17-6',
    mf: 'C18H14N2Na2O8S2',
    femaNo: 'Allura Red',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '16035',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Reddish Powder',
    applicationSummary: 'Bakery, Confectionery, Seasonings, Beverages',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: alluraRedImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Deep ruby-red food colorant offering superior light and heat stability. Globally popular for modern snack seasonings, sports drinks, gelatin desserts, and cosmetics.',
    applications: ['Energy & Sports Drinks', 'Seasoning & Extruded Snacks', 'Gelatin Desserts & Puddings', 'Oral Pharmaceuticals', 'Cosmetics & Lip Care'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'sunset-yellow',
    name: 'Sunset Yellow',
    colorFamily: 'yellow',
    colorHex: '#ea580c',
    colorNo: 'Yellow 3',
    ciNo: '15985',
    eNumber: 'E110',
    fdcName: 'FD&C Yellow No 6',
    casNo: '2783-94-0',
    mf: 'C16H10N2Na2O7S2',
    femaNo: 'Sunset Yellow FCF',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '15985',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Orange Red Powder',
    applicationSummary: 'Citrus Beverages, Bakery, Confectionery, Ice Creams',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: sunsetYellowImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Rich sunset-orange hue widely prized in citrus beverages, apricot jams, cheese snacks, instant soup powders, and baked goods.',
    applications: ['Orange & Citrus Soft Drinks', 'Instant Noodles & Soups', 'Breadcrumbs & Snack Batters', 'Ice Creams & Lollies', 'Confectionery Coatings'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'carmoisine',
    name: 'Carmoisine',
    colorFamily: 'red',
    colorHex: '#be123c',
    colorNo: 'Red 3',
    ciNo: '14720',
    eNumber: 'E122',
    fdcName: 'Azorubine',
    casNo: '3567-69-9',
    mf: 'C20H12N2Na2O7S2',
    femaNo: 'Carmoisine Food Red',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '14720',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Red to Maroon Powder',
    applicationSummary: 'Jellies, Syrups, Soft Drinks, Confectionery',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: carmoisineImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons / Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Rich raspberry-red tone with strong stability at low pH, ideal for fruit juices, yoghurt preparations, flavored cordials, and marzipan.',
    applications: ['Red Berry Flavored Drinks', 'Flavored Yoghurts & Ice Creams', 'Marzipan & Cake Frostings', 'Canned Fruit Preserves', 'Effervescent Tablets'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'black-pn',
    name: 'Black PN',
    colorFamily: 'brown',
    colorHex: '#1e293b',
    colorNo: 'Black 1',
    ciNo: '28440',
    eNumber: 'E151',
    fdcName: 'Brilliant Black BN',
    casNo: '2519-30-4',
    mf: 'C28H17N5Na4O14S4',
    femaNo: 'Black PN',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '28440',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Fine Black Powder',
    applicationSummary: 'Licorice, Sauces, Caviar Substitutes, Inks',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: blackPnImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Solid black synthetic tetrazo dye used to impart pure black or deep purple-black shades in licorice sweets, brown sauces, gravies, and fish paste.',
    applications: ['Black Licorice & Gums', 'Savory Sauces & Marinades', 'Caviar Substitutes & Surimi', 'Bakery Coatings & Fillings', 'Specialty Writing Inks'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'erythrosine',
    name: 'Erythrosine',
    colorFamily: 'red',
    colorHex: '#f43f5e',
    colorNo: 'Red 14',
    ciNo: '45430',
    eNumber: 'E127',
    fdcName: 'FD&C Red No 3',
    casNo: '16423-68-0',
    mf: 'C20H6I4Na2O5',
    femaNo: 'Erythrosine B',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '45430',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Cherry Red / Pink Powder',
    applicationSummary: 'Cherries, Cake Decorating, Hard Gel Capsules, Dentifrice',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: erythrosineImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Fluorescent cherry-pink colorant with specific compatibility in maraschino cherries, cake decoration gels, canned cherries, and pharmaceutical capsules.',
    applications: ['Cocktail & Glacé Cherries', 'Cake Decorating Gels & Piping', 'Dentifrices & Mouthwashes', 'Pharmaceutical Hard Gel Capsules', 'Sausage Casings'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'brown-ht',
    name: 'Brown HT',
    colorFamily: 'brown',
    colorHex: '#78350f',
    colorNo: 'Brown 3',
    ciNo: '20285',
    eNumber: 'E155',
    fdcName: 'Chocolate Brown HT',
    casNo: '4553-89-3',
    mf: 'C27H18N4Na2O9S2',
    femaNo: 'Food Brown 3',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '20285',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Brown Powder',
    applicationSummary: 'Biscuits, Chocolate Flavored Foods, Sauces, Cakes',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: brownHtImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons / Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Rich, natural-looking chocolate brown synthetic diazo dye that replaces cocoa tones in biscuits, toffees, chocolate cakes, and brown sauces.',
    applications: ['Chocolate Cakes & Brownies', 'Toffees & Caramel Confections', 'Biscuits & Cookie Doughs', 'Gravies & Brown Savory Sauces', 'Tobacco & Shisha Flavours'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'amarnath-red',
    name: 'Amarnath Red',
    colorFamily: 'red',
    colorHex: '#9f1239',
    colorNo: 'Red 9',
    ciNo: '16185',
    eNumber: 'E123',
    fdcName: 'Amaranth (FD&C Red No 2)',
    casNo: '915-67-3',
    mf: 'C20H11N2Na3O10S3',
    femaNo: 'Amaranth Red',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '16185',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Dark Red / Magenta Powder',
    applicationSummary: 'Wines, Liqueurs, Icings, Fish Roe',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: amarnathImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons / Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Dark reddish-brown powder delivering clear, deep magenta to dark red shades. Widely utilized in fruit brandies, alcoholic liqueurs, and fish roe in permitted markets.',
    applications: ['Aperitifs & Alcoholic Bitters', 'Fruit Wines & Brandies', 'Cake Icings & Fillings', 'Caviar & Fish Roe', 'Cosmetic Powders'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'quinoline-yellow',
    name: 'Quinoline Yellow',
    colorFamily: 'yellow',
    colorHex: '#eab308',
    colorNo: 'Yellow 13',
    ciNo: '47005',
    eNumber: 'E104',
    fdcName: 'Food Yellow 13',
    casNo: '8004-92-0',
    mf: 'C18H9NNa2O8S2',
    femaNo: 'Quinoline Yellow SS',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '47005',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Greenish Yellow Powder',
    applicationSummary: 'Energy Drinks, Syrups, Tablet Coatings, Liqueurs',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: quinolineYellowImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Clean, greenish-yellow water-soluble dye engineered for energy drinks, liqueurs, fruit syrups, pharmaceutical tablet film coatings, and cosmetics.',
    applications: ['Energy Drinks & Cider', 'Liqueurs & Flavored Alcohol', 'Fruit Flavored Lozenges', 'Tablet Film Coatings', 'Soaps & Shampoos'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'brilliant-blue',
    name: 'Brilliant Blue',
    colorFamily: 'blue',
    colorHex: '#0284c7',
    colorNo: 'Blue 2',
    ciNo: '42090',
    eNumber: 'E133',
    fdcName: 'FD&C Blue No 1',
    casNo: '3844-45-9',
    mf: 'C37H34N2Na2O9S3',
    femaNo: 'Brilliant Blue FCF',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '42090',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Reddish Blue Powder',
    applicationSummary: 'Ice Creams, Confectionery, Beverages, Mouthwash',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: brilliantBlueImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Vivid, electric-blue triarylmethane dye delivering intense coloration at very low dosage. Blendable with Tartrazine to yield magnificent green spectrums.',
    applications: ['Blue Raspberry & Cotton Candy Syrups', 'Sports & Isotonic Beverages', 'Ice Slushies & Popsicles', 'Toothpaste & Oral Hygiene', 'Eye Shadow & Cosmetics'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'indigo-carmine',
    name: 'Indigo Carmine',
    colorFamily: 'blue',
    colorHex: '#1d4ed8',
    colorNo: 'Blue 1',
    ciNo: '73015',
    eNumber: 'E132',
    fdcName: 'FD&C Blue No 2',
    casNo: '860-22-0',
    mf: 'C16H8N2Na2O8S2',
    femaNo: 'Indigotine',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '73015',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Dark Blue / Purple Powder',
    applicationSummary: 'Biscuits, Wafer Creams, Sugar Candies, Pet Food',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: indigoCarmineImg,
    moq: '100 Kgs',
    supplyAbility: '25 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Deep royal blue indigoid dye with distinctive violet-blue cast. High export volume capacity for biscuit cream sandwiches, confectionery, and medical diagnostic solutions.',
    applications: ['Biscuit & Wafer Creams', 'Sugar Confectionery', 'Pet Food & Kibble Formulations', 'Diagnostic Reagents', 'Oral Gel Medications'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'ponceau-4r',
    name: 'Ponceau 4R',
    colorFamily: 'red',
    colorHex: '#dc2626',
    colorNo: 'Red 7',
    ciNo: '16255',
    eNumber: 'E124',
    fdcName: 'Cochineal Red A',
    casNo: '2611-82-7',
    mf: 'C20H11N2Na3O10S3',
    femaNo: 'New Coccine',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '16255',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Bright Red Powder',
    applicationSummary: 'Fruit Syrups, Jams, Sweets, Cake Mixes',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: ponceauImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Vibrant, strawberry-red monoazo synthetic dye with high tinting strength, widely used in fruit cordials, syrups, jams, jellies, and desserts.',
    applications: ['Fruit Syrups & Cordials', 'Jams & Preserves', 'Sweets & Gummy Candies', 'Pastries & Cake Mixes', 'Flavored Dairy Drinks'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'red-2g',
    name: 'Red 2G',
    colorFamily: 'red',
    colorHex: '#b91c1c',
    colorNo: 'Red 10',
    ciNo: '18050',
    eNumber: 'E128',
    fdcName: 'Food Red 10',
    casNo: '3734-67-6',
    mf: 'C18H13N3Na2O8S2',
    femaNo: 'Azogeranine',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '18050',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Red Powder',
    applicationSummary: 'Processed Meats, Inks, Diagnostic Reagents',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: red2gImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'High-tinting red azo powder used under strict regulatory specifications in processed meat seasonings, breakfast sausages, and industrial chemical staining.',
    applications: ['Permitted Export Meat Formulations', 'Industrial Ink Staining', 'Laboratory Diagnostic Reagents', 'Textile & Leather Tints'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'patent-blue-v',
    name: 'Patent Blue V',
    colorFamily: 'blue',
    colorHex: '#0ea5e9',
    colorNo: 'Blue 5',
    ciNo: '42051',
    eNumber: 'E131',
    fdcName: 'Food Blue 5',
    casNo: '3536-49-0',
    mf: 'C27H31N2NaO7S2',
    femaNo: 'Patent Blue V',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '42051',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Cyan Blue Powder',
    applicationSummary: 'Confectionery, Dental Tablets, Liqueurs, Diagnostics',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: patentBlueVImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Luminous cyan-blue triphenylmethane dye widely requested across European and international pharmaceutical, dental tablet, and beverage formulations.',
    applications: ['Fine European Confectionery', 'Dental Plaque Disclosing Tablets', 'Specialty Liqueurs', 'Medical Lymphatic Tracers', 'Bath Gels & Shampoos'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
  {
    id: 'green-s',
    name: 'Green S',
    colorFamily: 'green',
    colorHex: '#15803d',
    colorNo: 'Green 4',
    ciNo: '44090',
    eNumber: 'E142',
    fdcName: 'Wool Green S',
    casNo: '3087-16-9',
    mf: 'C27H25N2NaO7S2',
    femaNo: 'Lissamine Green',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Colorants, Emulsifiers, Flavoring Agents, food color, pharma',
    brandName: 'Exim India Corporation',
    modelNumber: '44090',
    grade: 'Food Grade, Pharma, Cosmetic',
    colorDesc: 'Mint Green / Emerald Powder',
    applicationSummary: 'Canned Vegetables, Mint Sauces, Desserts, Shampoos',
    purity: '99% Min',
    shelfLife: '3 Years',
    packagingDetails: '10/25/50 HDPE DRUMS, BAGS We can also ship by Air and Ship',
    deliveryDetail: 'Shipped in 15 days after payment',
    image: greenSImg,
    moq: '250 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava Sheva) Mumbai',
    description: 'Clean mint-green to emerald dye with excellent brightness in canned peas, mint sauces, lime ice creams, and dessert toppings.',
    applications: ['Mint & Lime Sauces', 'Canned Processed Vegetables', 'Dessert Jellies & Syrups', 'Chewing Gum & Breath Mints', 'Shampoo & Soaps'],
    storage: 'Please keep in closed containers at ambient Temp and Humidity',
    analysis: STANDARD_ANALYSIS_SPECS,
  },
]
