// Master Dataset for Titanium Dioxide (TiO2, C.I. 77891, Pigment White 6) with Authentic Specifications and Analytical Data
// Images imported directly from src/assets/img/to/

import rutileImg from '../assets/img/to/rutile.jpg'
import pharmaFoodImg from '../assets/img/to/pharma-food.jpg'
import anataseImg from '../assets/img/to/anatise.jpg'

export const TIO2_COMPARISON_MATRIX = [
  { parameter: 'Crystal Structure', rutile: 'Tetragonal (High Density 4.23 g/cm³)', anatase: 'Tetragonal (Density 3.90 g/cm³)', pharma: 'High-Purity Anatase (FCC/USP Grade)' },
  { parameter: 'Refractive Index (Opacity)', rutile: '2.73 (Highest Opacity & Hiding Power)', anatase: '2.55 (Bright White, Moderate Opacity)', pharma: '2.55 (High Whiteness, Ultra-Pure)' },
  { parameter: 'Primary Application', rutile: 'Exterior Coatings, Masterbatches & Plastics', anatase: 'Paper, Rubber, Interior Paints & Fibres', pharma: 'Capsules, Tablets, Confectionery & Cosmetics' },
  { parameter: 'Weather & Chalk Resistance', rutile: 'Outstanding (UV-Protected & Surface Treated)', anatase: 'Moderate (Pure Uncoated)', pharma: 'High Photostability in Drug Coatings' },
  { parameter: 'Standard Particle Size (D50)', rutile: '0.20 – 0.30 Microns', anatase: '0.25 – 0.35 Microns', pharma: '0.20 – 0.40 Microns (Nano-Free Conventional)' },
  { parameter: 'Regulatory Standard', rutile: 'ISO 591-1:2000 Class R2', anatase: 'ISO 591-1:2000 Class A1', pharma: 'USP / IP / BP / E171 / US-FDA 21 CFR' },
]

export const TITANIUM_DIOXIDE_PRODUCTS = [
  {
    id: 'rutile-grade',
    name: 'Rutile Grade Titanium Dioxide',
    gradeFamily: 'rutile',
    colorHex: '#0284c7',
    moq: '100 Kgs',
    supplyAbility: '20 Metric Tons/Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '13463-67-7',
    ciName: 'Pigment White 6 (C.I. 77891)',
    otherNames: 'Rutile TiO2, Titanium(IV) Oxide Rutile, Surface Treated White Pigment',
    mf: 'TiO2 (Inorganic Surface Treated with Al2O3 & SiO2)',
    einecsNo: '236-675-5',
    femaNo: 'Industrial White Pigment',
    placeOfOrigin: 'Kerala / Maharashtra, India',
    types: 'High-Durability Rutile Pigment, UV Absorber, Opacifier',
    brandName: 'Exim India Corporation',
    modelNumber: 'Titanium Dioxide RD-01',
    grade: 'Industrial Coating, Masterbatch & Plastics Grade (ISO 591 Class R2)',
    colorDesc: 'Pure Brilliant White Fine Powder',
    applicationSummary: 'Masterbatches, Rigid PVC Pipes, Powder Coatings, Exterior Paints, Inks, Engineering Polymers',
    purity: 'TiO2 Content ≥ 94.0%',
    shelfLife: '5 Years',
    packagingDetails: '25 Kg Multi-wall Paper Bags with PE inner liner / 500 & 1000 Kg Jumbo Bags',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A CLEAN, DRY, COVERED WAREHOUSE AWAY FROM DIRECT RAIN & EXCESSIVE HUMIDITY',
    image: rutileImg,
    analysis: [
      { characteristic: 'TiO2 Content (Main Assay)', requirement: '≥ 94.00%' },
      { characteristic: 'Rutile Crystal Phase Content', requirement: '≥ 98.50%' },
      { characteristic: 'Whiteness (L* Value)', requirement: '≥ 97.50' },
      { characteristic: 'Tinting Strength (Reynolds Index)', requirement: '≥ 1850' },
      { characteristic: 'Oil Absorption', requirement: '18.00 – 22.00 g/100g' },
      { characteristic: 'pH Value of Aqueous Suspension', requirement: '6.50 – 8.50' },
      { characteristic: 'Residue on 325 Mesh (45μm)', requirement: '≤ 0.05%' },
      { characteristic: 'Moisture (Volatile at 105°C)', requirement: '≤ 0.50%' },
    ],
  },
  {
    id: 'pharma-food-grade',
    name: 'Pharma & Food Grade Titanium Dioxide',
    gradeFamily: 'pharma-food',
    colorHex: '#15803d',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '13463-67-7',
    ciName: 'Pigment White 6 (C.I. 77891 / E171)',
    otherNames: 'Food Grade TiO2, Pharmaceutical Titanium Dioxide, IP/BP/USP Grade, Ultra Pure White Colorant',
    mf: 'TiO2 (Pure Anatase Form)',
    einecsNo: '236-675-5',
    femaNo: 'US-FDA 21 CFR § 73.575 & § 73.1575',
    placeOfOrigin: 'Maharashtra, India',
    types: 'Ultra-Pure Opacifying Colorant & Pharmaceutical Excipient',
    brandName: 'Exim India Corporation',
    modelNumber: 'Titanium Dioxide PFG-02',
    grade: 'USP / BP / IP / EP / FCC Food & Pharma Certified',
    colorDesc: 'Odorless Ultra-Fine Brilliant White Powder',
    applicationSummary: 'Hard & Soft Gelatin Capsule Shells, Tablet Film Coatings, Confectionery Sugarcraft, Dairy Whiteners, Toothpastes, Sunscreens',
    purity: '99.0% – 100.5% (Ignited Basis)',
    shelfLife: '5 Years',
    packagingDetails: '25 Kg Poly-lined Fibre Drums / Multi-wall Paper Bags with double food-grade PE liner',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'PRESERVE IN TIGHTLY CLOSED CONTAINERS IN A DRY, AMBIENT ENVIRONMENT PROTECTED FROM CONTAMINATION',
    image: pharmaFoodImg,
    analysis: [
      { characteristic: 'Assay (TiO2 on Ignited Basis)', requirement: '99.00% – 100.50%' },
      { characteristic: 'Loss on Ignition (at 800°C)', requirement: '≤ 0.50%' },
      { characteristic: 'Water-Soluble Substances', requirement: '≤ 0.25%' },
      { characteristic: 'Acid-Soluble Substances', requirement: '≤ 0.50%' },
      { characteristic: 'Total Heavy Metals (as Pb)', requirement: '≤ 10.00 ppm' },
      { characteristic: 'Arsenic (As Content)', requirement: '≤ 1.00 ppm' },
      { characteristic: 'Lead (Pb Content)', requirement: '≤ 2.00 ppm' },
      { characteristic: 'Total Aerobic Microbial Count', requirement: '< 100 CFU/g' },
    ],
  },
  {
    id: 'anatase-grade',
    name: 'Anatase Grade Titanium Dioxide',
    gradeFamily: 'anatase',
    colorHex: '#eab308',
    moq: '100 Kgs',
    supplyAbility: '10 Tons per Month',
    port: 'JNPT, (Nhava sheva) Mumbai',
    casNo: '13463-67-7',
    ciName: 'Pigment White 6 (C.I. 77891)',
    otherNames: 'Anatase TiO2, Uncoated Titanium Dioxide, High Whiteness White Pigment',
    mf: 'TiO2 (Pure Uncoated Anatase Crystal)',
    einecsNo: '236-675-5',
    femaNo: 'Industrial White Pigment',
    placeOfOrigin: 'Kerala / Maharashtra, India',
    types: 'High-Whiteness Water-Dispersible Inorganic Pigment',
    brandName: 'Exim India Corporation',
    modelNumber: 'Titanium Dioxide AG-03',
    grade: 'General Industrial, Paper, Rubber & Textile Grade (ISO 591 Class A1)',
    colorDesc: 'Pure White Soft Granular Powder',
    applicationSummary: 'Paper Coating & Pulp Filling, Interior Emulsion Paints, Rubber Goods, Footwear Soles, Textile Printing & Delustering',
    purity: 'TiO2 Content ≥ 98.0%',
    shelfLife: '5 Years',
    packagingDetails: '25 Kg Woven PP Bags with PE liner / Multi-layer Paper Bags',
    deliveryDetail: 'Shipped in 10-15 days after payment',
    storage: 'STORE IN A COOL, DRY, WELL-VENTILATED AREA PROTECTED FROM MOISTURE',
    image: anataseImg,
    analysis: [
      { characteristic: 'TiO2 Content (Main Assay)', requirement: '≥ 98.00%' },
      { characteristic: 'Whiteness (L* Value)', requirement: '≥ 96.00' },
      { characteristic: 'Tinting Strength (Reynolds Index)', requirement: '≥ 1200' },
      { characteristic: 'Oil Absorption', requirement: '20.00 – 24.00 g/100g' },
      { characteristic: 'pH Value of Aqueous Suspension', requirement: '6.50 – 8.00' },
      { characteristic: 'Residue on 325 Mesh (45μm)', requirement: '≤ 0.08%' },
      { characteristic: 'Water-Soluble Matter', requirement: '≤ 0.40%' },
      { characteristic: 'Moisture (Volatile at 105°C)', requirement: '≤ 0.50%' },
    ],
  },
]
